### ISSUE TITLE
No coverage data generated

### ISSUE THREAD

**Issue by petemounce** [colszowka/simplecov#111]
Hi, I'm a Windows user.  ;-)

I have some rspec tests (environment at end of report) that run and pass that I want to see coverage for.  I've added SimpleCov to the very first 2 lines of my spec_helper.rb (having read through the readme and #60), and I am running my test-suite with `bundle exec rspec -r ..\ruby\spec\spec_helper.rb ..\ruby\spec\deployment\*.rb`.  Sadly, our codebase is a bit ****ed up; our structure looks like the following, because we learned ruby as we went and have not refactored/restructured yet (we're using ruby libraries to functionally-test a set of collaborating MS/.NET websites and applications).

When I run rspec, my coverage json file is largely empty (see below) and index.html shows no classes, but I've definitely got some coverage.  I'd like to get to the bottom of why that is.

spec_helper.rb first lines:
    
    require 'simplecov'
    SimpleCov.start
    # other stuff as before

spec file typical first lines:

    require File.dirname(__FILE__) + '/../spec_helper'
    require "#{File.dirname(__FILE__)}/../../lib/deployment.rb"

(as in, each spec file of several that are being run by rspec have those two lines at the top - I mention it because in #60 I saw some mention of active_support/core_ext multiple-loading causing some kind of issue which, although I didn't follow it, sounded like it might be pertinent.  `deployment.rb` glob-requires a bunch of files, 2 of which both `require active_support/core_ext`)

.resultset.json:

	{
	  "RSpec": {
	    "coverage": {
	    },
	    "timestamp": 1328177801
	  }
	}

ruby is 1.9.3-p0 from rubyinstaller + devkit 4.5.2.

Environment is Windows Server 2008 R2 x64 (fully patched).

bundle show:

    c:\src\root.git\JustEat\build>bundle show
    Gems included by the bundle:
      * activemodel (3.0.9)
      * activerecord (3.0.9)
      * activerecord-sqlserver-adapter (3.0.15)
      * activesupport (3.0.9)
      * aes (0.4.0)
      * arel (2.0.10)
      * builder (2.1.2)
      * bundler (1.0.21)
      * capybara (1.1.2)
      * childprocess (0.2.3)
      * coderay (0.9.8)
      * cucumber (1.1.4.1)
      * diff-lcs (1.1.3)
      * fakeweb (1.3.0)
      * ffi (1.0.11)
      * gherkin (2.7.1)
      * git (1.2.5)
      * headless (0.2.2)
      * i18n (0.5.0)
      * jeweler (1.6.4)
      * json (1.6.3)
      * log4r (1.1.9)
      * macaddr (1.0.0)
      * method_source (0.6.7)
      * mime-types (1.17.2)
      * multi_json (1.0.4)
      * nokogiri (1.5.0)
      * pbkdf2 (0.1.0)
      * pry (0.9.7.4)
      * rack (1.3.5)
      * rack-test (0.6.1)
      * rake (0.9.2.2)
      * rake-dotnet (1.5.8)
      * rdiscount (1.6.8)
      * rest-client (1.6.3)
      * rr (1.0.2)
      * rspec (2.6.0)
      * rspec-core (2.6.4)
      * rspec-expectations (2.6.0)
      * rspec-mocks (2.6.0)
      * ruby-odbc (0.99994)
      * ruby-prof (0.10.8)
      * ruby_parser (2.3.1)
      * rubyzip (0.9.5)
      * selenium-webdriver (2.15.0)
      * sexp_processor (3.0.7)
      * simplecov (0.5.4)
      * simplecov-html (0.5.3)
      * slop (2.1.0)
      * syntax (1.0.0)
      * systemu (2.2.0)
      * tenjin (0.6.1)
      * term-ansicolor (1.0.7)
      * trollop (1.16.2)
      * tzinfo (0.3.29)
      * uuid (2.3.3)
      * win32-api (1.4.8)
      * win32-service (0.7.2)
      * win32console (1.3.0)
      * windows-api (0.4.0)
      * windows-pr (1.2.1)
      * xpath (0.1.4)
      * yard (0.7.2)
      * yard-cucumber (2.1.4)

**Comment by bf4** [comment]
Closing as stale. Please reopen if this is still an issue. (And take a look at https://github.com/colszowka/simplecov/issues/340 )
