### ISSUE TITLE
Zero coverage reported for directories with plus sign (+) in them

### ISSUE THREAD

**Issue by richardxia** [colszowka/simplecov#116]
I'm running Mac OS X 10.6 with Ruby 1.9.2p190 (under rvm) and simplecov 0.6.1. When I run simplecov in a directory containing a plus sign in the middle of it, I get 0 line coverage. Interestingly enough, if the plus sign as at the end of the directory name rather than in the middle, I do get the correct line coverage output. Here is a test case that should reproduce my errors:

/tmp/tmp+tmp/test.rb:

    def foo
    end

/tmp/tmp+tmp/test_spec.rb:

    require 'simplecov'
    SimpleCov.start
    require './test'
    foo

Running test_spec.rb in tmp+tmp causes the output

    Coverage report generated for RSpec to /private/tmp/tmp+tmp/coverage. 0 / 0 LOC (0.0%) covered.

However, moving the directory tmp+tmp to tmp-tmp gives me the correct coverage report:

    Coverage report generated for RSpec to /private/tmp/tmp-tmp/coverage. 1 / 1 LOC (100.0%) covered.

This is a problem on Mac OS X because temporary directories generated by Dir.mktmpdir can contain plus signs in the middle of the path names.

**Comment by ptashman** [comment]
Any fix(es) to this yet?

**Comment by bf4** [comment]
@ptashman what have you tried?  this issue is two years old and I have no way of knowing from your description how similar your issue is.   (Hi @ronwsmith )

**Comment by ptashman** [comment]
I haven't encountered this at all. I'm just asking if it's still an issue so that I can tackle it or else we can mark this as obsolete and close it out.

**Comment by bf4** [comment]
Closing as stale.  Please re-open if this is still an issue.
