### ISSUE TITLE
doesn't count files under lib

### ISSUE THREAD

**Issue by ywen** [colszowka/simplecov#12]
I have this rails project in which I try simplecov. I had 100% coverage. then I created a dummy class in lib, and put a dummy method into it. ran spec again, the coverage was still 100%. Now I moved the same file into app/model. the coverage changed to 98%. Why didn't the files under lib get counted?

**Comment by tilo** [comment]
@colszowka @amatsuda 

so this means: if you use SimpleCov for getting coverage on a Ruby Gem, then you're out of luck, because it doesn't consider files under `./lib`.

This feels completely broken. 

the project description says: "Code coverage for Ruby" , not "for Rails"

this should be fixed.

**Comment by PragTob** [comment]
@tilo it works completely fine, you just need to require your code after simplecov was started as the README indicates. Many people use simplecov for gem code coverage and it's perfectly fine.
