### ISSUE TITLE
How to trace multi-processes with simplecov

### ISSUE THREAD

**Issue by pxie** [colszowka/simplecov#138]
Hi Christoph,

I am trying to use simplecov to trace code coverage in my project. My ruby application will launch several sub-processes via exec() method, and those sub-processes communicate with each other via REST calls, instead of simple ruby method call.

How to setup simplecov to trace multi-processes application?

I have added "SimpleCov.start" for each process launch command, but I only get zero line coverage report, after finished testing.

How to retrieve simplecov logs for troubleshooting?

Thanks.

**Comment by davidgrieser** [comment]
As I went looking for information on this I found the originally referenced PR #126.
