### ISSUE TITLE
gauge coverage of javascript by jasmine test

### ISSUE THREAD

**Issue by adamrneary** [colszowka/simplecov#141]
I could use a separate tool such as JSCoverage, but if there was a way to build that functionality into simplecov that would be spectacular. Is this something you've thought about? Interested in?

Thanks!

**Comment by Callisto13** [comment]
Anyone know if this is now a thing? Would be very useful for my current project!

**Comment by colszowka** [comment]
Nobody stepped in yet to build this, but I think it would be a great feature to have and is up for grabs, according to my implementation description above :)

**Comment by dometto** [comment]
:+1:

**Comment by bf4** [comment]
@dometto are you volunteering?

**Comment by dometto** [comment]
Good question. :-) I'm working on a project where I'll need JS specs soon, if I get to that point I'll definitely want some coverage, so I'll see if I can implement this.

However, we might go with opal completely. Also interested in opal integration for simplecov? [This gem](https://github.com/gdotdesign/quality-control/) seems to [user opal's own coverage statistics](https://github.com/gdotdesign/quality-control/blob/master/opal/rspec_coverage_helper.rb) when present, so it might be easy to do.

**Comment by bf4** [comment]
@dometto there's two ways of doing it that come to mind, since SimpleCov, is fundamentally around the Ruby Coverage module

1. make it easy to feed stats into it and/or document how another tool can do this
2. make a plugin :)

**Comment by AntiFish03** [comment]
This would be awesome! I'd love to help if I can find some time.  Jasmine does not have a coverage reporter built in.  However, Jasmine with Blanket.js is possibility with a custom reporter to add to the `.resultset.json`.

**Comment by ericraio** [comment]
Kind of old but I'd like to bump this, any idea how to get modern JS tools to work with simplecov?

**Comment by bf4** [comment]
@ericraio  there's two ways of doing it that come to mind, since SimpleCov, is fundamentally around the Ruby Coverage module

1. make it easy to feed stats into it and/or document how another tool can do this
1. make a plugin :)

**Comment by PragTob** [comment]
I'm not super sure this is a really necessary/worthwhile thing for simplecov to implement. Sure it sounds great/cool but is the upside of having both of the coverage results in one viewer really worth the work and configuration rather than having 2 separate results?

I mean you'd till need to config coverage for javascript, put in a formatter/plugin, have it right to a file and tell simplecov to pick up the file. We most certainly wouldn't take on creating and maintaining an entire JS tool.

I'm not saying I don't like the idea, I just think the chances are fairly slim.

**Comment by PragTob** [comment]
I believe this is more a place for some other tool to step in. With everything that's left to do I don't think this has any chance of getting done and am hence closing this.

Don't get me wrong, I like the idea but I think the execution is too complex. It might almost be easier to write a new tool that gets coverage output in a defined format and just creates coverage reports for everyone. I've toyed with the idea of building such a thing but it's too far away, also for simplecov.
