### ISSUE TITLE
ActiveSupport::Concern coverage

### ISSUE THREAD

**Issue by masterkain** [colszowka/simplecov#167]
Hello,

``` ruby
    require 'simplecov'
    SimpleCov.use_merging false
    SimpleCov.start 'rails'
```

I have this structure:

`app/models/concerns/api/account.rb`

Added via application.rb:

``` ruby
config.autoload_paths += ["#{config.root}/app/models/concerns", "#{config.root}/app/sweepers)"]
```

My model `app/models/account.rb`

``` ruby
class Account < ActiveRecord::Base
  include Api::Account
end
```

The coverage report does not include `app/models/concerns/api/account.rb` at all.

I tried to `add_group`, no dice.

**Comment by DannyBen** [comment]
I can confirm I am experiencing this as well, in 0.10.0
My concerns are not tested for coverage, even if its test is in `models/concerns`
(I cant work with any of the 0.11.x versions, as it generates reduced coverage with the blank line issues and such).

**Comment by bf4** [comment]
@dankohn please open a new issue describing your version, your test suite, how your running your tests, your gem statement in your gemfile, and where you require/configure simplecov (and reference this issue). Thanks!
