### ISSUE TITLE
Segmentation Fault when running all specs with RSpec

### ISSUE THREAD

**Issue by georgeu2000** [colszowka/simplecov#208]
The following causes a segmentation fault, but only when simplecov is in Gemfile:

```
c.run_all_when_everything_filtered = true
```

When set to false, there is no seg fault.

More RSpec config:

```
RSpec.configure do |c|
  c.filter_run :focus => true
  c.filter_run_excluding :slow  => true
  c.run_all_when_everything_filtered = true
  c.include FactoryGirl::Syntax::Methods
end
```

simplecov (0.7.1)
guard (1.6.2)
guard-rspec (2.4.1)
Ruby 1.9.3p125 and 1.9.3p374

```
ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-darwin11.4.2]

* Loaded features
0 enumerator.so
1 /Users/george/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.4.2/enc/encdb.bundle
....
525 /Users/george/.rbenv/versions/1.9.3-p125/gemsets/ruby-bitcoin/gems/rspec-expectations-2.12.1/lib/rspec/expectations/differ.rb
526 /Users/george/.rbenv/versions/1.9.3-p125/gemsets/ruby-bitcoin/gems/rspec-expectations-2.12.1/lib/rspec/expectations.rb
```

**Comment by MaicolBen** [comment]
I have the same issue on ruby 2.4.2 and simplecov 0.13, 0.14 and 0.15

**Comment by PragTob** [comment]
Most likely it's a ruby bug. We don't usually segfault but the `Coverage` library we use underneath.

You can check that out by just doing:

```
require "coverage"
Coverage.start
# your test suite
p Coverage.result
```

http://ruby-doc.org/stdlib-2.3.0/libdoc/coverage/rdoc/Coverage.html

Without a sample application there's probably also not much that ruby core can do.
