### ISSUE TITLE
Simplecov with minitest Unit tests?

### ISSUE THREAD

**Issue by spatil** [colszowka/simplecov#235]
I am trying to use simplecov with minitests unit testing, I configured my test_helper.rb

```
require 'simplecov'
SimpleCov.start 'rails' do
  add_filter '/spec/'
  add_filter '/config/'
  add_filter '/lib/'
  add_filter '/vendor/'

  add_group 'Controllers', 'app/controllers'
  add_group 'Models', 'app/models'
  add_group 'Helpers', 'app/helpers'
  add_group 'Mailers', 'app/mailers'
  add_group 'Views', 'app/views'
end
```

But when i run the test cases, it shows me all the methods from models/controllers are not covered, for which there are test cases I have written. Only before filters, relations are seen green rest is all red. 

Do i need some configuration? is Simplecov is supported for Minitest unit testing ?

**Comment by gamov** [comment]
I have missing model coverage if I place the SimpleCov.start in my test_helper.rb (with Minitest). I use config.before_initialize now.

**Comment by reitzig** [comment]
FWIW, in my [simple gem](https://github.com/reitzig/texlogparser) it was relatively easy to get SimpleCov going.

 1. Add `s.add_development_dependency 'simplecov', '~> 0.16'` to `.gemspec`.
 2. `bundle install`
 3. Create `test/enable_coverage.rb` with this content:
	```ruby
	require 'simplecov'
	```
 4. Create `.simplecov` with this content:
	```ruby
	SimpleCov.start do
	end
	```
 5. In `Rakefile`, edit the test task to include `enable_coverage.rb` at first position:
	```ruby
	desc 'Run tests'
	Rake::TestTask.new do |t|
	  t.libs << 'my_gem'
	  t.test_files = FileList['test/enable_coverage.rb', 'test/test*.rb']
	  t.verbose = true
	end
	```
 6. Run `rake test` and happily find coverage reports in `coverage/`.

I guess further config would go into `.simplecov`, but that is the basics.
@bf4 Maybe add a very minimal example like this to the documentation? Scrolling through here, one might get the idea that the task at hand is all but impossible.

**Comment by PragTob** [comment]
There is already generous documentation in the [README](https://github.com/colszowka/simplecov#getting-started) I feel.

Your step number 5 is framework specific. Also what is mentioned in 3. needs to be required somewhere.

PRs to improve the documentation are very welcome though :)

**Comment by reitzig** [comment]
@PragTob My issues with the README are as such.
 - I use a gemspec, not a Gemfile.
 - I didn't have a test helper. Rake just ran all the minitests.	
 - It doesn't mention `.simplecov`; the "hope `SimpleCov.start` is required first" approach seems fickle, and the long discussion above (among others) seems to agree.
 - All the Rails references are irrelevant for Gem development, and potentially confusing.

> Your step number 5 is framework specific

What do you mean? Which framework? This whole issue is about Minitest, if that's what you mean.

> Also what is mentioned in 3. needs to be required somewhere.

Rake does that. Note that the file is mentioned in 5.

**Comment by bf4** [comment]
Locked just because this is old and long and isn't progressing any further. I admit it's not really resolved in the way I'd like.  Please open a new issue and reference this one if you'd like to restart the 'simplecov' and 'minitest' don't always play well together conversation (both run in `at_exit` blocks) , esp in Rails.
