### ISSUE TITLE
Browser Back button does not work in coverage reports

### ISSUE THREAD

**Issue by DavidEGrayson** [colszowka/simplecov#263]
The steps to reproduce this bug are:

1. Generate a coverage report with SimpleCov.
2. Open it in Google Chrome.
3. Click on one of the filenames in the report.
4. Click the back button.

At this point, I would expect the browser to go back to the previous screen I was on with the list of all the Ruby files.  Instead, what actually happens is that I remain on the same screen I was already one.  The URL seems to change back, but now the contents of the page.

I expect this to be easy to reproduce, but if it is not then my setup is:

jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_17-b02 [Windows 8-amd64]
simplecov gem 0.8.2
simplecov-html gem 0.8.0
Browsers tested:
  Google Chrome 33.0.1712.4 dev-m
  Internet Explorer 10.0.9200.16736

**Comment by whatasunnyday** [comment]
@bf4 hey, there are two open PRs on this. any chance you could take a look?

**Comment by colszowka** [comment]
simplecov-html 0.9.0 is released that includes the fixes. To use it, you will need to bump simplecov to `0.9.2`, which will ship in the next minutes once I got the changelog ready.
