### ISSUE TITLE
Safari rendering issues

### ISSUE THREAD

**Issue by scarver2** [colszowka/simplecov#270]
Having issues when viewing coverage results in Safari. This does not occur in Chrome or Firefox. This issue did not exist in older versions. Hope that helps with isolating what change.

![screen shot 2013-12-20 at 11 02 50 pm](https://f.cloud.github.com/assets/2336088/1795294/2df6e288-69fe-11e3-80f5-69ac542cc670.png)

**Comment by bf4** [comment]
Fixed by @ciddennis in https://github.com/colszowka/simplecov-html/pull/28
