### ISSUE TITLE
Always 100% test coverage with Ruby 2.0p353 and Rails 4.1beta

### ISSUE THREAD

**Issue by clupprich** [colszowka/simplecov#271]
I'm running the latest official patch version of Ruby 2.0 (p353) together with the the revision e4b9f6cb1ad397b of simplecov on Rails 4.1beta. I've added simplecov to the top of `spec_helper` but when I run `bin/rake spec`, it always reports 100% test coverage and doesn't see files with no test coverage (like certain controllers, etc.). Anyone experiencing the same problems?

I tried adapting the Spork logic to Spring, but without luck.

**Comment by whatasunnyday** [comment]
@swrobel I have this same problem.

**Comment by whatasunnyday** [comment]
@swrobe I've mounted Grape into my rails project and it is also displaying below correct coverage. See issue https://github.com/colszowka/simplecov/issues/363. In the next week or two, I'll start reading through the Spring source code to see if there's any reason that Spring is not correctly reporting coverage for models and rack mounted apps.

**Comment by bf4** [comment]
A preloader that forks may allow you to make the Coverage module
behave as if it could clear tracked code.  You should look at the
coverage.c code

**Comment by whatasunnyday** [comment]
@bf4 That's helpful to know. Thanks.

**Comment by bf4** [comment]
@chrishough If you wrap `SimpleCov.start` in a conditional, it will conditionally run. A common one people use is `if ENV["COVERAGE"] =~ /\Atrue\z/i`

**Comment by whatasunnyday** [comment]
You can also only execute simplecov outside of Spring like this:

```
unless defined?(Spring)
  SimpleCov.start 'rails' do
  # ...
  end
end
```

**Comment by bf4** [comment]
@whatasunnyday Here's a protip for that pattern

```ruby
SimpleCov.start 'rails' do
  # other config
end unless defined?(Spring)
```

**Comment by whatasunnyday** [comment]
@bf4 I've never seen that before :+1: . Thanks!

**Comment by chrishough** [comment]
@bf4 @whatasunnyday the only way I was able to get this to work correctly with spring was to create the file `config/spring.rb` with the following in it:
```ruby
if ENV['COVERAGE']
  require 'simplecov'
  SimpleCov.start do
    coverage_dir 'tmp/coverage'
    add_filter '/.bundle/'
    add_filter '/spec/'
    add_filter '/config/'
    add_group 'Models', 'app/models'
    add_group 'Controllers', 'app/controllers'
    add_group 'Services', 'app/services'
    add_group 'Utilities', 'app/utilities'
    add_group 'Helpers', 'app/helpers'
    add_group 'Libraries', 'lib'
    add_group 'Mailers', 'app/mailers'
    add_group "Long Files" do |src_file|
      src_file.lines.count > 300
    end
    add_group 'Ignored Code' do |src_file|
      File.readlines(src_file.filename).grep(/:nocov:/).any?
    end
  end
  SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter[
    SimpleCov::Formatter::HTMLFormatter
  ]
  SimpleCov.minimum_coverage 95
end
```

**Comment by bf4** [comment]
@chrishough tl;dr you used an ENV var :)  BTW, I recommend you move the simplecov config to a `.simpelcov` file in your app root.

**Comment by Pikomu** [comment]
@swrobel, adding `SimpleCov.command_name 'Rspec'` fixed the lower coverage issue, the file would be :

```ruby
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
  SimpleCov.start 'rails'
  SimpleCov.command_name 'Rspec'
end
```

Simplecov tries to discover the command but the spring command makes it impossible.
See these : http://stackoverflow.com/questions/17255475/making-spring-gem-work-with-simplecov.
And these : https://github.com/colszowka/simplecov#test-suite-names.
