### ISSUE TITLE
cucumber and rspec results not merged

### ISSUE THREAD

**Issue by opsb** [colszowka/simplecov#29]
When I run

```
rake spec cucumber
```

and check the coverage I'm finding that the cucumber results overwrite the rspec results. This is easy to confirm because I have a couple of classes with 100% rspec coverage but only 50% cucumber coverage. I've tried setting

```
SimpleCov.use_merging true
```

but no luck. My understanding is that they should be merged by default, is this correct? If not how's it done?

I'm using ruby 1.9.2p136, rails 3.0.5 and simplecov 0.4.1

**Comment by mathieujobin** [comment]
I am still getting this issue with `simplecov-0.11.2`

I tried setting the `command_name` to various values.

I am getting different behavior depending I run rspec or cucumber first
