### ISSUE TITLE
Minitest wrong coverage value

### ISSUE THREAD

**Issue by plribeiro3000** [colszowka/simplecov#314]
Im currently facing a problem i dont even know where to look. Im working on a project [fog/fog-xenserver](https://github.com/fog/fog-xenserver) and i can't get simplecov to work on it.

It is resulting in 74.08% coverage when i have only 1 test and the lib is big, really big. I have tested both latest version (0.8.2) and the one stated on README (0.7.1).

Even if i remove `require 'minitest/autorun'` and no tests run, my coverage still 74.08%.

Ruby version : `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]`
Minitest version : `4.7.5`

In case it was something i did not properly configured, i have create a branch [simplecov](https://github.com/fog/fog-xenserver/tree/simplecov) so you guys could check it.

I use `rake` to run my tests as you can see [here](https://github.com/fog/fog-xenserver/blob/simplecov/Rakefile#L13)

**Comment by geekq** [comment]
For me the key change was to require and start simplecov BEFORE minitest/autorun loads ./lib

```
# <BEGINNING OF test/test_helper.rb>
# Require and start simplecov BEFORE minitest/autorun loads ./lib to get correct
# test results. Otherwise lot of executed lines are not detected.
require 'simplecov'
SimpleCov.start do
  add_filter 'test'
end

require 'minitest/autorun'

class << Minitest::Test
  def test(name, &block)
...
```

I am maintaining a ruby _library_ (as opposite to a Rails application)
and using plain Minitest and a [minimal Rakefile](https://github.com/geekq/workflow/blob/develop/Rakefile)
