### ISSUE TITLE
Coverage [N] exceeds number of lines in X

### ISSUE THREAD

**Issue by byrnejb** [colszowka/simplecov#315]
OS=CentOS-6.5 x86_64
SimpleCov=0.8.2
Cucumber=1.3.15
Aruba=0.5.4
Bundler=1.6.3

ruby 2.1.2p95

After making several iterative changes to a source file I am now seeing this message:

Warning: coverage data provided by Coverage [202] exceeds number of lines in 

I run SimpleCov with Cucumber/Aruba through Bundler.   This error appeared literally out of nowhere since the only changes made to anything were to the source file and the features file and the error began to appear only after the first changes were made and several runs of bundle exec cucumber had executed without the error.

Noteworthy is the fact that the error only occurred after repeated runs of a single scenario.  If I run the entire feature suite there is no error. And if following a complete run I then return to that specific scenario and rerun it by itself then the error is also gone.

**Comment by gerep** [comment]
Just for reference, doing as @josephks said fixed the problem.

**Comment by knagode** [comment]
You might have been changing files while tests were running. I think that was my issue.

**Comment by BandanaPandey** [comment]
I am also seeing this sometimes, but not all the times
Warning: coverage data provided by Coverage exceeds number of lines .
I am using simplecov 0.12.0 and simplecov-html 0.10.0 in my project.
Any idea why this is happening when i run my test cases.

**Comment by murdoch** [comment]
@gerep you are right about that, and @knagode might be right about **why** it's happeneing. Changing files while tests are running looks to be the cause of this. Thanks.

**Comment by chrishough** [comment]
@josephks that fixed it for me as well.
