### ISSUE TITLE
Include code that is not being called in reports

### ISSUE THREAD

**Issue by jensljungblad** [colszowka/simplecov#347]
Is it possible to have SimpleCov include models and controllers that aren't being called by tests? I'm currently getting a too high coverage percentage because SimpleCov only shows includes files that have tests in the report.

Using Rails + MiniTest

**Comment by Manthan2211** [comment]
Try putting these lines in a new order: in spec_helper.rb

ENV["RAILS_ENV"] ||= 'test'
require 'simplecov'
SimpleCov.start('rails')
require File.expand_path("../../config/environment",__FILE__)
require 'rspec/rails'
does it help?

**Comment by PragTob** [comment]
The coverage library relies on the code being loaded to determine whether it's covered. You can also hardcore set files we should load and count as not loaded

**Comment by thisismydesign** [comment]
Based on @tommyalvarez's comment I did this as a generic solution:
`rails_helper.rb`
```
require 'rspec/rails'

# ...

Dir[Rails.root.join("app/**/*.rb")].each {|f| require f}
Dir[Rails.root.join("lib/**/*.rb")].each {|f| require f}
```
