### ISSUE TITLE
index.html file showing full test coverage of spec files, missing some model files

### ISSUE THREAD

**Issue by zackshapiro** [colszowka/simplecov#349]
Top of `spec_helper.rb`:

``` ruby
require 'simplecov'
SimpleCov.start
require 'simplecov-json'
SimpleCov.formatter = SimpleCov::Formatter::JSONFormatter

---

ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
# require 'requests/fakeweb_helper'

Dir[Rails.root.join("spec/support/**/*.rb")].sort.each {|f| require f}
...
```

![](http://cl.ly/image/3l1z1Z2w2S3I/Screen%20Shot%202014-11-11%20at%209.14.41%20AM.png)

This is strange... In the screenshot above which is a sample of coverage/index.html, it's showing me 100% test coverage on my spec files yet it's missing a number of models. 

It shows I have 100% coverage on `order_spec.rb` yet no mention of `order.rb` in there. I'm not testing my test files, that wouldn't make much sense, so I'm very confused about this output and why it's happening.

It shows certain models but not others and has 100% test coverage on all of my `_spec.rb` files

Any suggestions on how to remedy?

**Comment by sergeyvdovareize** [comment]
Got this issue. I don't use the `simplecov-json` gem.
This is all I have in `spec/rails_helper.rb` regarding `simplecov`:
```
# coverage
require 'simplecov'
SimpleCov.start
```
