### ISSUE TITLE
Problems running scov for a Rails Engine Source

### ISSUE THREAD

**Issue by krobi64** [colszowka/simplecov#359]
I have an engine repo much like mentioned in #221, and like that issue, I am not getting any coverage from my specs:

![permission_c0_coverage_information_-_simplecov_-_rcov_style](https://cloud.githubusercontent.com/assets/159039/5732576/0e3a360c-9b49-11e4-95a7-295fbe4a5511.png)

I attempted to use the solution suggested in the https://gist.github.com/bsodmike/5866873:
```
# my_engine/spec/spec_helper.rb:

SimpleCov.start 'rails' do
    adapters.delete(:root_filter)
    filters.clear # This will remove the :root_filter that comes via simplecov's defaults
    add_filter do |src|
      !(src.filename =~ /^#{SimpleCov.root}/) unless src.filename =~ /my_engine/
    end
end
```

However, instead of catching the code in both lib and the app directories of the engine, it instead only captures a few `spec` files:

![permission_c0_coverage_information_-_simplecov_-_rcov_style](https://cloud.githubusercontent.com/assets/159039/5732536/7a09a026-9b48-11e4-8eaf-43873c2d91b1.png)

Engines are tested in context of a `spec/dummy` app.

```
require File.expand_path('../dummy/config/environment.rb',  __FILE__)
```

**Comment by bf4** [comment]
Sanity check, did you actually use `/my_engine/`?  Also, normally you would test coverage of spec files.  That might be useful in seeing if you have unexecuted tests, but that's about it.

For sanity check, please also try what I suggested in https://github.com/colszowka/simplecov/issues/345#issuecomment-68449872

 After your SimpleCov.start try adding

```ruby
SimpleCov.at_exit do
  puts Coverage.result.keys
end
```

Which will output every single file the Ruby stlib Coverage module recorded as being loaded.  Hopefully that will help you pinpoint your problem.

**Comment by bf4** [comment]
Also, forgot to ask, 

1. Please share the info from https://github.com/colszowka/simplecov/blob/master/CONTRIBUTING.md
2. Did you look at https://github.com/colszowka/simplecov/issues/340 ?

**Comment by bf4** [comment]
Closing due to lack of response. Feel free to reopen and add more info.
