### ISSUE TITLE
Incoherent missed lines

### ISSUE THREAD

**Issue by pierallard** [colszowka/simplecov#361]
Hi
I'm using ruby 2.1.2p95, with gems simplecov (0.9.1) and simplecov-html (0.8.0), rails (4.1.8) and rspec (2.99)

This is an example of code generating "missed lines", which are covered.

    1  class Foo < ActiveRecord::Base
    2    CONST = {
    3     'CONST1' => 0,
    4     'CONST2' => 101,
    5   }
    6   def error(str)
    7     if str == 'CONST1'
    8       return CONST['CONST1']
    9     else
    10      return CONST['CONST2']
    11     end
    12   end
    13 end

My example simply call `error('CONST1')` and `error('CONST2')`. The lines 3, 4, 5 and 9 are denoted as "missed", or they are covered.

**Comment by bf4** [comment]
Can you provide the test code and command and any configuration you're using the generate run simplecov?

**Comment by pierallard** [comment]
@bf4 It's a simple call with `rspec` command. The configuration inside my `spec_helper.rb` is :

    require 'simplecov'
    SimpleCov.start 'rails' do
      coverage_dir('public/coverage')
    end

    # Adds non parsed files to simplecov
    all_files = Dir['**/*.rb']
    base_result = {}
    all_files.each do |file|
      absolute = File::expand_path(file)
      lines = File.readlines(absolute, :encoding => 'UTF-8')
      base_result[absolute] = lines.map do |l|
        l.strip!
        l.empty? || l =~ /^end$/ || l[0] == '#' ? nil : 0
      end
    end
    SimpleCov.at_exit do
      merged = SimpleCov::Result.new(Coverage.result).original_result.merge_resultset(base_result)
      result = SimpleCov::Result.new(merged)
      result.format!
    end

The last part is a copy/paste from https://github.com/colszowka/simplecov/issues/16 to cover all files.

The `spec/models/foo_spec.rb` contains

    require 'spec_helper'
    describe Foo do
      it "should return 0" do
        Foo.new.error('CONST1')
      end
      it "should return 101" do
        Foo.new.error('CONST2')
      end
    end


This is the result : http://www.pasteall.org/pic/show.php?id=82840

**Comment by bf4** [comment]
I get 100%

```ruby
# coverage_example.rb
class Foo
  CONST = {
   'CONST1' => 0,
   'CONST2' => 101,
 }
 def error(str)
   if str == 'CONST1'
     return CONST['CONST1']
   else
     return CONST['CONST2']
    end
  end
end

Foo.new.error('CONST1')
Foo.new.error('CONST2')
```

```bash
ruby -rsimplecov -e "SimpleCov.at_exit { SimpleCov.result.format! }; SimpleCov.start; require './coverage_example'; puts  puts SimpleCov.result.original_result"
;puts Coverage.result"
```

SimpleCov reports `8 relevant lines. 8 lines covered and 0 lines missed.`  lines 3 and 4 are filtered out (ignored).

The original result from `Coverage.result` is

`coverage_example.rb"=>[2, 2, nil, nil, nil, 2, 4, 2, nil, 2, nil, nil, nil, nil, 2, 2]`

so, it looks consistent to me.

**Comment by pierallard** [comment]
@bf4 Thanks for looking at my issue. I searched the difference between my failing code and yours, and found the issue.
The lines in my `spec/spec_helper` file found in https://github.com/colszowka/simplecov/issues/16 cause the issue (just after `# Adds non parsed files to simplecov` comment in my previous comment).

It's not a `simplecov` issue, so I close it.

Thanks for your time.
