### ISSUE TITLE
Fix order dependencies in unit tests

### ISSUE THREAD

**Issue by sferik** [colszowka/simplecov#362]
After [switching from Test::Unit to Minitest](https://github.com/colszowka/simplecov/commit/667c3991a16c541609fbeff5a46b92b9505881a9), I started noticing some intermittent build failures. These will typically self-correct by restarting the build. They seem to be caused by an order dependency.

Minitest will force the tests to run in alphabetical order if you add the flag `i_suck_and_my_tests_are_order_dependent!` but I think it would be better to just fix the order dependency. :blush:

There’s a project called [minitest-bisect](https://github.com/seattlerb/minitest-bisect) that should make it easier to track down random failures.

**Comment by bf4** [comment]
Sounds good :)

**Comment by hugopeixoto** [comment]
I've tried to track this down. It seems that it is related to global configuration settings.

Some tests do things like `SimpleCov.add_filter` without cleaning up.
I'm adding the following pattern wherever it seems appropriate:

    setup do
      @prev_filters, SimpleCov.filters = SimpleCov.filters, []
    end

    teardown do
      SimpleCov.filters = @prev_filters
    end

Not sure if that's the way to go, but it solves the problem.

**Comment by colszowka** [comment]
Merged and green, thanks a lot for tackling this @hugopeixoto
