### ISSUE TITLE
Default code path doesn't appear to handle fork correctly?

### ISSUE THREAD

**Issue by ioquatix** [colszowka/simplecov#371]
I had to do this.

https://gist.github.com/clicube/5017378

 This removed what appeared to be superfluous output:

    Coverage report generated for RSpec to /home/samuel/Documents/Programming/rubydns/coverage. 0 / 599 LOC (0.0%) covered.

multiple times per run.

Perhaps this should be the default behaviour?

**Comment by bf4** [comment]
```ruby
pid = Process.pid
SimpleCov.at_exit do
  SimpleCov.result.format! if Process.pid == pid
end
```

 I like that.

**Comment by bf4** [comment]
are you using a merge timeout?

**Comment by ioquatix** [comment]
What do you mean?

**Comment by bf4** [comment]
Would you paste your simplecov config? (How you require, configure, start it)

**Comment by coderanger** [comment]
My solution for this was to add `SimpleCov.at_exit { SimpleCov.instance_variable_set(:@result, nil) }` to the post-fork code. Might be nice if the main [`at_exit` implementation](https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L42) checked pids and only ran formatters or the minimum coverage check if the current pid was the one you ran `start` in.

**Comment by bf4** [comment]
I'm up for a PR

**Comment by coderanger** [comment]
Mostly trying to think if that would break anything. The Coverage module already doesn't actually work across a fork, so I think it should be safe in all cases?

**Comment by colszowka** [comment]
Yes, I think that would be a good change - although maybe we can wrap the top level pid under SimpleCov.pid so we don't get weird interferences
