### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by colszowka** [colszowka/simplecov#372]
We are getting a bunch of seemingly random failures, on different ruby versions when building on travis. 

Locally everything works fine for me and the failing ruby versions vary across builds.

https://travis-ci.org/colszowka/simplecov/builds

**Comment by bf4** [comment]
Duplicate of https://github.com/colszowka/simplecov/issues/362

**Comment by colszowka** [comment]
Ah, thanks Ben :)
