### ISSUE TITLE
Enforcing minimum threshold coverage

### ISSUE THREAD

**Issue by elliotweiser** [colszowka/simplecov#373]
There doesn't seem to currently be an out-of-the box way to enforce code coverage, so I added the following to my Rakefile.

```
desc "Run unit tests and ensure 100% code coverage"
task :ci do
  Rake::Task['spec'].invoke
  enforce_coverage(100.0)
end

def enforce_coverage(threshold)
  result = File.read("coverage/.last_run.json")
  obj = JSON.parse(result)
  covered = obj["result"]["covered_percent"]
  msg = "Coverage rate #{covered}% is below the threshold of #{threshold}%"
  raise msg if covered < threshold
end
```

Hopefully this will help folks ensure a minimum threshold for the time being until a more permanent/out-of-the-box solution is available.  I'll certainly look forward to it!

**Comment by xaviershay** [comment]
Cane also supports this: https://github.com/square/cane#integrating-with-simplecov

**Comment by colszowka** [comment]
@elliotweiser Please check out https://github.com/colszowka/simplecov#minimum-coverage and https://github.com/colszowka/simplecov#maximum-coverage-drop

**Comment by xaviershay** [comment]
oh neat, I didn't know those had been added!

**Comment by elliotweiser** [comment]
thanks for the rapid response! I'll check it out!
