### ISSUE TITLE
Feature proposal: Inline assets in HTML output

### ISSUE THREAD

**Issue by eins78** [colszowka/simplecov#378]
(I already made an issue with [`simplecov-html`, see there](https://github.com/colszowka/simplecov-html/issues/33).)

**Comment by rthbound** [comment]
+1

**Comment by rthbound** [comment]
Looks like this has been done, as a formatter: [grosser/simplecov-single_file_reporter](https://github.com/grosser/simplecov-single_file_reporter)

**Comment by PragTob** [comment]
I think this is purely simplecov-html related so an issue over there should be enough :)
