### ISSUE TITLE
index.html not being written

### ISSUE THREAD

**Issue by lolomet** [colszowka/simplecov#379]
The first few lines of `spec_helper.rb` looks like this:

    # encoding: utf-8
    #
    require 'simplecov'
    SimpleCov.start 'rails'
    ...

I deleted my `coverage/index.html` because it wasn't updating, now it just isn't being written to. This is in Rails 4. Any other config necessary?

**Comment by lolomet** [comment]
Seems you can't send the report to Code Climate and write the report locally:

    # commenting out the below line lets the report be written
    CodeClimate::TestReporter.start

Is that the desired behaviour?

**Comment by sferik** [comment]
You can specify multiple formatters by following the [instructions in the `README`](https://github.com/colszowka/simplecov#using-multiple-formatters).
