### ISSUE TITLE
Coverage on ERB

### ISSUE THREAD

**Issue by ryanb** [colszowka/simplecov#38]
Great work on this gem. Is it possible to check code coverage in ERB templates? In a Rails app there might be an "if" condition in a view which is not covered. It would be great if it were somehow possible to check this.

**Comment by eloyesp** [comment]
I know it is an old issue, but it might be possible to add a hook on ERB when it read a template file or it compiles it and add those calls to the result set. Does it makes sense? @colszowka ?

**Comment by dmitry** [comment]
What about HAML / Slim and friends?

**Comment by eloyesp** [comment]
I were checking, and it seems that using trasepoint instead of coverage we
could track coverage of template files, I will do some testing on that,
what do you think about that approach?

**Comment by ioquatix** [comment]
Any update on using tracepoints?

**Comment by eloyesp** [comment]
I were trying just a bit, but found not way differentiate code that is not
being executed from lines that are being ignored.

For example, on the following code:

```
def foo bar
  if bar >  2
    bar
  else
    2
  end
end

foo 3
```

I shuld have `[1,1,1,nil,0,nil,nil,nil,1]`. I have no way to distinguish
`nil` from `0` using tracepoint.

**Comment by ioquatix** [comment]
Yeah I tried using trace points and came to the same conclusion. :(

**Comment by bf4** [comment]
I think you'd have to patch ERB in some way to cause the template text to
be considered a file after it was parsed but before it was eval'd.

I just tried making a template.rb

<% if true %>
  "true"
  <%= 'true' %>
<% else %>
  "false"
<% end %>


And then from the terminal

ruby -rerb -rcoverage -e 'Coverage.start; puts
ERB.new(File.read("./template.rb")).result; p Coverage.result'

  "true"
  true

{}

Which didn't pickup up evaluating any Ruby files, which you'd expect since
the input to `ERB` is text that happened to be read in from a  file, but
the file wasn't evaluated

**Comment by ioquatix** [comment]
I had a look in the MRI source code and for some reason it doesn't compute coverage for `eval` code which is being parsed.

https://github.com/ruby/ruby/blob/582951e2c8995d6bab5ddaf98cd3816310f8d506/parse.y#L4785

It might just be a matter if being slightly more allowing at that line, i.e. if calling eval with the optional file name argument set to something.

**Comment by joevandyk** [comment]
Might this be doable now?

https://bugs.ruby-lang.org/issues/14888
https://bugs.ruby-lang.org/issues/15287
https://github.com/ioquatix/covered/

**Comment by ioquatix** [comment]
It works in covered but I don’t use standard coverage library because this bug still applies.

**Comment by hattwj** [comment]
According to this feature over at ruby-lang we should have support for this (https://bugs.ruby-lang.org/issues/15287) assuming you're ruby 2.6 or above.

**Comment by mame** [comment]
I have created a PR that will solve this issue: https://github.com/simplecov-ruby/simplecov/pull/1037
