### ISSUE TITLE
Simplecov doesnt generating report with apartment gem

### ISSUE THREAD

**Issue by fabiomello** [colszowka/simplecov#380]
Simplecov doesnt generating report with apartment gem when i put the model at config.excluded_models .. I think the gem do a constantize at the model...
How can i include to generate the report?

**Comment by bf4** [comment]
In order to help, we need to be able to reproduce your issue. Please read https://github.com/colszowka/simplecov/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by sferik** [comment]
Please reopen this issue with more details if you’re still unable to get it working.
