### ISSUE TITLE
Single line conditionals: line coverage

### ISSUE THREAD

**Issue by Kriechi** [colszowka/simplecov#386]
Is it possible to correctly determine the coverage for a single line conditional, e.g.:
```ruby
foo if bar.present?
```

As far as I can see this line would be marked as green as soon as the conditional is evaluated, even if it evaluates to `false` and therefore does not execute the `foo` statement.
This means that the coverage information about the single `foo` call is lost.
Ideally the html formatter could split the line somehow to indicate that *only* the conditional is covered, but not the actual statement.

Is this possible? 
Thanks.

**Comment by colszowka** [comment]
Unfotunately, this is not possible because the [underlying ruby Coverage library](http://ruby-doc.org/stdlib-2.2.2/libdoc/coverage/rdoc/Coverage.html) used by simplecov does not support reporting this kind of data (branch/condition coverage). Sorry to dissapoint!

**Comment by joevandyk** [comment]
Is this still the case with Ruby >= 2.5?

https://bugs.ruby-lang.org/issues/13901

**Comment by bf4** [comment]
@joevandyk yes, there's an issue for that.

**Comment by PragTob** [comment]
@joevandyk there's an open PR even #694
