### ISSUE TITLE
Getting 100% even though the actual code is not being hit.

### ISSUE THREAD

**Issue by magicalbanana** [colszowka/simplecov#388]
Not really sure how to properly set this up on a gem project but when I run SimpleCov it's telling me I have 100% coverage even though all the files in my lib folder are being ignored and the ones that aren't are on the spec folder.

Any ideas?

**Comment by gokulnath** [comment]
I just encountered this issue

```
rails version: 4.2.0
simplecov version: 0.9.2
Testing framework: minitest (Rails default)
```
I have code in l ```lib``` and its sub-directories, and respective tests in ```test/lib``` and its sub-directories.

My simplecov configuration at the top of ```test_helper.rb```
```
require 'simplecov'
SimpleCov.start('rails')
```
On running ```rake test``` the coverage is incomplete. 
For Libraries group, I am not getting any coverage results (It just shows as 100% with no data available in the table)

**Comment by gokulnath** [comment]
Trying with .simplecov file configuration yields same results as above.

**Comment by magicalbanana** [comment]
Yeah, but I am not using rails. This is just for my gem:

https://github.com/magicalbanana/data_maker

If anyone can take a look at how to properly set this up it would be great.

**Comment by magicalbanana** [comment]
Got this to work, basically my entire lib was being loaded before on simplecov via the gemspec file. So thanks for anyone who looked at this.

**Comment by gokulnath** [comment]
My issue was the same, I was loading some code in initializer.

**Comment by onebree** [comment]
@gokulnath How do you include code that is ran from an initializer, or is preloaded?

**Comment by bf4** [comment]
Hi @onebree If you make and issue with info (per CONTRIBUTING) on how to reproduce your issue I can help :)
