### ISSUE TITLE
Multi-line statements not being counted accurately

### ISSUE THREAD

**Issue by adampope** [colszowka/simplecov#394]
I'm using 0.10 on a Rails 4.2 project with ruby 2.0.0-p643.  I'm seeing lots of occurrences of statements that span multiple lines not being counted as covered, or only 1 or the multiple lines being counted.  For example, I have a concern which is completely tested but reports as 77%.

![screen shot 2015-06-11 at 10 12 41](https://cloud.githubusercontent.com/assets/1418872/8103760/f32daf84-1022-11e5-8bf1-4845dca0b1c3.png)

If I simply reformat the code onto single lines I get 100% coverage.

![screen shot 2015-06-11 at 10 19 09](https://cloud.githubusercontent.com/assets/1418872/8103799/5dbfd6e2-1023-11e5-9817-8e814acf1bad.png)

**Comment by bf4** [comment]
so that we can reproduce this, can you provide a small snippet of the code and tests that create this bug? It would be of great help.

**Comment by adampope** [comment]
@bf4 I've created a repo with the code to reproduce this in (https://github.com/adampope/simplecov-multi-line-repro).  In doing so I've found the cause.  We are using the following snippet in `test_helper.rb` (from #16)  to make sure that all files are loaded:

```
  all_files = Dir['**/*.rb']
  base_result = {}
  all_files.each do |file|
    absolute = File::expand_path(file)
    lines = File.readlines(absolute, :encoding => 'UTF-8')
    base_result[absolute] = lines.map do |l|
      l.strip!
      l.empty? || l =~ /^else$/ || l =~ /^end$/ || l[0] == '#' ? nil : 0
    end
  end
  
  SimpleCov.at_exit do
    merged = SimpleCov::Result.new(Coverage.result).original_result.merge_resultset(base_result)
    result = SimpleCov::Result.new(merged)
    result.format!
  end
```

With that code multi-line statements do not get counted correctly.

With

![screen shot 2015-06-18 at 09 59 44](https://cloud.githubusercontent.com/assets/1418872/8227621/d3507920-15a0-11e5-8a41-ec9c0c905a4a.png)

Without

![screen shot 2015-06-18 at 09 59 18](https://cloud.githubusercontent.com/assets/1418872/8227623/d7cd8b28-15a0-11e5-97ec-c0b121bfce0c.png)

Any ideas on ways to modify this to correctly handle the multi-line statements?

**Comment by adampope** [comment]
We found a better way of solving the problem of tracking all files, I've added a comment to #16 so I'll close this ticket.

**Comment by mudit-1996** [comment]
@adampope  Hey. What is the final fix for multi line statements. Please help.
