### ISSUE TITLE
Corrupt JSON output with rspec --format json

### ISSUE THREAD

**Issue by shaicoleman** [colszowka/simplecov#395]
SimpleCov should either have correct JSON output, or shouldn't output anything at all when the JSON formatter is used.

This breaks the rspec-bisect gem

**Comment by colszowka** [comment]
@shaicoleman Not sure I am getting this correctly, but I suspect you are using the (third party) [simplecov-json](https://github.com/vicentllongo/simplecov-json) formatter. Having a look [at the code](https://github.com/vicentllongo/simplecov-json/blob/master/lib/simplecov-json.rb#L35) there I think it's been built upon simplecov's official HTML formatter, which has a similar line, but I can see that in this case the output is becoming invalid.

I would suggest you get in touch with the author of the simplecov-json gem and suggest making the plain-text message optional through some kind of configuration method. Maybe you could also send in a PR directly.

Other than that as a workaround I would suggest you just disable simplecov when using rspec-bisect, for example by wrapping the `SimpleCov.start` block in an `unless ENV['BISECT']`

**Comment by shaicoleman** [comment]
This happens without any third party gems (besides RSpec, and simplecov).
Sample app below:
https://github.com/shaicoleman/simplecov-json-issue-sample

To reproduce run:
    $ rspec --format json
    {"version":"3.3.1","examples":[{"description":"add some examples to (or delete) /tmp/simplecov-json-issue-sample/spec/models/widget_spec.rb","full_description":"Widget add some examples to (or delete) /tmp/simplecov-json-issue-sample/spec/models/widget_spec.rb","status":"pending","file_path":"./spec/models/widget_spec.rb","line_number":4,"run_time":2.3747e-05,"pending_message":"Not yet implemented"}],"summary":{"duration":0.000256213,"example_count":1,"failure_count":0,"pending_count":1},"summary_line":"1 example, 0 failures, 1 pending"}Coverage report generated for RSpec to /tmp/test2/coverage. 44 / 44 LOC (100.0%) covered.

I already have a workaround in place for rspec-bisect, but it's still a bug.
