### ISSUE TITLE
Guard clauses falsely marked as covered

### ISSUE THREAD

**Issue by joshpfosi** [colszowka/simplecov#398]
Hi, I am experiencing what I believe to be a bug where lines are falsely marked as covered. Consider the example snippet:

```ruby
return error 'Malformed power-manager response.' if response.nil? || response['rows'].nil?
```

This is erroneously marked as covered in Simplecov's report as (I imagine), the conditional, and therefore the line number, is hit, but the expression is not evaluated. To confirm I saw 'correct' behavior when I restructured it to look like:

```ruby
if response.nil? || response['rows'].nil?
  return error 'Malformed power-manager response.'
end
```

To be clear, my test suite is NOT hitting that expression! Is this a known issue? Is there no easy workaround? Guard clauses of this form I feel are quite common so it's a shame they aren't properly covered :(

**Comment by josephks** [comment]
This is expected behavior.

**Comment by bf4** [comment]
Hi @joshpfosi , Thanks for the report.  When making issues in the future, please review our guide so we can be most helpful https://github.com/colszowka/simplecov/blob/master/CONTRIBUTING.md#reporting-issues

In this case @josephks is correct. SimpleCov relies on Ruby's Coverage module, which, at this time, only provides [C0](http://grosser.it/2008/04/04/whats-my-coverage-c0-c1-c2-c3-path-coverage/) [coverage](https://www.bignerdranch.com/blog/code-coverage-and-ruby-1-9/), which means it only checks whether a lines was *executed* or not. It won't tell you which paths of a line were executed.
