### ISSUE TITLE
Exclude entire files from test coverage report

### ISSUE THREAD

**Issue by sashaperigo** [colszowka/simplecov#402]
My team uses SimpleCov with Code Climate and Travis CI. We have several entire files in our configurations folder that we'd like to skip from coverage reports. It'd be great if we could somehow configure this upfront in a .yml file, rather than using # :nocov: tags to surround each file!

**Comment by xaviershay** [comment]
I think you should be able to do this already using a filter.

```
SimpleCov.start do
  add_filter "path/to/your/file.rb"
end
```

Closing because I'm pretty sure that'll do it, but if not please do re-open!

**Comment by sashaperigo** [comment]
@xaviershay you're right, that works! Thanks for your help!
