### ISSUE TITLE
New files wont get added to the report

### ISSUE THREAD

**Issue by cvandermeer** [colszowka/simplecov#403]
With my rails application i added a controller and a model.
But after running rake again and checking the simplecov report those files are not included in the report.
I am using `ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]`
I am using `minitest` on `rails 4.2`
Here is my test helper

```ruby
require 'simplecov'
SimpleCov.start 'rails'
require "minitest/reporters"
Minitest::Reporters.use!

ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  fixtures :all
end
```

ALSO

I have this message when running rake:

```plain
SimpleCov failed to recognize the test framework and/or suite used. 
Please specify manually using SimpleCov.command_name 'Unit Tests'.
```

**Comment by bf4** [comment]
- What version of SimpleCov are you on?
- What happens if you clear your `coverage` directory and run the tests again?
- What happens if you follow the advice in the message `SimpleCov.command_name 'Unit Tests'`?
- Do you have a require SimpleCov at the top of your Rakefile? SimpleCov needs to start before any code is loaded.

**Comment by cvandermeer** [comment]
Simplecov 0.7.1
If i remove the entire folder then i get the same result.
i have added SimpleCov.command_name 'Unit Tests' but still the same problem.
I have require simplecov at the top of  rakefile

But still the same problem.

**Comment by bf4** [comment]
I don't really know what to do from here.

- Can you make a sample repo that duplicates this failure? AND/OR
- Can you update to the 0.9 series?

**Comment by cvandermeer** [comment]
It is fixed know, i dont know if its because of removing the files inside coverage or because of something else.
