### ISSUE TITLE
Scope is considerated "not ok" by simplecov-rcov when it is divided in two lines 

### ISSUE THREAD

**Issue by robsonagapito** [colszowka/simplecov#411]
I have a code and I declare a scope, as line bellow:

scope :with_snapshot_histories,
           -> { where(SCOPE_STR) }

In this case simplecov-rcov return "NOT OK", but if I declare scope in one line the result becomes OK.

scope :with_snapshot_histories, -> { where(SCOPE_STR) }

This situation also happens when I have a block (bellow):

NOT OK:
scope :service_codes_by_login, (lambda do |login| 
                                                                     joins(:account)
                                                                     .where(accounts: {login: "#{login}/#{login}"})
                                                                     .select(:service_code) 
                                                      end)

OK:
scope :service_codes_by_login, (lambda do |login| joins(:account).where(accounts: {login: "#{login}/#{login}"}).select(:service_code) end)

Is this a problem? Or is this a expected comportment?

This situation affect the result of our coverage.

Code in 2 lines:
![simplecov-rcov_before_perc](https://cloud.githubusercontent.com/assets/991015/9338996/21671180-45be-11e5-9687-76e411f3f0c6.png)

Result (2 lines) - 85.58% / 73.03 :
![simplecov-rcov_before_code](https://cloud.githubusercontent.com/assets/991015/9338997/21670d8e-45be-11e5-9cae-7270ac981e25.png)

Code in 1 line:
![simplecov-rcov_after_code](https://cloud.githubusercontent.com/assets/991015/9339008/2be83e5e-45be-11e5-984c-6071ff247a4c.png)

Result (1 line) - 85.64% / 73.15% 
![simplecov-rcov_after_perc](https://cloud.githubusercontent.com/assets/991015/9339009/2be8c874-45be-11e5-97fb-72ddd4d6bef8.png)

Coverage's difference:
Result (2 lines) - 85.58% / 73.03%
Result (1 line)   - 85.64% / 73.15% 

PS: Images are gem SIMPLECOV-RCOV, but I tested with SIMPLECOV and happens the same.

**Comment by bf4** [comment]
Offhand, it sounds like a bug in the Coverage module that we may be able to work around with some clever trick.

**Comment by xaviershay** [comment]
Is the lambda/block actually being executed? If not, that would explain this behaviour to me.

**Comment by robsonagapito** [comment]
Lambda/block really not being executed... but we can see a false positive in this case, because when it is in one line returns ok, but not being executed the complete line. I believe that it considers the line beginnings ok and ignores the "block", indifferent if executed or not.

**Comment by bf4** [comment]
> 
Actually with C0 coverage it is correct as it only checks that the line was executed or evaulated at load :) and Coverage only does C0. :)
>

**Comment by robsonagapito** [comment]
But, if I have a class with 20 scopes, all scopes with only one line to load, and no test, I have 100% of coverage, correct?  This coverage would be a false positive?

**Comment by xaviershay** [comment]
yep, but there's nothing we can do about it. The underlying coverage library only provides _line_ coverage, not _branch_ coverage.

**Comment by bf4** [comment]
@robinroestenburg It's a common misunderstanding of SimpleCov. It's advertised as a test coverage tool, but practically it just uses the Ruby Coverage module to track which lines of a file are run and how many times.  Since a method is only tracked when it's run, you can tell it's been called, so, during testing, it correlates with being tested.

**Comment by robinroestenburg** [comment]
@bf4 think you meant @robsonagapito? :wink:
