### ISSUE TITLE
Picking up coverage during fork

### ISSUE THREAD

**Issue by ioquatix** [colszowka/simplecov#414]
The following coverage: https://coveralls.io/builds/3383271 is not picking up coverage of code during fork.

https://coveralls.io/builds/3383271/source?filename=lib%2Fprocess%2Fdaemon%2Fcontroller.rb

Not sure exactly how to debug this or help figure out what is going on except to ask here.

**Comment by bf4** [comment]
Hi @ioquatix ! Did you set `SimpleCov.pid = $$` in your `.simplecov`? or elsewhere? Have you tried setting a command name?  Are you running parallel tests, or there's just a fork somewhere? 

SimpleCov version etc, please :) https://github.com/colszowka/simplecov/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by ioquatix** [comment]
The .simplecov file: https://github.com/ioquatix/process-daemon/blob/master/.simplecov

I don't believe I'm doing anything like `SimpleCov.pid = $$` anywhere.

It uses whatever is the latest version of SimpleCov, e.g. https://github.com/ioquatix/process-daemon/blob/master/Gemfile - this is running on Travis.

Yes, it's double forking to start a daemon process.

**Comment by bf4** [comment]
Nah, you're doing it right with the pid.

**Comment by bf4** [comment]
other possibility is changing the command name in the fork, just as you would with parallel tests...

**Comment by ioquatix** [comment]
Okay so like `Process.setproctitle` ?

**Comment by bf4** [comment]
oh, I meant `fork { SimpleCov.command_name = "i'm a fork" }`

**Comment by ioquatix** [comment]
I tried command_name, ti didn't help. I also tried changing my fork code like so

```
			def spawn
				@daemon.prefork
				@daemon.mark_log

				fork do
					Process.setsid
					exit if fork

					SimpleCov.start

					# ... snip ...
```

It didn't help. It's like after it enters the fork block coverage is not recorded. What can I do to check?

**Comment by bf4** [comment]
Puts Coverage.result, pid

Or 

B mobile phone

**Comment by PragTob** [comment]
I'm not sure what to do here and if forking can be made to work with simplecov/coverage. At the elast we should probably document it in the README.
