### ISSUE TITLE
Start Simplecov when specs passed

### ISSUE THREAD

**Issue by JanStevens** [colszowka/simplecov#415]
Hello,

Don't really see this feature atm but I would like to configure Simplecov so that it only starts generating the report when all specs where successful. The main reason is that we have a large test suite and there is no point in generating the coverage when the specs failed.

We only care for coverage report when all the specs passed,

I tried looking into it but don't see how I get the relevant info from rspec (or any other testing framework). If anyone can point me in the right direction I can try to create a PR.

Regards

**Comment by xaviershay** [comment]
You could hook into https://github.com/colszowka/simplecov#customizing-exit-behaviour and only call `format!` if tests are passing. I'm not sure exactly how to extract that info from RSpec, but start by looking at the `Runner` class https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/runner.rb

Good luck!

**Comment by bf4** [comment]
I think there's two ways to do this:

Basically, you can track coverage but only report it when the tests fail.  There's no way to both track and not track coverage at the same time.  But you can conditionally report it... 

- before you load your app to `require 'Coverage'; Coverage.start`, then if the specs fail `SimpleCov.start 'some profile'; SimpleCov.format.result!` See https://github.com/rails-api/active_model_serializers/pull/1069/files#diff-38d89add37c3690ad9d851aee9acd632R46 for what I'm doing there (for a different reason).  
- set `SimpleCov.formatters = []` and in `SimpleCov.at_exit { $! && set_formatter_or_generate_custom_results }`

**Comment by JanStevens** [comment]
Thanks, using your code I managed to do the same but hit a wall because we use `parallel_tests`,
Now only the process that failed does not generate the reports

**Comment by bf4** [comment]
would you mind including what code worked and what was wrong with the output (specifics and details plz)

**Comment by yurygnutov** [comment]
@JanStevens hey, did you manage to "fix" your issue? Seems like I face the same one.
