### ISSUE TITLE
Coverage report for rspec tests covers method defintion when there's actually no tests for that method

### ISSUE THREAD

**Issue by Munchery-JunyuWang** [colszowka/simplecov#417]
Hi! we are having an issue with simplecov&rspec tests, so the coverage report is generated as expected, but the weird thing is in some of the files (actually a lot), the coverage report shows some of the method definition are covered whereas there's actually no tests for that function. for example
```
def abc(x)
 puts 'hello world'
end
```
when there's no tests written for funciton abc, the line `def abc` is green (covered) in the coverage report while `puts 'hello world` and `end` are red (not covered).

PS: some information about our setup
```
gem simplecov
gem ci_reporter_rspec
gem rspec_rails 3.1.0
rails 3.2.18
```

Is there any way to avoid this? Thanks!

**Comment by bf4** [comment]
Nope. Please see C0 coverage in https://github.com/colszowka/simplecov/issues/340#issuecomment-135314803
