### ISSUE TITLE
No Data generated by report

### ISSUE THREAD

**Issue by Tarun17** [colszowka/simplecov#418]
I get this issue as well. I am using SimpleCov with RubyMine IDE.  

![image](https://cloud.githubusercontent.com/assets/4503298/10130310/fec3e10a-658c-11e5-8510-2588503f2153.png)

and this what the coverage report looks like:

![image](https://cloud.githubusercontent.com/assets/4503298/10130315/1e37b502-658d-11e5-875f-d2d8e5362af3.png)

Really need some help

**Comment by xaviershay** [comment]
Need the actual command that is running the test - it's the first line of the output window, but is truncated. My guess is it's loading up your code before running the file in question.
