### ISSUE TITLE
Question: Is -Xcli.debug=true actually necessary for correct metrics in JRuby?

### ISSUE THREAD

**Issue by phillip-koebbe-fidelity** [colszowka/simplecov#420]
We're using JRuby 1.7.x and 9000 and when we use

```
JRUBY_OPTS="-Xcli.debug=true --debug" bundle exec rspec
```

we get what we believe are accurate coverage metrics, but a lot of extra debug output. For one test suite, the extra output was 10,000+ lines in JRuby 1.7.x, but down to ~150 in 9000. Manageable, but still annoying. But when we remove `-Xcli.debug=true`, like so

```
JRUBY_OPTS="--debug" bundle exec rspec
```

we get the same coverage metrics but without the extra output. So this begs the question, is `-Xcli.debug=true` really necessary. It appears that is all the code is checking for, even though it suggests `--debug` in the warning:

From `simplecov/lib/simplecov.rb:4-13`:

```ruby
# Coverage may be inaccurate under JRUBY.
if defined?(JRUBY_VERSION)
  if ENV["JRUBY_OPTS"].to_s !~ /-Xcli.debug=true/
    warn "Coverage may be inaccurate; Try setting JRUBY_OPTS=\"-Xcli.debug=true --debug\""
    # see https://github.com/metricfu/metric_fu/pull/226
    #     https://github.com/jruby/jruby/issues/1196
    #     https://jira.codehaus.org/browse/JRUBY-6106
    #     https://github.com/colszowka/simplecov/issues/86
  end
end
```

**Comment by bf4** [comment]
@headius @enebo Is it simple impossible to get similar-to-MRI C0 code coverage details on JRuby 9000?  Does `-Xcli.debug=true --debug` no longer help improve how JRuby calculates coverage of Ruby lines?

**Comment by inossidabile** [comment]
That is true indeed. Running it against couple JRuby projects I have I get the same coverage without `-Xcli.debug=true` but with just `--debug`.

**Comment by envygeeks** [comment]
AFAIW --debug sets that flag for you, but while this topic is on the books, it constantly warns about this option even if we set it in `.jrubyrc` it would be nice if it detected this option in a cleaner way.

**Comment by bf4** [comment]
@envygeeks hmm.  I looked into how to get this info from the runtime at one point but didn't succeed.  Any help is appreciated.

**Comment by bf4** [comment]
At the time I did try just `--debug` https://github.com/metricfu/metric_fu/commit/7fd31ea637ac0747b85bd2d11889de412f29496f but I haven't played with it since

```plain
@enebo https://twitter.com/tom_enebo/status/462289024107814914
recommended JRUBY_OPTS="-Xcli.debug=true"
but that didn't work and caused other failures
JRUBY_OPTS="--debug" Still produced the below error, as did
JRUBY_OPTS="--debug -Xcli.debug=true"

Failure message was
home/travis/build/metricfu/metric_fu/gemfiles/vendor/bundle/jruby/1.9/gems/simplecov-0.8.2/lib/simplecov.rb:31 warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag

SimpleCov::Formatter::MetricFu calculates the same coverage from an RCov report as from SimpleCov
     Failure/Error: expect(source_file.coverage.count).to eq(covered_lines_from_rcov_text.count)

       expected: 11
            got: 8

       (compared using ==)
     # /home/travis/build/metricfu/metric_fu/spec/metric_fu/metrics/rcov/simplecov_formatter_spec.rb:52:in `(root)'
```

**Comment by envygeeks** [comment]
Coming to correct myself, it seems there is no `--debug` as it's not listed in the JRuby help but I know you can quickly detect debug mode with this:

```
jruby --dev -Xcli.debug=true -e '$stdout.puts JRuby.runtime.debug?'
true
```

**Comment by bf4** [comment]
Seems like that could be a PR right there

**Comment by envygeeks** [comment]
@bf4 I'm playing with JRuby a bit to see what options it has so far but I'll ship one after I finish testing, so far I know that the `--debug` option we thought existed is actually simply `-d` (that might be a bug in JRuby?) but here is what I've gathered so far quickly:

```
jruby --debug # Does not trigger JRuby.runtime.debug?
echo cli.debug=true > .jrubyrc # Triggers JRuby.runtime.debug?
jruby -Xcli.debug=true # Triggers JRuby.runtime.debug?
jruby -d # Triggers JRuby.runtime.debug
```
