### ISSUE TITLE
SimpleCov does not recognise most of my files

### ISSUE THREAD

**Issue by fiverrben** [colszowka/simplecov#424]
I'm using ruby-2.2.2 & SimpleCov (0.10.0) does not show all of my files when running rspec (3.3.0).

The command I run is: ``` bundle exec rspec spec ```

My spec_helper.rb looks like this:

```
require 'simplecov_loader'

ENV['RACK_ENV'] ||= 'test'
$env = ENV['RACK_ENV']
$service_name_str = "user_analytics_chimera"

require "rack/test"
require 'database_cleaner'

require_relative '../../lib/user_analytics'
require_relative "../#{$service_name_str}"

require_relative "../../worker/lib/helpers/db_helper"
require_relative "../../worker/lib/helpers/response_rate_helper"
require_relative "../../worker/lib/helpers/events_helper"
require_relative "../../worker/lib/response_rate_events"
require_relative "../../worker/lib/user_analytics_worker"

RSpec.configure do |config|
  config.mock_with :rspec
  config.order = :random
  config.tty = true
  config.formatter = :documentation
  config.expect_with :rspec do |expectations|
    expectations.syntax = :expect
  end
end
```

simplecov_loader.rb looks like this:
```
require 'simplecov'
require 'simplecov-rcov'

SimpleCov.formatters = [
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::RcovFormatter
]
SimpleCov.start
```

To verify the issue is files (which are missing from the report) not being loaded before SimpleCov.start, I've used prints.

Any thoughts? Your help is greatly appreciated.

**Comment by bf4** [comment]
Would you mind leaving some notes on how you solved your problem or not for anyone else who comes across this?

**Comment by fiverrben** [comment]
Sure thing.

Since my codebase is divided into two folders: service & worker, which share common code (in root directory), I could not understand why SimpleCov would not show code coverage of files included in the specs which sit in the service/spec directory (when being ran with service directory as work-dir using bundle exec rspec spec).

What I had to do eventually is use the root config prior to starting SimpleCov:
SimpleCov.root "#{Dir.getwd}/.."

my non-default folder structure caused my mistake.
