### ISSUE TITLE
No helper coverage in simplecov 0.11.0

### ISSUE THREAD

**Issue by Aqualon** [colszowka/simplecov#427]
Hi, after update to simplecov 0.11.0 all my helpers are shown with 0% coverage, even so I have specs for them running. If I manually add a ```require 'my_helper'``` to my_helper_spec.rb, I get coverage information again.

Is this supposed to be handled that way now or is it a bug?

**Comment by Aqualon** [comment]
Actually after some investigation I found out, that coverage was not executed also in older versions due to some misconfiguration in my app (SimpleCov.start was called too late). So it actually helped me to find a bug. So not an issue.

**Comment by xaviershay** [comment]
The system works! cc @hugopeixoto
