### ISSUE TITLE
Decreased coverage with version 0.11

### ISSUE THREAD

**Issue by DannyBen** [colszowka/simplecov#440]
Hi,

Not sure if this is the same issue as #433 or not.

After updating the gem from 0.10 to the latest 0.11.1 my code coverage dropped from 100% to 73%

The reasons as I could see are:

1. Files that were not considered in the coverage before we suddenly considered, and have 0% coverage.
2. Empty lines and comments are now considered

Here is a small screenshot of a file that should have 100% coverage
![simplecov](https://cloud.githubusercontent.com/assets/2405099/11740586/254b3ea0-9ffc-11e5-89ec-ad20eaf15bf5.png)

For now, I have locked simplecov at 0.10 in the Gemfile as a workaround.

Let me know if you need more details.

**Comment by xaviershay** [comment]
Thanks for the report!

First issue is expected per https://github.com/colszowka/simplecov/pull/422 ... occurs to me that we listed the feature in the changelog but not the defaults change for Rails. I just added this.

Second issue is a dup of #433 and should be fixed on master, though this needs confirmation before I'll release it. (There is also a work around on that ticket.)

**Comment by xaviershay** [comment]
Sorry #433 isn't fixed on master yet, there is an open PR: https://github.com/colszowka/simplecov/pull/436
