### ISSUE TITLE
generate wrong report when using grape

### ISSUE THREAD

**Issue by TangMonk** [colszowka/simplecov#445]
It always miss end point lines, like following:

![image](https://cloud.githubusercontent.com/assets/3498786/12370243/7e54fe6e-bc44-11e5-86e2-93e3554b6372.png)

![image](https://cloud.githubusercontent.com/assets/3498786/12370244/87aa9014-bc44-11e5-9c91-a9a9eae09dfe.png)

And more..., simplecov always miss this lines from `post`, `get`, `put`, `delete` block from grape DSL

Actually the test is ok, and I am sure it coverage this lines, But simplecov generate wrong report

**Comment by xaviershay** [comment]
Sorry you're having problems! Unfortunately there isn't enough information here for me to figure out what is going wrong.

How are you testing? Is it possible you're running the code in a separate or forked process? That could interfere with coverage.

Some other ideas (and potentially helpful data you could include) are in https://github.com/colszowka/simplecov/blob/master/CONTRIBUTING.md

Please do reopen when you provide more information.
