### ISSUE TITLE
lib/simplecov.rb:60: warning: instance variable @track_files_glob not initialized

### ISSUE THREAD

**Issue by fornellas** [colszowka/simplecov#446]
Hello,

It seems Simplecov module expect some instance variables to be set up by SimpleCov::Configuration. Of course the default value nil works, however, we get warnings from Ruby VM.  I believe this could be solved by improving SimpleCov::Configuration to either preset unset variables to nil, or, check them with Object#instance_variable_defined? before using.

If you think any of these is a good solution (or even suggest a better one), I can make the patch an pull request.

Sincerely,

**Comment by xaviershay** [comment]
I like initializing to `nil`. PR would be fantastic!
