### ISSUE TITLE
Merging doesn't work with test-unit

### ISSUE THREAD

**Issue by Ecco** [colszowka/simplecov#45]
Rails 3 application. Simple tests (no rspec, no cucumber).

If I add this to my gemfile :

require 'test-unit', '2.3.0'

then merging doesn't work as unit, functional, and integration test results overwrite each-other.

Thing is, I need this for the performance tests to work.

**Comment by bf4** [comment]
Closing as stale. Please reopen if this is still an issue. (And take a look at https://github.com/colszowka/simplecov/issues/340 )
