### ISSUE TITLE
Move ResultMergeHelper modules to utility methods

### ISSUE THREAD

**Issue by colszowka** [colszowka/simplecov#450]
This is a followup on #449 that was intentionally not changing too many things to avoid conflicts with #436 and #441. Once those are resolved we should be able to replace the dynamic includes on the array objects introduced in #449 with some utility class methods.

**Comment by bf4** [comment]
possibly related https://github.com/colszowka/simplecov/issues/501#issuecomment-226802034

**Comment by PragTob** [comment]
Done in #558 from my understanding :tada:
