### ISSUE TITLE
Determine if use of guard clauses should be enforced

### ISSUE THREAD

**Issue by craiglittle** [colszowka/simplecov#452]
As per [@colszowka's request](https://github.com/colszowka/simplecov/pull/448#issuecomment-174098260), this issue is for discussion between the contributors to determine if the [`Style/GuardClause` cop](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/GuardClause) should be enabled. This came up while bringing the codebase into compliance with the latest `rubocop` version. For the time being, the cop [has been disabled](https://github.com/craiglittle/simplecov/commit/6bc590ef89aa25e6d64b832f96ef4c4d56a4b1a3).

[Here's](https://github.com/colszowka/simplecov/blob/master/spec/faked_project/lib/faked_project/some_class.rb#L13-L21) the existing method in the codebase that raised this question.

For what it's worth, my two cents: I like that the use of guard clauses, where appropriate, reduces the level of indentation in a method, so I'm in favor of enabling the cop.

**Comment by colszowka** [comment]
/cc @bf4 @sferik  @xaviershay @amatsuda Gentlemen, what do you think?

Personally I'd prefer a simple if/else statement over a guard clause any time because it is easier to parse the control flow of the method this way, so I'd drop this particular cop.

**Comment by xaviershay** [comment]
I tend to prefer guard clause but don't think this is a thing that should be enforced by rubocop either way - depends on code context too much.

**Comment by sferik** [comment]
:+1: to what @xaviershay said.

**Comment by craiglittle** [comment]
Agreed! Context matters a lot with this technique. I think it makes sense to proceed with the cop turned off.

Closing this out...

**Comment by colszowka** [comment]
Thanks for giving your thoughts everyone, let's keep it this way then! :clap:
