### ISSUE TITLE
dropping json gem dependency

### ISSUE THREAD

**Issue by beanieboi** [colszowka/simplecov#458]
hello simplecov-contributors!

just out of interest, how important is supporting really really really old rubies for simplecov?
i recently saw this tweet from Mike Perham (https://github.com/rails/rails/pull/23453) and started looking at our Gemfiles. some of the projects only use simplecov and therefor a quite significant amount of gem dependencies.

dropping the json is just one example and it's only a minor code change, it's almost a philosophical question and there is no right or wrong. there are opinions. i'm interested in the opinion of you, the simplecov contributors.

thanks for simplecov!
ben

**Comment by xaviershay** [comment]
My take: if it's causing us problems we should drop EOL versions.

**Comment by colszowka** [comment]
I second that, I think we should get rid of support for EOL'd rubies. On the 2.x-vresions of Ruby I've personally not seen any upgrade issues anyway, so now that 2.0 is getting EOL'd this month it might even make sense to drop support for that too.

**Comment by colszowka** [comment]
Somewhat related as to supporting outdated rubies: A minor compatibility issue came up that breaks simplecov for 1.9.3, which EOL'd around a year ago: https://github.com/colszowka/simplecov/pull/448/files#r52411167

**Comment by beanieboi** [comment]
my personal take on this:
to me, it's ok to drop support for EOL'd versions of ruby (currently speaking of 1.8 and 1.9, 2.0 will be EOL'd in a few weeks). you can still use the older version of SimpleCov if you are on 1.8. you could consider security patches for older versions, but this introduces a lot of communication and maintenance overhead. i personally don't even know how i can install 1.8.7 on my mac without spending a significant amount of time on it.

what just came to my mind. maybe this can also simplify the rails integration? never versions of Rails are pretty hardcore at dropping older ruby versions. (AFAIK Rails 5 will only run on 2.2 and higher?)

i will prepare a PR that removes the `json` dependency, since it's included in 2.0 and higher. but i guess that should go into the next major versions where the dropped support for old rubies can be properly announced?

**Comment by PragTob** [comment]
Just dropepd support of old rubies and of the JSON gem.
