### ISSUE TITLE
Coverage drops when running bundle exec rake

### ISSUE THREAD

**Issue by magicalbanana** [colszowka/simplecov#459]
Running rspec alone produces the right coverage, but with I run rake and cucumber is also run, the coverage drops to the one generated by cucumber.

So typically, when run rspec independently it's around 100%, when I run cucumber independently it's around 40%. But when running rake, the coverage drops to about 70%.

So it goes to say that when I run `bundle exec rake` the rspec coverage should win out (or am I misunderstanding how merging works?) but instead the coverage generated by cucumber get's combined.

Any ideas why?

I have a `.simplecov` config

And require `simplecov` on both my rails_helper and env file (at the very top for both of them).

**Comment by colszowka** [comment]
First of all, you don't need to add simplecov to any env files, see the [Getting Started](https://github.com/colszowka/simplecov#getting-started) section in the README for the setup.

For the merging it sounds as if for some reason on how your specific rake test task is set up, the command name detection is not working correctly. Please see [the merging section](https://github.com/colszowka/simplecov#merging-results) of the README for information how this works, likely you'll simply need to add `SimpleCov.command_name 'RSpec'` in `spec_helper.rb` and `SimpleCov.command_name 'Cucumber'` in your cucumber `env.rb`.

**Comment by magicalbanana** [comment]
Actually, I believe it's working fine. I was mistaken when I thought that the cucumber test run produced 70%. It was actually only 40% and the rspec 100% so if I am not mistaken it's adding them together and dividing them.

So my question is, is this the intended behavior?
