### ISSUE TITLE
"track_files nil" not respected in latest release

### ISSUE THREAD

**Issue by kmewhort** [colszowka/simplecov#462]
I believe this is due to a bug introduced in #447, per my comments here: https://github.com/colszowka/simplecov/pull/447/files

**Comment by kmewhort** [comment]
Actually, on second look, those comments weren't accurate.  The issue seems to remain though that the config setting isn't respected anymore.

**Comment by craiglittle** [comment]
Could you expand on what you mean by "the config setting isn't respected anymore"? Is that true no matter what is passed to `track_files` or only with `nil`?

**Comment by kmewhort** [comment]
@craiglittle, we just did some more investigation and it indeed seems like the issue is that `track_files nil` no longer has any effect.  `track_files false` works though.

Is this change intentional? If so, maybe the solution is to simply add a note to the changelog.
