### ISSUE TITLE
LoadError: cannot load such file -- simplecov

### ISSUE THREAD

**Issue by jonbcampos** [colszowka/simplecov#464]
I had simplecov running for a while and then one day I had to downgrade my ruby version and since then I can't get it working no matter what I do.

Now I am running:
ruby 2.2.3p173
rails 4.2.4
simplecov 0.11.2
simplecov-html 0.10.0

I've tried uninstalling/reinstalling. I do make sure that the require/start block is at the top of my test_helper.rb but every time it hits the require line I get the error "LoadError: cannot load such file -- simplecov"

Any help would be greatly appreciated!

**Comment by josephks** [comment]
Gemsets are unique to a Ruby version.  You need to `gem install simplecov` in the new Ruby.

**Comment by jonbcampos** [comment]
Good point. Sadly I already did that as I know I have to include new gem's
per ruby installation. Currently a 'gem list' returns

...

simplecov (0.11.2)

simplecov-html (1.4.7)

...


Any other thoughts?

**Comment by jonbcampos** [comment]
I've done a clean uninstall/install of ruby using rvm. Still no go. I pulled simplecov out of the :test group and it started working. Any thoughts as to why and what the ramifications could be? How do I get it back in the test group?

**Comment by achiinto** [comment]
I can reproduce this issue too. With or without it in the test group, it still fails.

**Comment by BandanaPandey** [comment]
@jonbcampos , if you have already done ::
  gem install simplecov 
in your Gemfile after downgrading your ruby version.
Did you include (gem 'simplecov', :require => false) in your Gemfile :test group?
If you haven't try this.
Refer this [one](https://github.com/colszowka/simplecov/commit/1b5736f1012f91676b87f00f4189764be591fe3b) for the time being.
Also can we please provide us more information about what is there in your spec_helper.rb.

**Comment by jonbcampos** [comment]
I found the issue. When the gem was in test it would be ignored because of my .bundle/config file. At some point it thought that it only needed to run production/develop gems, not test. So once I removed the `BUNDLE_WITHOUT` everything started to work as anticipated. Thank  you for the follow up!

**Comment by coderbhairishav** [comment]
Just in case anyone still faces this issue. I recommend to remove the coverage folder from root directory of the project and then run the test. As none of the above solution worked for me!

**Comment by calebhaye** [comment]
Also, be sure to use `bundle exec rpsec` when appropriate
