### ISSUE TITLE
Buggy state of 0.11.x

### ISSUE THREAD

**Issue by DannyBen** [colszowka/simplecov#468]
I don't mean to be pushy or ungrateful for this great-gem-I-cant-live-without, but may I ask what is the state of the 0.11.x release?

It seems like something went a little sideways in all 0.11.x releases - I have been unable to upgrade to any of them, I am still stuck at 0.10 due to several issues - namely #467 , #454 , #443 and similar.

Normally, I wouldn't mind staying a little behind until things stabilize, but 0.10 is giving me some other issues I would like to get rid of already. For example, lack of coverage of concern files as mentioned in #167, and just now, a new issue, where the comment `# :nocov:` is considered "not covered" and drops my coverage rate... hows that for irony... :wink:
![simplecov](https://cloud.githubusercontent.com/assets/2405099/13556939/46e0c3ce-e3ee-11e5-8d05-05b18239aeb5.png)

**Comment by PragTob** [comment]
Closed by #551 as the skipping seems to be the main concern and for the others, there are other tickets :)
