### ISSUE TITLE
Possible to get coverage data without stopping server?

### ISSUE THREAD

**Issue by AshMcConnell** [colszowka/simplecov#471]
Hi Folks,

I have a JRuby on Rails application running on a server.  I was wondering if it is possible to get simplecov to provide the coverage data without stopping the server.  We have used jacoco (set up with tcp output) to grab the coverage data without stopping, is it possible with simplecov?

Perhaps it's possible to programmatically stop simplecov to dump it to file and then use rails to serve it?

Thanks for your help
All the best,
Ash

**Comment by bf4** [comment]
@AshMcConnell yes, though I'm not sure I understand why you'd want to never end your test suite.  If you're using this in production, try https://github.com/danmayer/coverband

SimpleCov.result will print results, but the stdlib Coverage module cannot be stopped and started

**Comment by PragTob** [comment]
I believe @bf4 said everything there is to say :)

![IMG_20180818_152929](https://user-images.githubusercontent.com/606517/70068051-98043100-15ef-11ea-82c4-8dbad07555fe.jpg)

**Comment by ponchithra-velayutham** [comment]
Can anybody say is there any way to stop simple cov server and get the results?
