### ISSUE TITLE
Exclude files from a group

### ISSUE THREAD

**Issue by pookah-net** [colszowka/simplecov#472]
I'm probably missing something very simple (and documented!), but I can't figure out how to exclude the test files from a group.

When I run the tests, I get a report that contains all of the relevant files for a group - including the test files! I just want to see the *tested* files, not the test files. Is that possible? 

Thanks in advance
Ian

**Comment by xaviershay** [comment]
I think you want a filter: https://github.com/colszowka/simplecov#string-filter ?

Please re-open with your current config if that doesn't help!

**Comment by pookah-net** [comment]
Yeah, that worked! :-) Not quite what I was thinking, but... It turned out I was having a dose of the "not enough coffee" and didn't make the connection between "filter" and "I don't want to see tests..."

Thanks!
