### ISSUE TITLE
QUESTION: Seperate tabs for Models and Model Concerns

### ISSUE THREAD

**Issue by Epigene** [colszowka/simplecov#484]
Hi!

I have this block in rails_helper.rb

``` ruby
SimpleCov.start 'rails' do
  add_filter '/spec/'
  add_filter '/config/'
  add_filter '/vendor/'
  add_filter '/test/'
  add_filter '/lib/'
  add_filter '/db/'
  add_filter '/log/'
  add_filter '/tmp/'

  add_group 'Controllers', 'app/controllers'
  add_group 'Models', 'app/models'
  add_group 'Helpers', 'app/helpers'
  add_group 'Mailers', 'app/mailers'
  add_group 'Views', 'app/views'
  add_group 'Model Concerns', 'app/models/concerns'
end
```

This gives me tabs for "Models" and "Model Concerns" in coverage report, unfortunately, the "Models" tab also includes the reports on concerns. Indeed, it includes reports on _all_ files in /models and subdirectories.

How can I change the formatting in the line below to only load files in that directory, without any subdirectories?

```
add_group 'Models', 'app/models'
```

**Comment by PragTob** [comment]
Hi there,

there are different kinds of filters, [see the code dispatching them here](https://github.com/colszowka/simplecov/blob/master/lib/simplecov/configuration.rb#L284-L303) and see their [actual implementation here](https://github.com/colszowka/simplecov/blob/master/lib/simplecov/filter.rb)

So from my understanding, you could just implement a block that does what you want it to do - e.g. return true for file names in app/models except for app/models/concerns. You could also implement your own filter class of course.

Hope this helps you, let us know if not :)

**Comment by Epigene** [comment]
Thanks!

I managed to get the exclusion working by passing a block.

```rb
add_group 'Models' do |file|
  file.filename[%r'/app/models'].present? && file.filename[%r'/app/models/concerns'].blank?
end
```
