### ISSUE TITLE
let me know what exception happened in at_exit

### ISSUE THREAD

**Issue by grosser** [colszowka/simplecov#493]
I'm doing some custom reporting and want to not do that when the user has Interrupted the test run,
can we pass in $! to the at_exit call ... or store it somewhere globally ?

**Comment by bf4** [comment]
Hi @grosser So, given https://github.com/colszowka/simplecov/blob/c66eaa1b7fc38ab54cc5d34fba21ea7834943f5d/lib/simplecov/defaults.rb#L56-L65, any thoughts about interface and name? Part of the result? an attribute on `SimpleCov`? `exit_exception`?

**Comment by grosser** [comment]
calling at_exit with status + exception could be nice ... otherwise `exit_exception` would make sense ...
