### ISSUE TITLE
Merging resultset.json from multiple VMs

### ISSUE THREAD

**Issue by garyharan** [colszowka/simplecov#496]
I have 4 `.resultset.json` files on 4 different VMs.  Each VM runs a separate set of files and I want to merge all the files into a single one.

Is there any good way to merge 4 `.resultset.json` files into a single one?

**Comment by bf4** [comment]
possibly related https://github.com/colszowka/simplecov/issues/501#issuecomment-226802034

**Comment by ayufan** [comment]
@garyharan This is how I achieved that in GitLab: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5018 and it works great :)

**Comment by PragTob** [comment]
@garyharan is this still a problem? Has the solution above helped you?

**Comment by garyharan** [comment]
@ayufan thanks for the share!  I'm afraid I only looked at this today (github notifications is like a giant turd sometimes) and it looks like a good approach!

@PragTob I'm pretty sure this solution will work!  Thank you!
