### ISSUE TITLE
Sub Projects aggregation

### ISSUE THREAD

**Issue by driverpt** [colszowka/simplecov#497]
We're trying to aggregate SimpleCov results from 4 gems that under the same project structure. The purpose is getting Jenkins Code Coverage results, but the thing is Jenkins only accepts one directory for coverage and we wanted to aggregate all 4 sub-gems into the same result.

Is this possible?

P.S.: I've been reading all the way in the web (Stackoverflow, Google, etc...) and i can't find how to do this.

**Comment by bf4** [comment]
possibly related https://github.com/colszowka/simplecov/issues/501#issuecomment-226802034

**Comment by PragTob** [comment]
Hi there @driverpt !

Does the problem still persist?

FWIW over at shoes/shoes4 we aggregate the results of several gems through running all the tests and giving different invocations different command_names (e.g. spec:shoes and spec:swt) as described in the [merging results](https://github.com/colszowka/simplecov#merging-results) section. Maybe that helps?

**Comment by PragTob** [comment]
Closing due to no further feedback
