### ISSUE TITLE
Zero coverage on simple model files

### ISSUE THREAD

**Issue by Daniel-ltw** [colszowka/simplecov#507]
```Ruby
class Person < ActiveRecord::Base
  self.table_name = "people"
end
```

This gives 0 coverage on that file even if some bits of code uses that model. 

Anyone with that issue?

**Comment by bf4** [comment]
@Daniel-ltw see 'where coverage comes from' https://github.com/colszowka/simplecov/issues/340

(if you'd like, that issue definitely still needs to be made into a page. easy pr)
