### ISSUE TITLE
Ignoring hits inside of parallel block

### ISSUE THREAD

**Issue by vinnyoodles** [colszowka/simplecov#510]
I'm using the parallel gem for this. It seems like the code coverage is not counting the hits inside of the parallel block.

![screenshot from 2016-07-05 14-32-43](https://cloud.githubusercontent.com/assets/8698599/16595482/5b15d608-42bd-11e6-9be9-592fe2608254.png)

**Comment by PragTob** [comment]
Hi there @vinnyoodles !

Thanks for the report. Could you provide us with a test repository/test script? That would make this much easier to debug, otherwise it's quite hard to debug sadly :(

**Comment by PragTob** [comment]
Also I'm guessing that the parallel block might spawn new processes which might be where the interference comes from. Without a test repo to reproduce this is quite hard to fix.

**Comment by PragTob** [comment]
Without a test repo there isn't much to be done here sadly. The problem might also be based on the forking which might be an inherent challenge with the way the`coverage` library works so fixing it would be pretty hard/almost impossible either way.
