### ISSUE TITLE
Relaxed JSON dependency is incompatible with Ruby < 2.0

### ISSUE THREAD

**Issue by presidentbeef** [colszowka/simplecov#511]
First off, let me commiserate with you about how hard it is to maintain compatibility with older versions of Ruby while your dependencies don't. It's a real pain.

That being said, relaxing the `json` version dependency (b47a3bd33d70f90ea2339ec2cef2c7427a6cb825 with the 0.12.0 release) causes Bundler and RubyGems to pick the _latest_ `json` version, which explicitly declares a dependency on Ruby 2.0+.

For example:

```
$ ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ gem install simplecov
Fetching: docile-1.1.5.gem (100%)
Successfully installed docile-1.1.5
ERROR:  Error installing simplecov:
    json requires Ruby version ~> 2.0.
```

It seems that you want to keep the `json` dependency for 1.8.7 compatibility (per closing #491) but actually compatibility is now lost:

```
$ ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
$ gem install simplecov
Fetching: json-2.0.1.gem (100%)
ERROR:  Error installing simplecov:
    json requires Ruby version ~> 2.0.
```

One solution for simplecov users might be to explicitly declare their dependency on `json` < 2.0, but it's kind of silly to manage transitive dependency versions when your app/library has already removed `json` as a dependency. :confused: 

I don't know how you want to handle it, but by trying to support newer `json` you've broken 1.8.7 and 1.9.3 compatibility, while removing `json` would only break it for 1.8.7.

(I should note the tests passed only by [actively managing](https://github.com/colszowka/simplecov/blob/b47a3bd33d70f90ea2339ec2cef2c7427a6cb825/Gemfile#L18-L20) the `json` version in the Gemfile. Unfortunately this does not translate to working for end-users.)

**Comment by BenMorganIO** [comment]
Let's get rid of the json gem. Ruby 1.9.3+ already come packaged with it. This gem, from their readme, doesn't support 1.8.3 anyways. One less dependency is always encouraged.

**Comment by bf4** [comment]
One option is:

```ruby
# lib/simplecov.rb
gem 'json', ">= 1.8", "< 3"
```

would cause any users of simplecov to fail fast if the correct json isn't available in the expected versions.

**Comment by BenMorganIO** [comment]
@bf4 that could work. What about:

```ruby
gem 'json', '>= 1.8', '< 3' unless require 'json'
```

**Comment by bf4** [comment]
The gem command needs to come before the require

**Comment by BenMorganIO** [comment]
Ah, right, chicken and the egg problem. But anywho, I'm :+1: for this.

**Comment by albfan** [comment]
There's no way to force 1.8 for ruby 1.9.3? GemFile does that specifically: [Gemfile:35](https://github.com/colszowka/simplecov/blob/master/Gemfile#L35)

**Comment by bf4** [comment]
@albfan no, gems are built and gemspec evaluated at build time.  If it were possible, we would have done it.

**Comment by bf4** [comment]
@colszowka locked comments. ccing you in case you disagree

**Comment by PragTob** [comment]
As we just dropped ruby support for a bunch of old ruby version and are now relying on stdlib JSON this shouldn't be an issue any longer.
