### ISSUE TITLE
Default filters for Rails profile exclude unexpected files

### ISSUE THREAD

**Issue by grzesiek** [colszowka/simplecov#514]
Currently, default profile for `:rails` adds some filters, for example `/config/` and `/db/` filters.

Because of how filters are implemented this will also exclude files located in `/lib/module/my/config/for/something/` which is a little unexpected.

It would be great to make it possible to improve files to match against relative routes like `\A/config/` or something like that, what do you think?

Thanks for the great work with SimpleCov!

**Comment by PragTob** [comment]
Hey there,

thanks for the issue report!

That seems like a problem indeed :smile: Imo the default profile should only exclude files in the root config folder.
