### ISSUE TITLE
Move this repo to https://github.com/jazzband

### ISSUE THREAD

**Issue by oamado** [colszowka/simplecov#519]
Hi @colszowka 

You could move the repo to https://jazzband.co/
check the code of conduct https://jazzband.co/about/conduct
this can help everyone

**Comment by colszowka** [comment]
@oamado We have a number of contributors right here where the repo lives, and what I feel is an adequate community that is triaging issues. Also, the org you mention seems mostly python/django related, so this might not be such a great fit. Thanks for the suggestion, but we'll keep it here :)

**Comment by oamado** [comment]
thanks for answer @colszowka
