### ISSUE TITLE
coverage 100% for add_filter simplecov

### ISSUE THREAD

**Issue by BandanaPandey** [colszowka/simplecov#522]
I am using following in my app::
simplecov 0.12.0
simplecov-html 0.10.0

And included following in my test_helper.rb::
require 'simplecov'
SimpleCov.start 'rails' do
  add_filter '/lib/'
end

I am seeing 100% coverage for libraries on using simplecov on my local machine.
Is this correct?
Thoughts?

**Comment by robinvdijk** [comment]
That seem the correct behaviour. If you add a filter, it sets the coverage to 100% for that category.

**Comment by PragTob** [comment]
Yes for all that I know this is correct, as you basically skip every line in lib and then that is considered 100% (as you wanted to skip). If I'm wrong or this behavior has some bad implications I'm unaware of let me know :)
