### ISSUE TITLE
lines with the skip_token are counted as not covered

### ISSUE THREAD

**Issue by cemeyer2** [colszowka/simplecov#527]
Lines that are marked with the `skip_token` such as `nocov` are being counted as not covered. In the screenshot below, I attempted to declare that an entire file should not be covered, but after annotating it it shows 2 lines not covered, which are the 2 that have the `skip_token` on them.

<img width="429" alt="screen shot 2016-10-12 at 20 33 09" src="https://cloud.githubusercontent.com/assets/102593/19333426/284515e4-90bb-11e6-8328-9d2d56e99bdc.png">

per `CONTRIBUTING.md`:
- I am using simplecov v0.12.0
- `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`
- `rails (5.0.0.1)`
- no other coverage gems
- using `rspec-rails (3.5.2)`

please let me know if more info is needed to debug

**Comment by cemeyer2** [comment]
seems very similar to #468

**Comment by PragTob** [comment]
Fixed by #551
