### ISSUE TITLE
uninitialized constant Module::Coverage (NameError)

### ISSUE THREAD

**Issue by eprothro** [colszowka/simplecov#528]
I've added simplecov to my gemfile (I've commented out everything else except rspec)

In my spec_helper I require a file `coverage.rb`

```
require 'simplecov'
SimpleCov.start
```

This raises `uninitialized constant Module::Coverage (NameError)` from the call to `start`.

Calling from `ruby spec/coverage.rb` works fine, as does executing the two lines from `irb`.

Any ideas?

**Comment by eprothro** [comment]
After pulling my hair out for a while... renaming `coverage.rb` to `code_coverage.rb` worked around the issue.

**Comment by colszowka** [comment]
@eprothro I'll assume this solved the issue for you. This basically broke the loading mechanism of ruby since simplecov itself requires `coverage` from the Ruby stdlib, and this filename apparently confused it :)

Feel free to reopen should the issue persist

**Comment by eprothro** [comment]
Yes, this worked around the issue. I would hope that simplecov would require the file it intends more specifically to actually resolve the issue.

**Comment by colszowka** [comment]
Hm, is there a way to explicitly `require` bits of the ruby standard library? I'm not familiar with any

**Comment by eprothro** [comment]
Ah, I didn't read thoroughly enough, sorry. Didn't realize it was a stdlib conflict.
