### ISSUE TITLE
.resultset.json does not store more than 15MByte of results

### ISSUE THREAD

**Issue by remco-dg** [colszowka/simplecov#535]
We have a program which is repeatedly started and stopped. In that program, we have the following code:

require 'simplecov'
SimpleCov.project_name('ourprojectname')
SimpleCov.coverage_dir('/opt/coverage')
SimpleCov.formatter = SimpleCov::Formatter::HTMLFormatter
SimpleCov.merge_timeout 1073741823 # (2^30)-1
SimpleCov.command_name Time.now.to_s
SimpleCov.start do
  add_filter "/usr/" # Do not show files from /usr/
end

def main
     call to large set of program code in other files here 
     SimpleCov.result.format!
end

Now as you can see, the SimpleCov.command_name is set to a unique name every time we run the program. We found that after 25 times starting and stopping the program, the results of the first 24 data sets were removed from the coverage results. We were expecting (based on the Simplecov documentation) that we could run several hundreds of tests. The issue seems to be trigged by the size of the .resultset.json. When the .resultset.json gets larger than 15MByte, this issue occurs.

% gem list | grep simple
simplecov (0.12.0)
simplecov-html (0.10.0)
% ruby -e "puts RUBY_DESCRIPTION"
ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]
No Rails used
No other coverage gems used
Not running any unittest framework
Not using a .simplecov file

**Comment by PragTob** [comment]
:wave: 

Sorry for no comment for so long :sweat_smile: 

Does this issue still occur? If it does are there any other indications? It'd be decidedly weird if it was linked to the size of the JSON.

**Comment by remco-dg** [comment]
We finished our simplecov tests 3 years ago. If we are going to use simplecov again, we need to build up the test-environment from scratch anyway, including a new version of simplecov, so there is no need now to investigate this issue any further.
