### ISSUE TITLE
JSON runtime dependency for Ruby versions "< 2"

### ISSUE THREAD

**Issue by 1v** [colszowka/simplecov#536]
If I add `simplecov` to my gem as development dependency my tests on Ruby 1.9.3 fails because of `json` gem. 
```
json-2.0.2 requires ruby version ~> 2.0, which is incompatible with the current
```
I can fix this by adding json as my gem's runtime dependency:
```
gem.add_runtime_dependency "json", "~> 1.8", "< 2" if RUBY_VERSION < "2"
```
So maybe you add this line as `simplecov` dependency?

**Comment by 1v** [comment]
Should be like this:
```ruby
  if RUBY_VERSION < "2"
    gem.add_dependency "json", ">= 1.8", "< 2"
  else
    gem.add_dependency "json", ">= 1.8", "< 3"
  end
```
I think.

**Comment by 1v** [comment]
I see your tests somehow passing with ruby 1.9.3 and bundler somehow installing json version 1.8.3 on all rubies. But this because of `cache: bundler` in `.travis.yml`. Fails if remove https://travis-ci.org/1v/simplecov/builds/174092020

**Comment by bf4** [comment]
@1v 

gemspecs aren't dynamic. They are only executed when the gem is built. So, if you're bundling from source, it will be executed each time, but otherwise, when publishing a gem, the condition is only executed at build.  That is, you can't `gem.add_dependency "json", ">= 1.8", (RUBY_VERSION < "2" ? "< 2" : "< 3")`

**Comment by bf4** [comment]
Seems like the problem is for the json gem 3.0 to specify a minimal ruby version :(

-Benjamin

**Comment by 1v** [comment]
No, you can :smile::
ruby 1.9.3 https://travis-ci.org/1v/simplecov/jobs/174097796#L169
ruby 2.0.0 https://travis-ci.org/1v/simplecov/jobs/174097797#L169
What changed: https://github.com/colszowka/simplecov/compare/colszowka:6e5ec23...1v:dc779c0

**Comment by bf4** [comment]
@1v That's bundling from source. If you don't believe me, do this:  `gem build simplecov.gemspec` then you have a choice of untarring it and inspecting or something like ` gem specification simplecov-0.12.0.gem | grep name -A 5 | grep json -A 5`.

**Comment by colszowka** [comment]
@1v In general, Ruby 1.9 has reached end of life [almost two years ago](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) and shouldn't be used for anything really. I think the correct way to go forward here for simplecov would be to declare a strict ruby version compatibility in the gemspec that only allows still-alive rubies to be used to make the point clear.

In my experience, upgrading on the post 1.9-Ruby versions is fairly straightforward (at least in comparison to 1.8>1.9)

**Comment by 1v** [comment]
Even Ruby 2.0 security maintenance ended [wiki](https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions).

Anyway, it is possible to install dependencies for specified rubies.

Create file `ext/mkrf_conf.rb`:
```ruby
require 'rubygems/dependency_installer'

di = Gem::DependencyInstaller.new

begin
  if RUBY_VERSION < "2"
    di.install "json", "< 2"
  else
    di.install "json", ">= 2"
  end
rescue => e
  exit!
end
# Write fake Rakefile for rake since Makefile isn't used
File.open(File.join(File.dirname(__FILE__), 'Rakefile'), 'w') do |f|
  f.write("task :default" + $/)
end
```
And add to `.gemspec`:
```ruby
spec.extensions << 'ext/mkrf_conf.rb'
```
Downside: dependency installed silently.

**Comment by bf4** [comment]
@1v that is a not recommended use of the extensions api. I say this as someone who trod a similar path some years ago during the 1.8 to 1.9 transition while maintaining metric_fu, so totally empathize, and apologize for not having links to support my assertions at this time. (On phone)
