### ISSUE TITLE
Release of a Ruby 2.4 compatible version

### ISSUE THREAD

**Issue by spickermann** [colszowka/simplecov#544]
Hi @colszowka

I noticed that the current master is already compatible with Ruby 2.4 and for example the Fixnum deprecation warning is already removed (see: https://github.com/colszowka/simplecov/commit/050eb6830440bf998c462aee219f8b3cd17d570f). Great.

What are your plans about releasing a new version of simplecov?

Cheers.

**Comment by dreyks** [comment]
Also why not drop the dependency on `json` gem entirely since it's been in Ruby stdlib since at least 2.0.0?

**Comment by PragTob** [comment]
@dreyks this gem still supports ruby 1.9.3 so that's why it can't be removed. Maybe at some point in the future support may be dropped but not now for all that I can tell/say :)

**Comment by spickermann** [comment]
Hi @colszowka,

I do not want to bully you. But I wonder when the next, a Ruby 2.4 compatible version of simplecov will be released.

From my point of view the current master seems to be compatible with Ruby 2.4. Is there something that blocks a release? Is there something that still needs to be done? Perhaps something I can do or where I can help?

Cheers.

**Comment by colszowka** [comment]
@spickermann The [changelog](https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md) needs to be updated prior to releasing, based on https://github.com/colszowka/simplecov/compare/v0.12.0...master

I've been intending to do that for the past two weeks but keep bumping into other stuff I need to do in the evenings, so didn't get around to it yet. If someone wants to go through the commit list and compile the changelog as a PR, that would be excellent. Please also mention that you're doing this here so we don't end up doing the work three times over :heart:

**Comment by PragTob** [comment]
@colszowka I will do that this evening :)

**Comment by colszowka** [comment]
@PragTob Thanks a lot!

Also, I've finally added you to the collaborators und rubygems owners here and on simplecov-html.

@bf4 @xaviershay @sferik @amatsuda I've recently suggested to @PragTob to join the team when we met at a user meetup - in addition to a variety of great things he's doing for the Ruby community he's actively using simplecov with JRuby and can therfore help us making SimpleCov support for JRuby official. Welcome on board Tobi! And, somewhat related: Thanks everyone already aboard for all your wonderful help with maintaining this project for the past years!

**Comment by PragTob** [comment]
Thanks :) I also have the honor of vaguely knowing @bf4 and knowing @sferik rather well so I guess we'll get along well =D

:wave: @xaviershay @amatsuda

**Comment by PragTob** [comment]
:star2: #546 :star2:

**Comment by PragTob** [comment]
:tada: [0.13.0](https://rubygems.org/gems/simplecov/versions/0.13.0) :tada:

**Comment by PragTob** [comment]
Also, of course please test this out and if you encounter any issues please let us know! :)

**Comment by colszowka** [comment]
Excellent, thanks!
