### ISSUE TITLE
Getting different results if executed with rake or rspec

### ISSUE THREAD

**Issue by fabn** [colszowka/simplecov#562]
I've used simplecov for a lot a different projects and never had an issue. However now I'm integrating it in a new project and I'm noticing a very weird behaviour. It's a rails project tested with RSpec, pretty standard.

If I integrate simplecov in the usual way I get different output according on how I run tests. I've added the usual blocks in Gemfile and rails helper
```ruby
# rails_helper.rb
require 'simplecov'
SimpleCov.start 'rails'
# Gemfile
group :test do
  gem 'simplecov', require: false
end
```

I noticed the behavior because it wasn't reporting some classes as covered and I know that those classes are covered by tests. If I change configuration (or command line) as shown below the total coverage changes accordingly.

Here's the output of simplecov:

```
# With bundle exec rspec
Coverage report generated for RSpec to ./coverage. 1036 / 2670 LOC (38.8%) covered.
# With bundle exec rake
Coverage report generated for RSpec to ./coverage. 1359 / 2014 LOC (67.48%) covered.
# And this is the weirdest thing, if I change the SimpleCov.start 'rails' with SimpleCov.start 
# I get this, i.e. the right coverage of my tests, but obviously in the html report I get no groups.
Coverage report generated for RSpec to ./coverage. 3216 / 3351 LOC (95.97%) covered. 
```

Here are the relevant gems in my bundle:

```
Gems included by the bundle:
  * rails (4.2.7.1)
  * rake (12.0.0)
  * rspec-core (3.4.4)
  * rspec-expectations (3.4.0)
  * rspec-mocks (3.4.1)
  * rspec-rails (3.4.2)
  * rspec-support (3.4.1)
  * simplecov (0.13.0)
  * simplecov-html (0.10.0)
  * spring-commands-rspec (1.0.4)
```

**Comment by PragTob** [comment]
Hi there!

Thanks for reporting a bug!

The last command that gets you "the best" coverage result, are you running `bundle exec rspec` there or `bundle exec rake` ?

My immediate thought would be that for some reason it loads some files before SimpleCov.start is run and therefore missing coverage.

regarding the profile, the rails profile also adds a couple of fitlers such as for the tests themselves and unneeded files like config ( see https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb ) so that might be a starting point.

Cheers,
Tobi

**Comment by fabn** [comment]
For the last point, ok. That's explained why the output differs so much.

Also, I see that executing rspec with explicit bundle exec (so without binstubs and spring) gives the same output as rake.

I think then that this issue can be closed, I'll reopen if I can reproduce with bundle exec or in CI env.

Thanks.

**Comment by PragTob** [comment]
Thank you :+1: 

As for binstubs, especially with spring that already has the code preloaded and stuff.. which messes with what Simplecov does :(
