### ISSUE TITLE
Should fully skipped files be marked as 100% covered or 0% covered?

### ISSUE THREAD

**Issue by PragTob** [colszowka/simplecov#565]
We are treating files that are fully irrelevant (just comments for instance) different from files that are skipped through `# :nocov:` as a whole. A file with just irrelevant lines gets 100% coverage, one where all lines are skipped (or some are irrelevant) gets 0% coverage:

![selection_062](https://cloud.githubusercontent.com/assets/606517/24075294/c0e91e34-0c18-11e7-9c97-b99ab96d0d34.png)

![selection_063](https://cloud.githubusercontent.com/assets/606517/24075296/c6cc7bf2-0c18-11e7-8368-59266fee376a.png)

Question is: Does that sound right? I feel like skipped lines should mostly be like non relevant lines (as the user decided they are not relevant) and it feels weird that a file is 0% covered, but the whole project still has 100% coverage. Removing that distinction would also simplify the code :)

Stumbled on this while investigating #563 (fix in #564 )I stumbled across - e.g. the difference (as apparent in the fix) that mostly caused it was the difference that `no_lines?` is different from `relevant_lines.zero?`as `no_lines?` only triggers if all lines are irrelevant (such as comments only).

**Comment by PragTob** [comment]
@colszowka would love to get your input here, as I might be missing something :)

**Comment by krtschmr** [comment]
came here since i we have same issue.

some rake tasks, like annotate_models or generate_erd_diagram are sitting at 0% because it's `nocov`

doesn't make any sense at all.

i checked but can't find a filter or exclude method to just exclude them from the coverage at all.
like

`excluded_files.include(current_file)`

seems. to not exist.

**Comment by PragTob** [comment]
If no one stops me I'll change it to be 100% :)


![bunnies](https://user-images.githubusercontent.com/606517/70067285-51fa9d80-15ee-11ea-91f6-add87de04709.jpeg)

**Comment by PragTob** [comment]
No one stopped me :man_shrugging:
