### ISSUE TITLE
Controller Methods Not Being Covered by Tests

### ISSUE THREAD

**Issue by bjigarjian** [colszowka/simplecov#568]
I've been having this issue where simplecov does not cover code inside of my controller methods. My group has been working on this problem for weeks and no one has been able to figure out what is wrong. Our models are getting covered, but the methods inside of controllers are not working even though we have many tests that should cover these methods. Any suggestions are welcome. 

Here is the gem in my Gemfile. 
gem 'simplecov', :require => false, :group => :test

I am using Rails 4.2.6 with ruby 2.3.1

I am using the testing framework that comes with rails. To run my tests I run 
bundle exec rake test. 
Simplecov is required at the top of my Rakefile. My test_helper is below:

```ruby
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
  SimpleCov.start 'rails' do
    add_filter "/users/"
  end
  puts "required simplecov"
end

ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...

end
```

Thanks for helping.

**Comment by bf4** [comment]
Are you sure simplecov is started before any application code is required/loaded?

**Comment by PragTob** [comment]
Closing due to no further feedback
