### ISSUE TITLE
track_files forgets about files explicitly configured to be tracked.

### ISSUE THREAD

**Issue by NullVoxPopuli** [colszowka/simplecov#572]
my current config:

```ruby
files = `git ls-files app | grep '.rb'`.chomp.split("\n").map(&:strip)
SimpleCov.start do
  # I couldn't trust globs to include everything, since I'm using a non-standard rails structure,
  # and nothing seems to be working, so explicitness wins right now
  files.each { |f| track_files(f) }

  add_group 'Models', 'app/models'
  add_group 'Controllers', '.*controller.*'
  add_group 'Operations', '.*operation.*'
  add_group 'Policies', '.*polic.*'
  add_group 'Mailers', 'app/mailers'
  add_group 'Serializers', '.*serializer.*'
  add_group 'Jobs', '.*job.*'
  add_group 'Forms', '.*form.*'
  add_group 'Services', 'app/services'

  filters.clear
  add_filter '/app/admin/'
  add_filter '/app/helpers/'
  add_filter '/app/views/'
  add_filter '/gems/'
  add_filter '/spec/'
  add_filter '/config/'
  add_filter '/public/'
  add_filter '/db/'
end

Rails.application.eager_load!
```

This results in only having coverage% > 0 show up in the outputted report.

I've found I can add 
```
# This is a hack to load un-tested files...
# http://www.dixis.com/?p=715
base_result = {}
files.each do |file|
  absolute = File.expand_path(file)
  lines = File.readlines(absolute, encoding: 'UTF-8')
  base_result[absolute] = lines.map do |l|
    l.strip!
    l.empty? || l =~ /^end$/ || l[-1] == '#' ? nil : -1
  end
end

SimpleCov.at_exit do
  original = SimpleCov.result.original_result

  merged = SimpleCov::RawCoverage.merge_resultsets(original, base_result)
  result = SimpleCov::Result.new(merged)
  result.format!
end
``` 
after SimpleCov.start to at least have all the files show up in the report, but then files that were previously covered now show as uncovered.

How do I tell simplecov to watch all files, and not discard them if they aren't covered?

**Comment by NullVoxPopuli** [comment]
I have one particular file:
`app/models/data/person.rb`

```ruby
files = `git ls-files app | grep '.rb'`.chomp.split("\n").map(&:strip)
ap `pwd`
ap files.select{ |f| f.include?('person') }
```
prints: 
```
"/web\n"
[
    [0] "app/admin/person.rb",
    [1] "app/helpers/person_helper.rb",
    [2] "app/models/data/account_contact_person.rb",
    [3] "app/models/data/operational_person.rb",
    [4] "app/models/data/person.rb"
]

```
and then the person.rb tests run... and pass...

but, in the `at_exit` block, I modified the whole thing to look like this
```ruby
SimpleCov.at_exit do
  original = SimpleCov.result.original_result
  ap original.keys.select{ |f| f.include?('person') }
  merged = SimpleCov::RawCoverage.merge_resultsets(base_result, original)
  result = SimpleCov::Result.new(merged)
  result.format!
end
```

which prints:
```

[
    [0] "/web/app/models/data/account_contact_person.rb",
    [1] "/web/app/models/data/operational_person.rb"
]
```

(this is a docker environment, so that's where the `/web` prefix came from)

**Comment by NullVoxPopuli** [comment]
versions:

```
$ ./run gem list | grep -E "(^simple)|(^rails)"
rails (5.0.0.1)
rails-controller-testing (1.0.1)
rails-dom-testing (2.0.2)
rails-html-sanitizer (1.0.3)
rails-settings-cached (0.6.5)
rails_12factor (0.0.3)
rails_serve_static_assets (0.0.5)
rails_stdout_logging (0.0.5)
simplecov (0.14.1)
simplecov-html (0.10.0)

 $ ./run ruby -v
Running Command: ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

```

**Comment by jgonera** [comment]
That's how it works presently. It only accepts a single glob:
https://github.com/colszowka/simplecov/blob/abdf6a294f030a9407606adcf541d52505622b1b/lib/simplecov/configuration.rb#L48-L55

**Comment by PragTob** [comment]
How @jgonera said - calling `track_files` multiple times isn't really a supported interface atm but could be added - albeit probably with another name. 

If you want that, you can please open another issue about it :)

**Comment by NullVoxPopuli** [comment]
is there a reason `app/**/*.rb` wouldn't include everything? 
it looks like **/* is supposed to mean recursive in blobs.

**Comment by PragTob** [comment]
To the best of my understanding `app/**/*.rb` should include every `.rb` file nested under app - I might be wrong as always though ;)

**Comment by NullVoxPopuli** [comment]
It seems to only include files that have tests. Any file with 0 coverage is
omitted

**Comment by NullVoxPopuli** [comment]
How does simplecov detect when a test touches lines in a file? as far as I can tell, my problem isn't actually the loading of the files, but actually with detecting that tests have executed lines without those files.

I was looking at `SimpleCov.add_not_loaded_files`, and it uses `Dir[glob]`.
I tested in `irb` that `Dir['app/**/*.rb'] == Dir.glob('app/**/*.rb')` and that `app/**/*.rb` correctly recursively finds all the files. 

So, that means this _isn't_ a problem with `track_files` but with how the files are actually being tracked. track_files appropriately sets the initial coverage to 0, but then never updates.

**Comment by PragTob** [comment]
Afaik all that is done by the underlying `Coverage` library, but I'd need to dive into the code to find out myself. It could also be that it is tracked correctly but then the results don't show up correctly in the end, there is some code around none covered lines in SimpleCov and how to deal with it if they are skipped/not_covered/whatever

**Comment by NullVoxPopuli** [comment]
what's the `Coverage` library called. I seed it's referenced in a few places, but I can't seem to find where it's required anywhere -- gemspec  and Gemfile don't mention it.

**Comment by NullVoxPopuli** [comment]
oh it's built in. I see that in the readme now. hmm

**Comment by NullVoxPopuli** [comment]
so, here is how I'm investigating:
```ruby
module SimpleCov
  class SourceFile
    def initialize(filename, coverage)
      binding.pry if filename.include?('person')
      @filename = filename
      @coverage = coverage
    end
  end
```

I ran `./tests spec/models/data/person_spec.rb`

which correctly runs the specs from that file, which loads `app/models/data/person.rb` -- which defines a few relationships (things that would be evaluated an marked as covered upon file load).

I notice the first `binding.pry` catch is on `account_contact_person.rb` which inherits `person.rb`. This `account_contact_person.rb` file has 3 lines covered (1's in the coverage array).

I type `continue` into pry, and get another subclass of `person.rb`, `operational_person.rb` (these are all under `app/models/data`. This file has 1 coverage line - the class is just the class def and nothing else.

I type `continue` again, and get to the `app/helpers/person_helper.rb`. Not related to models.

I type `continue` again, and finally get `app/models/data/person.rb` -- the file I've been looking for.
It's coverage is all 0s. :-\ 

So the root of my problem appears to be with Ruby's `Coverage`.

**Comment by NullVoxPopuli** [comment]
Something weird I noticed, was that each of those files was sent to `SimpleCov::SourceFile.initialize` 7 times. :-\
that's weird.

**Comment by PragTob** [comment]
Afaik if `Coverage` reports `0` that means a line should be covered but wasn't covered/hit during execution.

Reasons why it might not get coverage is that the file might not have been loaded before SimpleCov ran, stuff that tries to smart load/cache things can also interfere.

It's hard to tell from over here without a code/application sample reproducing my sample. Although I should know better myself I produced errornous coverage myself as SimpleCov wasn't started before ANY file was loaded. I've also seen errornous behaviour because some library I won't mention here hardcore `load`'s code although it was `require`'d before -.-'

**Comment by NullVoxPopuli** [comment]
Well, in my rails app (which is closed source, unfortunately) I did adjust the autoload paths.

```ruby
    config.autoload_paths += Dir[Rails.root.join('app', 'models', '**')]
    config.autoload_paths += Dir[Rails.root.join('app', 'models', 'data', '**')]
```

I put all my AR models in data, because I wanted to separate the AR models from non-persisted models.

After my `SimpleCov.start do ..` block, I have `Rails.application.eager_load!` -- I get quite a few test failures without this.

**Comment by NullVoxPopuli** [comment]
So... after trying to replicate this in a sample project and failing -- when I was comparing my project to the `rails new` project, I noticed that the files were being required twice. 

so... I have a hunch that coverage was working all along, but the later requiring erased all the coverage stats.

All is well now. :-)

**Comment by PragTob** [comment]
sounds like some cause... if it works now all is well I hope :+1:

**Comment by NullVoxPopuli** [comment]
:+1:
