### ISSUE TITLE
Chat concerning roadmap

### ISSUE THREAD

**Issue by stevepeak** [colszowka/simplecov#577]
Hey @colszowka (or any other contributor) If you have a moment to chat concerning Simplecov's roadmap that would be great. I'm the founder of [Codecov](https://codecov.io) and we interests to make Simplecov better.

### Most common questions are:
1. When will Simpelcov support branch coverage?
2. When will Simplecov support partial line coverage?
3. Can Simplecov make `track_files` include all files by default?

Thank you for your time.

**Comment by PragTob** [comment]
Hi there,

I might be off with a couple of things but here we go:

1 & 2: Not likely to happen. simplecov builds on the standard library [coverage](https://ruby-doc.org/stdlib-2.4.0/libdoc/coverage/rdoc/Coverage.html) from Ruby. That just reports hits from executed per line, so branch coverage and partial line coverage are not within our reach.
3. Simplecov should take everything into account by default. It's specific [profiles](https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb) that add certain filters most of the tme unless I'm wrong atm.

Cheers,
Tobi

**Comment by stevepeak** [comment]
Thank you Tobi for your response.

It's unfortunate and surprising that the standard library is not getting attention. The value of branch and partial line coverage is quite valuable.

I personally have not had enough experience with Ruby and Simplecov to understand why/how files are missing from the reports. But it's a common question at Codecov - which makes us look bad because they think Codecov ignores them when in-fact Simplecov did not include them. The documentation on `Simplecov.track_files` is very light. 

Thank you

**Comment by colszowka** [comment]
Hi Steve,

1. and 2.: You'd have to talk to the ruby language maintainers, as we're 
merely users of the Ruby Standard Library coverage lib. I am not aware of 
any plans to extend that to branch coverage. If upstream supported it, I 
guess we could add it.
3. Please check the README: 
https://github.com/colszowka/simplecov/blob/master/README.md#default-root-filter-and-coverage-for-things-outside-of-it

If there are further questions I'd prefer to have those discussed here in 
the open, but maybe someone else on the team would be available?



Am 3. Mai 2017 8:45:30 nachm. schrieb Steve Peak <notifications@github.com>:

**Comment by PragTob** [comment]
@stevepeak `track_files` also really isn't an interface I think people should use most of the times, rather `add_filter` to EXCLUDE stuff not the other way around.

**Comment by colszowka** [comment]
Oh, Tobi is way too fast, dammit :)

But regarding point 3: The default in simplecov is to filter out anything 
outside your project root (see lib/simplecov/defaults.rb). If you install 
your dependencies within i.e. root/vendor/bundle using bundle install 
--path vendor you'd have all used gems included. If installed outside the 
project root, which is the usual default, you'd have to use that filters 
clearing I linked to.

**Comment by PragTob** [comment]
On open source tiem right now either way :dancer:

**Comment by stevepeak** [comment]
Thank you, you guys are awesome 👍

**Comment by PragTob** [comment]
@stevepeak btw. since the recently released 0.18 we support branch coverage, not certain if I'd make a lot of promises regarding the stability of the API though :)
