### ISSUE TITLE
Simplecov causes guard to not halt on fail

### ISSUE THREAD

**Issue by matrinox** [colszowka/simplecov#584]
This is part of the Guardfile I use
```ruby
group :red_green_refactor, halt_on_fail: true do
  guard :rspec, cmd: 'bundle exec rspec', all_on_start: true, all_after_pass: true, failed_mode: :keep do
    # ...
  end

  guard :rubocop, all_on_start: true, keep_failed: true, cli: ['-a', '--format', 'clang'] do
    # ...
  end
end
```

Before I added simplecov, if there were failed specs, it would stop (i.e. not run rubocop). After I added `SimpleCov.start` to `spec_helper.rb`, rubocop is run even when there are failed specs. The exit code is 1 in both cases.

Any idea why?

**Comment by PragTob** [comment]
Hi there!

We do some funky things at `at_exit` regarding to the exit code. That might mess with things, I don't have the time atm but I think I'd debug into this: https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L57-L88

Might also be a thing that guard-rspec gets somehow thrown off by something... but not sure, sorry :(

**Comment by matrinox** [comment]
@PragTob That's fine, I just wanted some pointers. This is very helpful to someone who hasn't touched much of your codebase. You commented on another one of my PRs https://github.com/colszowka/simplecov/pull/583#pullrequestreview-40759465 saying that I should create an issue first. Although that is for features, does this apply for bugs, too?

**Comment by PragTob** [comment]
@matrinox opening issues for bugs first is nice, so other people can see that there's a bug already reported. Also, sometimes bugs turn out to be features :dancer: So it's nice to do, but not as important as with features :) In general, you can of course make PRs without prior issues it might just end up in more work for you and us and maybe even unmerged PRs, and I hate to see people's good work not making it in :cry:

**Comment by matrinox** [comment]
@PragTob I don't mind :)

**Comment by PragTob** [comment]
@matrinox does this problem persist? I know we changed something around with exit statuses but we should always capture the relevant exit status and report it back "upstream"

**Comment by matrinox** [comment]
@PragTob I'm not sure, this has been a long time. We can close this issue for now

**Comment by PragTob** [comment]
Okidokes, thanks!
