### ISSUE TITLE
Run CI with frozen-string-literals enabled

### ISSUE THREAD

**Issue by PragTob** [colszowka/simplecov#592]
As mentioned in #590 and should probably also be applied to simplecov-html. I'm not 100% sure if we should just run all 2.4+ with this seeting or if we should run 2.4 with both. As we also CI against 2.3 etc. without the setting it should be ok though.

@pat mentions how to do this:

> I would recommend adding the following to your .travis.yml file to ensure regressions aren't introduced:

```yml
before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
```

>This will add the flag when the tests are run on MRI 2.4 or newer (while the feature was introduced in 2.3, it doesn't seem to work reliably until 2.4). However, at this point in time for the tests to pass, you'll need to use the latest RSpec commits, along with submitted patches to simplecov-html, test-unit, and parser (for rubocop):
> * https://github.com/colszowka/simplecov-html/pull/56
> * https://github.com/test-unit/test-unit/pull/149
> * https://github.com/whitequark/parser/pull/354

**Comment by pat** [comment]
Regarding the dependencies: obviously, `simplecov-html` is now sorted (at least in git), and test-unit's 3.2.5 release is frozen-string-literal friendly as well.

Parser is trickier, as it depends on `racc`, which isn't yet happy about frozen string literals. There are existing PRs there (made in January), but the test suite isn't green and I've not been able to figure out why.
https://github.com/tenderlove/racc/pull/80
https://github.com/tenderlove/racc/pull/81

**Comment by PragTob** [comment]
We enforce the pragma comments on freezing strings so I believe this is good enough as we make sure it works for our project.
