### ISSUE TITLE
Test failed. Because each processing's coverage is not fine. But total coverage was fine.

### ISSUE THREAD

**Issue by kouyaf77** [colszowka/simplecov#593]
Is it possible to check only total coverage?
I'm using  `simplecov (0.14.1)` and `parallel_tests (2.14.1)`

```
[...]

Coverage report generated for RSpec:248423 to /vagrant/Source/Rails/xxx/coverage. 3741 / 10680 LOC (35.03%) covered.
Coverage (35.03%) is below the expected minimum coverage (80.00%).

[...]

Coverage report generated for RSpec:248423, RSpec:248434 to /vagrant/Source/Rails/xxx/coverage. 4929 / 8455 LOC (58.3%) covered.
Coverage (58.30%) is below the expected minimum coverage (80.00%).

[...]

Coverage report generated for RSpec:24838, RSpec:248423, RSpec:248434 to /vagrant/Source/Rails/xxx/coverage. 5572 / 7620 LOC (73.12%) covered.
Coverage (73.12%) is below the expected minimum coverage (80.00%).

[...]

Coverage report generated for RSpec:24838, RSpec:248423, RSpec:248434, RSpec:248472 to /vagrant/Source/Rails/xxx/coverage. 6176 / 7127 LOC (86.66%) covered.
Tests Failed

3340 examples, 0 failures, 22 pendings
```

**Comment by PragTob** [comment]
Ugh. If it doesn't do it with this setting then no it probably isn't possible atm (to the best of my knowledge) :|

That said, I wanted to enable & use that setting on our own CI and we are also running with parallel_tests. So I might have to fix that either way... still if you have a PR/idea I'd be glad to have it :D

**Comment by PragTob** [comment]
It seems the problem was brought up before as part of #559 and there seems to be a workaround as per [this comment](https://github.com/colszowka/simplecov/issues/559#issuecomment-280805651)

**Comment by kouyaf77** [comment]
@PragTob 
I see. Thanks a lot.
I'm going to refer [this comment](https://github.com/colszowka/simplecov/issues/559#issuecomment-280805651)
