### ISSUE TITLE
skiping swagger documentation  

### ISSUE THREAD

**Issue by raulperezalejo** [colszowka/simplecov#596]
My swagger documentation looks like not covered. I would like to skip this code from my controllers, 
Is there any way to do this? 

thanks

**Comment by PragTob** [comment]
You can [skip code](https://github.com/colszowka/simplecov#ignoringskipping-code), you could apply that to your controller. Is that what you're looking for? :)

**Comment by PragTob** [comment]
Closing due to no further feedback
