### ISSUE TITLE
Spring doesn't share coverage from devise_for with rspec?

### ISSUE THREAD

**Issue by bobmazanec** [colszowka/simplecov#597]
Simplecov 0.14.1
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Rails 5.0.3
```
coffee-rails (4.2.2, 4.2.1)
factory_girl_rails (4.8.0, 4.7.0)
jquery-rails (4.3.1, 4.2.1)
rails (5.0.3, 5.0.0.1)
rails-dom-testing (2.0.3, 2.0.1)
rails-html-sanitizer (1.0.3)
rails-i18n (5.0.4, 4.0.2)
rails_12factor (0.0.3)
rails_autolink (1.1.6)
rails_serve_static_assets (0.0.5)
rails_stdout_logging (0.0.5)
rspec-rails (3.6.0, 3.5.2)
sass-rails (5.0.6)
slim-rails (3.1.2, 3.1.1)
sprockets-rails (3.2.0)
```

Spring 2.0.2
```
spring (2.0.2, 1.7.2)
spring-commands-rspec (1.0.4)
spring-watcher-listen (2.0.1, 2.0.0)
```

While tracking down this issue, I run `spring stop; spring rspec <args>`

`config/spring.rb` and `spec/rails_helper.rb`:
```
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
end
```

`.simplecov`:

    SimpleCov.start 'rails'

The project uses devise-neo4j; `devise_for :users` in `config/routes.rb` causes `models/user.rb` to load fairly early.

I see `coverage/.resultset.json` getting written fairly early in my test run showing coverage for `user.rb`'s load. When the run finishes, the `user.rb` coverage shows only the run time code (e.g., method bodies)&mdash;not the load-time code.

Running `spring stop` re-writes `coverage/.resultset.json` with `models/user.rb` load-time coverage, suggesting the spring process has it, but somehow isn't passing it to rspec?

I have also tried it without `.simplecov`, running `SimpleCov.start` directly in `spring.rb` and `rails_helper.rb`&mdash;same behavior.

Thoughts or suggestions?
TIA

**Comment by PragTob** [comment]
:wave: 

Sadly not really no, Spring has caused me (+ co-workers) enough pain and anger that it's deactivated on all projects I work on. It's likely that the spring process has it, and it's only written when a process exits (so it doesn't pass it to rspec).

You could put a couple of puts in to see when the user code is loaded versus when simplecov is started. Also, have you [adjusted the setup for spring](https://github.com/colszowka/simplecov#want-to-use-spring-with-simplecov) ?

**Comment by bobmazanec** [comment]
Yes, I started with that and then some somewhat-educated variations before asking.

My current workaround is to surround User model's execute-on-load code in the with `# :nocov`s (including, `def <name>`s and matching `end`s, but not the chewy, executable centers 😄 ) while I figure out if I want to disable Spring.

Thanks for the answer and everyone's contributions to Simplecov!

**Comment by PragTob** [comment]
I'm gonna close this out as we have a lot of spring problems and it's clear something needs to be done with the docs for it or it in general and this seems to be a problem with it like any ohter.

If you disagree please let me know and we can reopen :)
