### ISSUE TITLE
devise model 0% coverage

### ISSUE THREAD

**Issue by juanbrein** [colszowka/simplecov#599]
Running minitest on rails 5.1.2. Spring is not enabled and simplecov start is at the very beginning of application_system_test_case.rb:

![image](https://user-images.githubusercontent.com/2943422/28262661-23614df0-6ae4-11e7-80ad-d1e74af81996.png)

![image](https://user-images.githubusercontent.com/2943422/28262682-350355a8-6ae4-11e7-8eb0-a6e45b3b7f83.png)

Code is tested using unit and integration tests, so this code is definitely running

**Comment by PragTob** [comment]
:wave: 

You say it is at the beginning of "application_system_test_case.rb" - I'm not very familiar with the new rails system tests, but OAuth code usually is hard to E2E test. So I guess it's done in Unit tests and unit tests shouldn't require your system case unit case, so simplecov also (or even firstly) needs to be started in the test_helper that you call for your minitest tests.

**Comment by juanbrein** [comment]
Moved it to test_helper.rb

![image](https://user-images.githubusercontent.com/2943422/28307085-f65cfebc-6ba1-11e7-919b-c2b0fbffe57f.png)

Same results:

![image](https://user-images.githubusercontent.com/2943422/28307099-02d67ae2-6ba2-11e7-82e1-2030c1d85003.png)

**Comment by PragTob** [comment]
Looks a bit like the class is loaded before simplecov is started. Otherwise at least the class definition should be covered.

What test command do you run?

Could you add a `puts "Simplecov"` after simplecov was started and a `puts "User loaded"` at the top of your user class file or inside the user class, I'd bet the one in the user class appears so simplecov isn't started first :)

**Comment by juanbrein** [comment]
Yey now is working! Great tip on printing outputs as things gets loaded. I ended up using `config/initializers/simplecov.rb` as this:

![image](https://user-images.githubusercontent.com/2943422/28308286-02f97c6e-6ba6-11e7-8a48-67d72fa93c36.png)

Thank you
