### ISSUE TITLE
Covered code shown as skipped

### ISSUE THREAD

**Issue by bikashp** [colszowka/simplecov#60]
I'm using ruby 1.9.2-p180, simplecov gem 0.4.2.

Though, i've written test for my model methods, simple coverage html file shows all of them as missed lines. This has happened only in few of my models and not all.

**Comment by StellarDoor5319** [comment]
I'm also having this problem. Check out https://github.com/StellarDoor5319/casualdate to see the repo with problems. Coverage is at https://www.codacy.com/app/StellarDoor5319/casualdate/file/12657786485/coverage?bid=5931021&fileBranchId=5931021.

**Comment by tomasmetroy** [comment]
To anyone still struggling with this (using test/unit library and running the tests with rake):

- at the very beginning of your Rakefile: require 'rake/testtask'  
- right underneath that: 
Rake::TestTask.new("test:all") do |t|
      t.libs = ["lib"]
      t.warning = true
      t.test_files = FileList['test/**/*_test.rb']
end

- then run the tests with: rake test:all
