### ISSUE TITLE
Coverage report generated before test suite is finished in rails 5.1.3

### ISSUE THREAD

**Issue by mvanduijker** [colszowka/simplecov#602]
After upgrading rails from 5.1.2 to 5.1.3 coverage report is generated before test suite is finished. Resulting in an incomplete report.

Using ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

Rolling back to 5.1.2 makes everything work again. Willing to submit a PR but have no clue where to look.

**Comment by bf4** [comment]
Rails changelog?  Is there something specific that doesn't finish? Like just system tests?

**Comment by PragTob** [comment]
What test command do you execute? `rspec spec` / `rake something` ? Results are generated on exit of the process so if for some reason the process exited before and then tests are run that'd be a potential source.

A sample project would help to figure this out although not sure I got the time :)

**Comment by mvanduijker** [comment]
I am using out of the box minitest and just use `rails test`. Will try to make a sample project when I got time.

Screenshots of my console:
![image](https://user-images.githubusercontent.com/1771206/28979831-9559a23e-794b-11e7-98aa-751c1d54877b.png)

Seems to think it exited, while still running.

**Comment by mvanduijker** [comment]
I found out, my mistake.

I `require "minitest/autorun"` before `require "simplecov"` in `test_helper.rb` which worked in rails 5.1.2
requiring minitest/autorun after simplecov fixed it.

**Comment by PragTob** [comment]
Yup, always require `simplecov` first :) Glad you solved it!
