### ISSUE TITLE
include a gem in your coverage

### ISSUE THREAD

**Issue by mathieujobin** [colszowka/simplecov#606]
Hey there,

say your app uses a in-house gem, called `goo`
and my app is closely tied to this gem, although it still make sense to make it a separate gem.

so I would like my coverage to include the gem source.

is there a way through simplecov config to just include that gem easily?

thanks

**Comment by PragTob** [comment]
I think [track_files](http://www.rubydoc.info/gems/simplecov/SimpleCov/Configuration:track_files) should work. At the very least, you can run `bundle install --path some_directory` [[doc]($ bundle install --path vendor/bundle)] to include all gems in your current working directory and then add a filter for all other gem paths, `track_files` should work though and be the better solution

**Comment by mathieujobin** [comment]
thanks, this is a very good solution
