### ISSUE TITLE
Ruby 2.4.1 p111 gives "Gem Not Found" Error

### ISSUE THREAD

**Issue by sqlandfriends** [colszowka/simplecov#612]
Hello as in topic I have Ruby 2.4.1p and there is problem installing SimpleConv: "Gem not found" error shows up every time I try to install it.

Is there any workaround? 
btw. I need it for RubyMine IDE.

Rergards, Horacy.

**Comment by PragTob** [comment]
so um, it just fixed itself?

**Comment by lucasdavid** [comment]
I'm having the same problem. Could you please tell me how did you manage to fix this?

**Comment by PragTob** [comment]
@lucasdavid can you please let me know what you do? does `gem install simplecov` not work?

**Comment by lucasdavid** [comment]
Okay, thank you! That did work out! I was having problems because I tried the following:

1. I added `gem 'simplecov', '~> 0.16.1'` inside my Gemfile, under the test group:
    ```rb
    group :test do
      # some other stuff...
      gem 'simplecov', '~> 0.16.1'
    end
    ```

2. Then I ran `bundle install`:
    ```shell
    ldavid@...:{a nice path here}$ bundle install
    Fetching source index from https://gems.contribsys.com/
    Fetching source index from https://gems.contribsys.com/
    Fetching gem metadata from https://rubygems.org/..........
    Fetching source index from https://rubygems.org/
    Resolving dependencies...
    Using rake 12.3.1
    Using concurrent-ruby 1.0.5
    # Some lines omitted...
    Using jbuilder 2.7.0
    Fetching json 2.1.0
    Installing json 2.1.0 with native extensions
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
        current directory: {myhome}/.rvm/gems/ruby-2.4.1/gems/json-2.1.0/ext/json/ext/generator
    {myhome}/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20180614-14286-s142ku.rb extconf.rb
    creating Makefile
    
    current directory: {myhome}/.rvm/gems/ruby-2.4.1/gems/json-2.1.0/ext/json/ext/generator
    make "DESTDIR=" clean

    current directory: {myhome}/.rvm/gems/ruby-2.4.1/gems/json-2.1.0/ext/json/ext/generator
    make "DESTDIR="
    compiling generator.c
    linking shared-object json/ext/generator.so
    /usr/bin/x86_64-linux-gnu-ld: cannot find -lgmp
    collect2: error: ld returned 1 exit status
    Makefile:257: recipe for target 'generator.so' failed
    make: *** [generator.so] Error 1

    make failed, exit code 2

    Gem files will remain installed in {myhome}/.rvm/gems/ruby-2.4.1/gems/json-2.1.0 for inspection.
    Results logged to
    {myhome}/.rvm/gems/ruby-2.4.1/extensions/x86_64-linux/2.4.0/json-2.1.0/gem_make.out

    An error occurred while installing json (2.1.0), and Bundler cannot continue.
    Make sure that `gem install json -v '2.1.0'` succeeds before bundling.

    In Gemfile:
      simplecov was resolved to 0.16.1, which depends on
        json
    ```

I'm not sure which logs to give you, but I have ruby 2.4.1p111 installed through RVM.

**Comment by PragTob** [comment]
Hi there, this is a problem with installing the `json` gem (which is a dependency of simplecov) so not a problem with simplecov itself.

**Comment by lucasdavid** [comment]
Although I do understand this problem happens when installing json in 2.4, I found a very old issue where people were having the same problem as me: #544.
I'm just confused on why `bundle install` doesn't work while `gem install simplecov` does.

**Comment by PragTob** [comment]
@lucasdavid chances are your Gemfile.lock specifies a different `json` version than `gem install simplecov` installs. You can try `bundle update json`
