### ISSUE TITLE
SimpleCov not reporting coverage for lines in application_controller tested with an anonymous controller helper.

### ISSUE THREAD

**Issue by erlandsona** [colszowka/simplecov#619]
Ideally coverage would be reported against the lines where after_sign_in_path_for if defined in application_controller.rb currently that's not the case.

I'm wondering if there might be a good starting place in the gem source to dig around to see why it might not be reporting coverage for these tests?

* Include the SimpleCov version you are running in your report.
    * `/box/gems/simplecov-0.15.0`

* Include your ruby -e "puts RUBY_DESCRIPTION".
    * `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]`

* Please also specify the gem versions of Rails (if applicable).
    * `/box/gems/rails-4.0.4`

* Include any other coverage gems you may be using and their versions.
    * `/box/gems/rspec-core-3.3.2`
    * `/box/gems/rspec-rails-3.3.3`

* Include how you run your tests and which testing framework or frameworks you are running.
    * `docker-compose run web bundle exec rspec spec/controllers/application_controller_spec.rb`

Otherwise, please ensure you are requiring and starting SimpleCov before requiring any application code. For example, if running via RSpec, this would be at the top of your spec_helper. ✔️

SAMPLE (LEGACY?) CODE
```ruby
describe ApplicationController do
  # Setup Anonymous Controller for testing
  controller do
    def after_sign_in_path_for(resource)
      super resource
    end
  end

  it { is_expected.to use_before_filter :authenticate_user! }

  describe 'Devise::Controllers::Helpers#after_sign_in_path_for' do
    before
      expect_any_instance_of(ApplicationController).to receive(:sign_out).once
      expect_any_instance_of(ApplicationController)
        .to receive(:new_user_session_path).once.and_call_original

      sign_in user
      @result = controller.after_sign_in_path_for user
    end

    it { expect(@result).to eq "/users/sign_in" }
  end
end
```

**Comment by PragTob** [comment]
Hi there,

Thanks for the report 🎉 

I'm not quite sure where you are missing coverage right now. Is it in the anonymous controller you define above? Mixing spec files with actual code to be covered might be a problem. It's also weird that your spec file doesn't end in `_spec.rb` I also can't see where simplecov is started here (the spec should require the spec/rails_helper that takes care of this). 

A good place to start digging is if the [standard library coverage](https://ruby-doc.org/stdlib-2.4.1/libdoc/coverage/rdoc/Coverage.html#method-c-start) reports the coverage if started in place of simplecov, because that's what simplecov relies upon.

**Comment by erlandsona** [comment]
Thank you for your response. Allow me to clarify. 
The goal is to see coverage for `app/controllers/application_controller.rb` given a spec @ `spec/controllers/application_controller_spec.rb`

> RE: Spec file doesn't end in `_spec.rb`.
- I mistyped it in my first comment. Sorry for any confusion it caused.

> RE: Mixing spec files with actual code.
- It's effectively a mock controller that inherits from application controller. It would be the same as testing an actual controller inheriting from `ApplicationController`.
Here's a [link to the technique](https://stackoverflow.com/a/6658312)
Here's the [corresponding rspec docs](https://relishapp.com/rspec/rspec-rails/v/3-3/docs/controller-specs/anonymous-controller)

I have these lines at the top of `spec/spec_helper.rb`
```ruby
require 'simplecov'
SimpleCov.start 'rails'
```
The top of my `spec/rails_helper.rb` looks so:
```ruby
# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'spec_helper'
require 'rspec/rails'
```

And my `.rspec` file has these flags set
```
--color
--require rails_helper
```

Also, I tried following the console commands for the [standard library coverage reports](https://ruby-doc.org/stdlib-2.4.1/libdoc/coverage/rdoc/Coverage.html#method-c-start) and I'm not sure what I'm supposed to be looking for. Here's what I got.
```ruby
❯ docker-compose run --service-ports web bundle exec rails c
Loading development environment (Rails 4.0.4)
irb(main):001:0> require 'coverage'
=> true
irb(main):002:0> Coverage.start
=> nil
irb(main):003:0> require 'app/controllers/application_controller.rb'
LoadError: cannot load such file -- app/controllers/application_controller.rb
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `block in require'
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
        from (irb):3
        from /box/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
        from /box/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
        from /box/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
irb(main):004:0> Coverage.result
=> {}
irb(main):007:0> Coverage.start
=> nil
irb(main):008:0> require 'spec/controllers/application_controller_spec.rb'
LoadError: cannot load such file -- spec/controllers/application_controller_spec.rb
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `block in require'
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /box/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
        from (irb):8
        from /box/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
        from /box/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
        from /box/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
irb(main):009:0> Coverage.result
=> {}
```

**Comment by PragTob** [comment]
Hi, about coverage first - you are getting load errors when requiring the files. that way, of course no coverage can be measured.

Please also load and start simplecov before loading and starting ANYTHING else. I.e. it should be on top of your rails_helper. If your application controller gets loaded before simplecov is started, nothing will be seen.

**Comment by erlandsona** [comment]
Got it. Alright here's the top of my `rails_helper.rb`
```
require 'simplecov'
SimpleCov.start 'rails'
# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'spec_helper'
require 'rspec/rails'
```

I thought because the README mentioned starting SimpleCov at the top of Spec Helper and because my spec_helper was required above rspec that I was good.

I realize the docs are also specific about those lines being added before any Rails code is loaded.

Forgive me for not realizing it was probably this line
`require File.expand_path('../../config/environment', __FILE__)`
That was loading the rails application code.

It's working now! Thank you so much for your help!

**Comment by alexandroid** [comment]
Just to comment for other people who may stumble on this issue. If your project has both `spec/rails_helper` and `spec/spec_helper` - make sure SimpleCov initialization happens in `rails_helper` as it is invoked first.
