### ISSUE TITLE
Could not find docile-1.1.5 in any of the sources

### ISSUE THREAD

**Issue by alessandroarioli** [colszowka/simplecov#629]
Hi!
I've a problem bundling this gem.
We are using Rails 5.1 with Ruby 2.3.1, when i bundle locally on my mac the gem installation gone successfully, but on the CI with command

`bundle install --deployment --path vendor/bundle`

produces this error on docile gem dependency:

`Could not find docile-1.1.5 in any of the sources`

Any thoughts?
Thank you!

**Comment by PragTob** [comment]
Hi there,

no idea as `docile` is readily available on rubygems as [1.1.5](https://rubygems.org/gems/docile/versions/1.1.5).

So, I'd guess that you might be hitting one/few of the gotchas for [bundler deployment mode](http://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE)

I.e. don't think anything we can do from here :)
