### ISSUE TITLE
require "ostruct"

### ISSUE THREAD

**Issue by timpwbaker** [colszowka/simplecov#632]
I am using Simple Cov with RSpec on a small ruby CLI that parses cron strings. 

Versions:
simplecov (0.15.1, 0.13.0, 0.12.0)
simplecov-html (0.10.2, 0.10.0)

I use an OpenStruct in part of my code and I forgot to `require "ostruct"`. My tests ran green and the code using OpenStruct is well tested. 

However when I attempted to run the application 'as a user' from the command line I receive a `uninitialized constant CronParser::OpenStruct` error. I have added `require "ostruct"` and all is well again. Obviously my error.

I initially thought this was RSpec itself, but some digging revealed that removing Simple Cov causes the test to fail as they should. 

I am sure this is quite niche, but as it causes tests to pass when they shouldn't I thought it worth sending over. 

Example:
https://github.com/timpwbaker/roocron/blob/master/lib/cron_parser.rb

Remove `require "ostruct"` from the second line and run 
`rspec spec/cron_parser_spec.rb:39`

It will pass when it shouldn't. To see it fail:
`ruby bin/cron_parser.rb "*/15 0 1,15 * 1-5 /usr/bin/find"`

Thanks for a really helpful tool.
Tim

**Comment by PragTob** [comment]
Hi there,

thanks for the report. Unfortunately that's how it is in the ruby world. One gem requires a stdlib/gem/whatever et voila it is required everywhere. Getting rid off this property is quite hard, it'd mean no gem ever could use the standard library and I don't believe we want that :)

Also secondly, as far as I can tell simplecov isn't (directly) the culprit but rather the `json` library we use.

Thanks for the report but I don't think there's anything we can do here :(

**Comment by tb99022** [comment]
Ah ok, that's cool. I assumed it was something like that. Thanks for the quick response.

TB

**Comment by timpwbaker** [comment]
Ah ok, that's cool, I assumed it was something like that. Thanks for the quick response. TB
