### ISSUE TITLE
SimpleCov ignore some files for no reasons. Require at the top.

### ISSUE THREAD

**Issue by nanark** [colszowka/simplecov#640]
SimpleCov ignore some files (0%) when others are successfully covered (100%) with the same tests.

I run my tests with the framework's testing tools (`rails t`).

Rails 5.1.4
SimpleCov 0.15.1

This is my `test_helper.rb` file.

    require 'simplecov'
    
    # save to CircleCI's artifacts directory if we're on CircleCI
    if ENV['CIRCLE_ARTIFACTS']
      dir = File.join(ENV['CIRCLE_ARTIFACTS'], 'coverage')
      SimpleCov.coverage_dir(dir)
    end
    
    SimpleCov.start 'rails'
    
    ENV['RAILS_ENV'] ||= 'test'
    require File.expand_path('../../config/environment', __FILE__)
    require 'rails/test_help'

This is a **file successfully covered (100%)** by SimpleCov with a `Connection.types` :

    class Connection < ApplicationRecord
      validates :type_of, inclusion: { in: proc { Connection.types.map(&:to_s) } }
    
      TYPES = %i[
        friend
        industry
        investor
      ].freeze
    
      belongs_to :project
      belongs_to :user
    
      def self.types
        TYPES
      end
    end

This is a **file unsuccessfully covered (0%)** by SimpleCov with `Kpi.types`:

    class Kpi < ApplicationRecord
      REGEX = {
        float: "^\d+(\.?\d)?$"
      }.freeze
    
      TYPES = [
        { id: :buyers, name: 'Number of buyers', unit: 'users', example: '1000', regex: :float },
        { id: :sellers, name: 'Number of sellers', unit: 'users', example: '1000', regex: :float },
      ].freeze
    
      belongs_to :project
    
      def self.types
        TYPES
      end
    end

![capture d ecran 2017-11-08 a 21 32 12](https://user-images.githubusercontent.com/581768/32592360-a597a212-c523-11e7-97ed-365e0eb4c3d7.png)

**Comment by PragTob** [comment]
Hi there,

thanks for the bug report. Could you to me a favor and just put `puts "being loaded"` in the uncovered file right before the `class` definition and a `puts "starting simplecov"` right before you start simplecov and then make sure that the `starting simplecov` message appears before the other? I'm afraid there might be some magic going on that requires the other files before simplecov actually starts :)

**Comment by nanark** [comment]
Ok it's weird.

```
>>> Kpi Class loaded (test 3)
Running via Spring preloader in process 2978
>>> Starting simplecov
Run options: --seed 15588

# Running:

>>> Like Class loaded
>>> Connection Class loaded
">>> Testing Kpi"
">>> Testing Connection"
....
```

The Kpi Class is loaded before. And the line only appear when I change the file, then it seems to be cached. If I run my test twice with no change, the `Kpi Class loaded` puts disappear.

**Comment by nanark** [comment]
These are my Test env values:
```
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false
  config.action_dispatch.show_exceptions = false
  config.action_controller.allow_forgery_protection = false
  config.action_mailer.perform_caching = false
  config.action_mailer.delivery_method = :test
  config.active_support.deprecation = :stderr
```

**Comment by nanark** [comment]
Ok, found the culprit: ActiveAdmin.

I added a filter:
```
SimpleCov.start 'rails' do
  add_filter('/admin')
end
```

And it works fine now. Thanks!

**Comment by nanark** [comment]
Added this around AA routes. It ain't pretty but it works.
```
unless Rails.env.test?
```

**Comment by PragTob** [comment]
activeadmin does some funky things with hardcore loading files :|

Spring can also be the culprit [see the README section thoug](https://github.com/colszowka/simplecov#want-to-use-spring-with-simplecov)

As there's not much for us to do here, closing.

**Comment by nanark** [comment]
It's kind of random actually...
With no major change (some minor changes of double quotes to single quotes), I go from 36 to 21%.
If I add a space char on the routes.rb file, it goes up to 36% again. 

![capture d ecran 2017-11-09 a 16 43 58](https://user-images.githubusercontent.com/581768/32614303-41eaaa8a-c56d-11e7-8996-96a6140b5cb8.png)

At least CodeClimate got it right every time :)

**Comment by nanark** [comment]
How can I have different results with no changes ?

**Comment by PragTob** [comment]
that's probably some race condition or in terms of spring it most likely depends on when spring decides to reload or not reload something or whatever - spring has cost me enough time in my life that I deactivate it by default in new Rails projects :)

**Comment by nanark** [comment]
Haha, I see. But I don't load the Spring gem in the test Env, and I don't think CodeClimate is running it either.

```
group :development do
  gem 'listen', '~> 3.0.5'
  gem 'rubocop', '~> 0.51.0', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

```
