### ISSUE TITLE
Reporting uncovered lines even though they are definitely covered

### ISSUE THREAD

**Issue by erijonhson** [colszowka/simplecov#641]
Hello, my problem is the same of the others, but nothing fix it. 

I'm using ruby `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`, `rails 5.0.6` and `simplecov 0.15.1`. 

![image](https://user-images.githubusercontent.com/10831613/32861365-35f7370a-ca33-11e7-9b4c-4ed20e96ef06.png)

![image](https://user-images.githubusercontent.com/10831613/32861438-6d223162-ca33-11e7-934f-8d7d7d3a2fb3.png)

Any advice?
Before you go ahead please search existing issues for your problem, chances are someone else already reported it.

**Comment by erijonhson** [comment]
https://github.com/erijonhson/help-students

**Comment by PragTob** [comment]
Please read the README. It is mentioned multiple times that you should require simplecov before everything else, [which you don't do](https://github.com/erijonhson/help-students/blob/master/spec/rails_helper.rb).

Feel free to reopen if this doesn't fix it. Good luck.

**Comment by erijonhson** [comment]
I did this but it still does not work.
In fact, the other modules are well analyzed, this is the only one that shows problems: 
![image](https://user-images.githubusercontent.com/10831613/32894576-f15f0396-cabb-11e7-8bdd-88c122958439.png)

**Comment by erijonhson** [comment]
I gave up using spring for test coverage. I only do `bundle exec rspec` and everything works fine.

**Comment by PragTob** [comment]
the README also has a section for working with spring, but yeah generally speaking it's harder to do with it
