### ISSUE TITLE
Add branch coverage indication (ruby 2.5)

### ISSUE THREAD

**Issue by damienlethiec** [colszowka/simplecov#645]
Ruby 2.5 introduces a branch coverage feature (https://bugs.ruby-lang.org/issues/13901) which would be really useful to include in simplecov. I hope I did not miss it but I do not think it is the case yet.

Thanks a ton :)

**Comment by PragTob** [comment]
There is an old issue about this where we already discussed the first things - while yes, we definitely want to do this my time is sadly cut short and right now I sadly don't see myself working on this too soon as it's quite the effort.

**Comment by damienlethiec** [comment]
Sorry, I looked for it but did not see the old issue. I gonna keep this in my to do list and see if I can find the time to tackle it in the next months if it is ok with you :)

Merry Christmas!

**Comment by joecabezas** [comment]
Hello, there is any update on this?, thanks
