### ISSUE TITLE
Report file format description

### ISSUE THREAD

**Issue by Pawamoy** [colszowka/simplecov#657]
Hi :wave:! 

I was searching online for documentation about coverage reports format standards or specifications, and I was surprised not to find any. It seems everybody uses its own format and its own tools to generate HTML (or else) reports.

I see that you write partial results in coverage_path/.resultset.json. What is the format of these files? When merging them, is it still the same format?

Could you point me to or add a section in the documentation explaining your result file format? A bit like [Istanbul's one](https://github.com/gotwarlost/istanbul/blob/master/coverage.json.md)?

**Comment by PragTob** [comment]
Hi @Pawamoy !

The `.resultset.json` is an implementation detail about how we handle synchronization between multiple test processes (among other things). It is **not** meant as a file for public consumption. See [this comment](https://github.com/colszowka/simplecov/pull/637#issuecomment-340076405). It's much preferred to write you own formatter, that way you can write it (easily) in any way you want or use any of the existing formatters.

**Comment by Pawamoy** [comment]
Alright I see, so if at some point a standard for coverage report format emerges, then all we have to do is write a formatter for it! Works for me, thanks :)
