### ISSUE TITLE
Ruby send calls not covered incorrectly

### ISSUE THREAD

**Issue by rhuanbarreto** [colszowka/simplecov#659]
I'm running the following code on Rails 5.0:

```ruby
#/app/controllers/application_controller.rb
def get_query_cache(model, method)
    Rails.cache.fetch("#{model.name}-#{method}", expires_in: 24.hours) do
      model.send method
    end
end
```
Then I call the following:
```ruby
#/app/controllers/category_controller.rb
def index
    @articles = get_query_cache(Article, :custom_method)
end
```
In the code coverage report the custom_method is showed as not covered even though it was called.

Configuration:
```ruby
#/config/environments/test.rb
config.action_controller.perform_caching = false
```
### Environment Description
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-darwin16]
rails (5.0.6)
minitest (= 5.10.3)
minitest-reporters
simplecov (0.15.1)
simplecov-cobertura (1.3.0)
simplecov-html (0.10.2)

**Comment by rhuanbarreto** [comment]
Just after some investigation, on the HTML report, some lines appear as not covered but on the cobertura report that I read on Jenkins the lines are covered!

So is that a bug on the HTML reporter?

**Comment by bf4** [comment]
@rhuanbarreto how are you running your tests?  code is considered covered if and only if it was evaluated after simplecov starts.

**Comment by rhuanbarreto** [comment]
On the test_helper.rb

```ruby
require 'simplecov'
require 'simplecov-cobertura'
SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::CoberturaFormatter
])
SimpleCov.start
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'minitest/autorun'
require "minitest/reporters"
Minitest::Reporters.use! [
    Minitest::Reporters::SpecReporter.new, 
    Minitest::Reporters::JUnitReporter.new
]

class ActiveSupport::TestCase
end
```

And it's required in the top of each test file. `require 'test_helper'`

The problem is not anymore about codecov covering or not covering. It is running well. But the HTML formatter is reporting less coverage than coverage from Cobertura formatter in the same test result.

HTML Formatter - 2788/3092 lines covered
Cobertura Formatter - 2817/3092 lines covered

**Comment by rhuanbarreto** [comment]
In the HTML formatter, the send methods are uncovered. On the Cobertura formatter are covered. I'm sure that the code is covered. So the HTML formatter is not getting the right result but the Cobertura formatter yes

**Comment by bf4** [comment]
And the result.json (in the coverage folder) is the same but the formatters generate different reports?

BTW, in my experience, Minitest and simplecov don't always play nice since they both run in `at_exit` hooks.  Are you running your tests with Rake?

**Comment by rhuanbarreto** [comment]
No. Running the tests as `rails test` command. How should I run it?

It's really weird. Now both results are the same (HTML and Cobertura reports). But running locally and on Jenkins give different results.

In Jenkins there are more lines covered than local.

Follow below the test stage from Jenkinsfile:
```groovy
    stage('Test Code') {
      docker.image('rhuan/ruby-freetds:2.3').inside('-v bundle_cache:/vendor/bundle') {
        withEnv(["RAILS_ENV=test"]) {
          try {
            sh 'bundle install --path /vendor/bundle'
            sh 'rails db:migrate'
            sh 'rails test'
          } catch(err) {
          } finally {
            junit 'test/reports/*.xml'
            cobertura(
              autoUpdateHealth: false,
              autoUpdateStability: false,
              coberturaReportFile: 'coverage/coverage.xml',
              conditionalCoverageTargets: '70, 0, 0',
              failUnhealthy: false,
              failUnstable: false,
              lineCoverageTargets: '80, 0, 0',
              maxNumberOfBuilds: 0,
              methodCoverageTargets: '80, 0, 0',
              onlyStable: false,
              sourceEncoding: 'ASCII',
              zoomCoverageChart: false)
            publishHTML(target: [
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: true,
              reportDir: 'coverage',
              reportFiles: 'index.html',
              reportName: 'Test Coverage'
            ])
          }
        }
      }
    }
```

**Comment by PragTob** [comment]
@rhuanbarreto if you run locally with `rails test` then it's more likely that you have `spring` inbetween and it's not easy for simplecov to play nicely with spring. That might be the reason these 2 are so different (jenkins probably has nothing preloaded)

**Comment by PragTob** [comment]
Or in other words, has anything changed or was updated here on your side?

**Comment by rhuanbarreto** [comment]
As the cobertura file was correct I ended up relying on Jenkins results rather than the HTML report.
