### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by slur7** [colszowka/simplecov#677]
Howdy! Thanks for reporting an issue <3

Before you go ahead please search existing issues for your problem, chances are someone else already reported it.

To make sure that we can help you quickly please include and check the following information:

 * Include how you run your tests and which testing framework or frameworks you are running.
    - please ensure you are requiring and starting SimpleCov before requiring any application code.
    - If running via rake, please ensure you are requiring SimpleCov at the top of your Rakefile
      For example, if running via RSpec, this would be at the top of your spec_helper.
    - Have you tried using a [`.simplecov` file](https://github.com/colszowka/simplecov#using-simplecov-for-centralized-config)?
 * Include the SimpleCov version you are running in your report.
 * If you are not running the latest version (please check), and you cannot update it,
   please specify in your report why you can't update to the latest version.
 * Include your `ruby -e "puts RUBY_DESCRIPTION"`.
 * Please also specify the gem versions of Rails (if applicable).
 * Include any other coverage gems you may be using and their versions.

Include as much sample code as you can to help us reproduce the issue. (Inline, repo link, or gist, are fine. A failing test would help the most.)

This is extremely important for narrowing down the cause of your problem.

Thanks!

**Comment by PragTob** [comment]
hi, this is basically our issue template so I'm just closing :) If that was a mistake but you wanted to open something else, please make a new issue.
