### ISSUE TITLE
minimum coverage rounds preventing checking real 100%

### ISSUE THREAD

**Issue by gleseur** [colszowka/simplecov#679]
Hello,

We enforce 100% coverage (so we expecter every line to be covered) on our apps but after a certain number a lines, the minimum coverage passes while some lines are not covered due to rounding.

For instance, it says  "32847 / 32848 LOC (100.0%) covered"

I suggest  changing 
https://github.com/colszowka/simplecov/blob/92a7b4df103978f3131b803fa499477fe7d8387e/lib/simplecov.rb#L218
to
    `covered_percent = result.covered_percent.floor(2)` 

as I think it is enough to solve our issue and should be mostly transparent to other users

I'll submit a pull request if you are ok with the change.

Note: we're running 0.16.1

Thanks

**Comment by PragTob** [comment]
:wave: 

Thanks for the report!

Wow that's some dedication, what company is that if I might ask? ;)

That change is welcome of course :)

**Comment by gleseur** [comment]
Thanks @PragTob 
I opened https://github.com/colszowka/simplecov/pull/680 accordingly.

To answer your question, we're Shippingbo, a French startup.
If you start with that requirement, it's not so hard, and quite satisfying, to stick to it. The hard part is catching up if you let it drift.

**Comment by PragTob** [comment]
And merged :dancer:
