### ISSUE TITLE
0% coverage report

### ISSUE THREAD

**Issue by pcsgithubid** [colszowka/simplecov#682]
coverage report is 0% after upgrading app from Jruby 17 to jruby9.1.5 and simplecov-0.16.1

coverage. 0 / 4871 LOC (0.0%) covered.
** Execute default

spec_helper.rb

require 'simplecov'
SimpleCov.start 'rails'
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'simple_bdd'
require 'capybara/rails'
require 'factory_girl'
require 'webmock/rspec'
require 'capybara/rspec'
require 'capybara/webkit/matchers'

execute tests RAILS_ENV=test bundle exec rake

**Comment by PragTob** [comment]
:wave: 

Hi there in our tests it generally works. If you only upgrade JRuby or only simplecov does the problem still persist?

Otherwise we'd ideally need a script to reproduce this because otherwise we can't really identify where the bug comes from or well what the problem is.

**Comment by olleolleolle** [comment]
@pcsgithubid Did the workaround work for you? Can this issue be closed?

**Comment by tedthetnaungsoe** [comment]
passing JRUBY_OPTS="--debug" definitely work.
Or create .jrubyrc and add debug.fullTrace=true
I believe this issue should be closed.
