### ISSUE TITLE
guard warning (annoyance)

### ISSUE THREAD

**Issue by costa** [colszowka/simplecov#683]
With a simple guard config
```ruby
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch(%r{spec/.+(?<!_spec)\.rb})  { 'spec' }
```
it produces
```
        ** ERROR: directory is already being watched! **

        Directory: <proj-dir>/var/coverage

        is already being watched through: <proj-dir>/var/coverage

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```
even though I don't even start `SimpleCov` when in guard.

**Comment by PragTob** [comment]
Hi there,

I'm unsure how this relates to simplecov other than it may be the directory where we store our coverage results? Seems more like a problem with guard/guard configuration although I can't see what it is atm.

I'll close this for now, feel free to reopen.
