### ISSUE TITLE
TextFormatter like istanbul's text coverage report

### ISSUE THREAD

**Issue by tansaku** [colszowka/simplecov#686]
I've searched through the issues and found a couple of mentions of istanbul, but no one sharing the particular text output format it uses, e.g.

```
----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    79.41 |     57.5 |    83.78 |    79.41 |                |
 async-voter.js |     88.1 |    77.78 |      100 |     88.1 |... 49,75,76,77 |
 index.js       |       95 |    83.33 |       50 |       95 |             19 |
 persist.js     |    46.88 |       25 |       50 |    46.88 |... 55,69,77,79 |
----------------|----------|----------|----------|----------|----------------|
```

I find this quick and simple text output at the end of a test run to be super useful.  Is there an existing textformatter that I can use with simplecov that will output this kind of data on the command line after a test run?

A bit like the [rspec --profile option](https://stackoverflow.com/a/6946446/316729) does?

Maybe this will require writing my own formatter?  presumably simplecov can output data to the command line - not just static files?

Many thanks in advance

**Comment by PragTob** [comment]
:wave: 

An overview of existing formatters can be found here: https://github.com/colszowka/simplecov/blob/master/doc/alternate-formatters.md

Failing at that, yes you'd need your own formatter or we could make an official simplecov text formatter - quite honestly I don't have much time allocated for simplecov these days though.

**Comment by tansaku** [comment]
@PragTob totally understand about not having much time :-) happy to write a formatter if you can point me at anything that will help me get started - are there any docs on making a formatter, or is it just a question of looking through the existing formatters to get a feel for how to create one?

**Comment by PragTob** [comment]
@tansaku best to look at how the html formatter handles it, as it's by far the most used/tested one :)

**Comment by tansaku** [comment]
ah, looks like someone did it already https://github.com/chetan/simplecov-console
