### ISSUE TITLE
More specific Rails adapter

### ISSUE THREAD

**Issue by jasonmp85** [colszowka/simplecov#69]
I love the project but feel the coverage numbers it reports are too high in Rails projects.

Specifically controller tests often exercise functionality in model, lib, or helper classes. While the tests therefore technically 'cover' those lines, none of the controller tests are really testing model, lib, or helper code in isolation.

Basically I was wondering whether the 'rails' adapter could be modified in the following way: *When running spec:foo, SimpleCov only measures in the 'foo' directory*. For example, when running controller tests, a filter is applied which excludes models from being measured. And when running model tests, libs are not measured, etc.

Ideally there'd be a single incantation which would run all tests for which coverage makes sense (controllers, lib, helpers, models) and *only* measure coverage on the files they're directly testing. Then at the end the results are merged.

This would do a better job of showing actual coverage. If you 'cover' a model file because you used it in a controller, you're not really testing things like validation, scopes, etc. in isolation.

**Comment by bf4** [comment]
Closing as stale. Please reopen if this is still an issue. (And take a look at https://github.com/colszowka/simplecov/issues/340 )
