### ISSUE TITLE
Not generating results for external testing projects

### ISSUE THREAD

**Issue by yogevglucome** [colszowka/simplecov#690]
I want to analyze the test coverage in our code point of view, and therefore, installed the simplecov gem.

Our testing environement has 2 seperate project: REST API test (Java+Rest-Assured) and Web UI testing (Java-Selenium).
As you can see, we dont have unit testing inside the rails app, and testing using external projects. 

I configured the simplecov gem as descriped in the tutorial and put this, in the rails script:
`require 'simplecov'`
`SimpleCov.start 'rails'`
`puts "require simplecov"`

When loadin the app, I see the string I printed. 

I ran both automation test projects, and I don't see any coverage of controllers/models, I see only small precentage of initialization files of some gems and rails.

I searched a bit in the net, and tried putting the code phrase in boot.rb or even puma.rb and it returned the same results.

Any ideas?

**Comment by PragTob** [comment]
Hi there,

simplecov works through seeing what code is loaded/executed after simplecov is started. On exit of the process it then prints the results. So it absolutely needs to be loaded first, then the requests need to be made against the rails app it is running in and then it should print the result.

That said, I don't have much experience with such a thing as I usually do the testing from Ruby

**Comment by yogevglucome** [comment]
Update:
I really tried anything, using relative paths, config new profile etc.
I see the coverage only for the name of the methods in controllers and models, nothing inside, although I an 100% sure that I reach certain code parts.

**Comment by PragTob** [comment]
@yogevglucome sorry for the long silence. Have you gotten anywhere with this? It seems something is still wrong because method names etc. comes just from parsing the code so that looks to me like nothing is actually executed/correctly measured as covered.

It might also depend on the web server you are using. Lots of web servers fork processes to do their handling which as far as I know would interfere with this.

**Comment by PragTob** [comment]
Closing due to missing feedback

**Comment by czcq** [comment]
same problem! I am waiting the reply!
