### ISSUE TITLE
COVERAGE=true rspec not working when trying to run

### ISSUE THREAD

**Issue by okhan98** [colszowka/simplecov#693]
whenver I run COVERAGE=true rspec command i get the error:
Unable to activate codeclimate-test-reporter-1.0.8, because simplecov-0.16.1 conflicts with simplecov (<= 0.13)
something to do with versions I am assuming?

**Comment by manu29d** [comment]
This gem has been deprecated. Please refer to [this comment](https://github.com/codeclimate/ruby-test-reporter/issues/180#issuecomment-288202948)
Alternatively, you can check out the dependencies in the [gemspec file](https://github.com/colszowka/simplecov/blob/master/simplecov.gemspec) which indeed lists `simplecov <= 0.13`
My solution would be to run `bundle update codeclimate-test-reporter` which will downgrade the version of `simplecov`. This will further introduce breaking changes.

The best way would be to refer the README and use the new reporting method described there.

**Comment by PragTob** [comment]
This is correct although somewhere down my list is to convince codeclimate to change their strategy for their test reporter and revive the old one... but that's far inbetween.
