### ISSUE TITLE
How are `end` and `rescue` defined as non relevant lines?

### ISSUE THREAD

**Issue by janpio** [colszowka/simplecov#695]
While [trying to find a way to classify `require`, `def`, `module` etc. as non-relevant lines that do not affect the coverage calculation](https://stackoverflow.com/q/52294125/252627) I also noticed that `end`, `else` and `rescue` currently are excluded already:

![image](https://user-images.githubusercontent.com/183673/45453684-ca232d80-b6e1-11e8-98cd-c9f4a17c4502.png)

It seems to be https://github.com/colszowka/simplecov/blob/master/lib/simplecov/lines_classifier.rb 's job to do that, but I only see code that does this for comments and "empty" lines, not `end` or `rescue`.

Can someone point me into the right direction where this happens?

**Comment by PragTob** [comment]
@janpio :wave: 

Hi there! 

I believe the core ruby coverage library already provides this: https://ruby-doc.org/stdlib-2.6.3/libdoc/coverage/rdoc/Coverage.html

If you look at their sample, you'll see some lines have `nil` as a corresponding value which is their way of saying "not relevant" :)

**Comment by janpio** [comment]
Oh interesting, so if we wanted to go in there we would have to find a way to monkey patch that somehow. Doesn't look like something one wanted to do 🤷‍♂ Luckily we mostly abandoned the initial idea anyway, so not really needed and more.

Thanks for the response!

**Comment by PragTob** [comment]
@janpio I believe it's done in C so you couldn't even freedom patch it if you wanted to. You'd likely have to do a second pass to remove those nils, like override their result in the line classifier or what not. But if I understood correctly what you wanted to do, you wanted to ignore things that are currently classified. The line classifier would be right for that!
