### ISSUE TITLE
Incorrect coverage behavior of single-line `if` or `unless` statements

### ISSUE THREAD

**Issue by tit** [colszowka/simplecov#698]
There are two equivalent constructions (methods).

```ruby
def modifier
  raise if false
end

def statement
  if false
    raise
  end
end
```

When testing these constructs, 100% code coverage does not occur.

<img width="357" alt="coverage_report" src="https://user-images.githubusercontent.com/278604/46110471-640fcd80-c1ec-11e8-8bf4-cac2420ccdbf.png">

All source code for this issue I put on https://github.com/tit/simplecov_issue
For reproduction this defect use next steps:

1. Download https://github.com/tit/simplecov_issue
2. `cd /simplecov_issue`
3. run `rspec`
4. open `/simplecov_issue/coverage/index.html`

I use `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]`
and RubyMine 2018.3.

p. s.: Sorry for my bad English. :)

**Comment by bf4** [comment]
This behavior is actually correct. SimpleCov is measuring C0 covering using the Ruby Coverage module.  Though more recent versions of Ruby can calculate branch coverage, SimpleCov, at this time does not.

Thanks for the issue. Check this out

```bash
cat <<EOF > main.rb
def modifier
  raise if false
end

def statement
  if false
    raise
  end
end
EOF
ruby -r pp -rcoverage -e "puts RUBY_DESCRIPTION; Coverage.start; require './main'; pp Coverage.result"
rm -f main.rb
```

For me this returns

```
{"/path/to/main.rb"=>[1, 0, nil, nil, 1, 0, 0, nil, nil]}
```

see
https://grosser.it/2008/04/04/whats-my-coverage-c0-c1-c2-c3-path-coverage/

**Comment by tit** [comment]
Ooops, sorry)
