### ISSUE TITLE
Using Parallel Gem ignores coverage

### ISSUE THREAD

**Issue by dariusgm** [colszowka/simplecov#701]
* SimpleCov is correctly integrated, as I can see the coverage for most of the lines.
* Version: 0.16.1
* Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
* Rails: 5.1.5, but I think it is not related to rails

```ruby
class Sync
  class << self
    def run
      Parallel.map(product_ids, in_processes: 10, progress: 'Fetching and saving data') do |product_id|
        publish(product_id)
      end
    end

    private

    def product_ids
      [1,2,3,4,5]
    end

    def publish(product_id)
      Message.publish({ id: product_id })
      product_id
    end
  end
end
```

I am using Parallel inside a class. Its used inside a rake task to do a synchronization task. I was not able to get the line "publish" inside the Parallel.map Block to be recognized as a line that was called. My Rspec Test have this expectation line: `expect(Sync.run).to eq [1,2,3,4,5]` - even the test is passing, I don't get the line `publish` to be hit by the coverage. I assume its because Parallel is doing stuff in an other process and simplecov can get this line. Is it possible to either get it to be "green" or to disable the coverage scan for this particular line?

Thanks a lot for any hints

**Comment by deivid-rodriguez** [comment]
It sounds like you're running into https://github.com/colszowka/simplecov/issues/414.

**Comment by shamca65** [comment]
We are experiencing this issue as well. We run 12 processors during test runs and the .html summary is definitely not correct. Is there any workaround?

**Comment by dariusgm** [comment]
Yes it use. Surround your code with:
# :nocov:
....
# :nocov:

And simplecov will ignore it in the coverage calculation. For more Details please take a look at the Readme file in this repository.
