### ISSUE TITLE
100% coverage in single test file, but not 100% when in full test suite

### ISSUE THREAD

**Issue by jodeci** [colszowka/simplecov#703]
```
rails 5.2.1
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]
minitest 5.1
simplecov 0.16.1
```

Irrelevant code stripped out for demonstration:
https://gist.github.com/jodeci/bc9a23bec16968838f9bbf6cfadf3d8b

When written in an `if.. elsif.. else` fashion, simplecov reports 100% coverage only when the test file is tested alone. If the whole test suite is run (`rails test`), test coverage (for the same file) drops to 88% (in my case, always failing to recognize the `elsif` part).

However, if written in a guard clause fashion, simpelcov will report 100% coverage during the full test.

Not complaining since I'm back to 100% coverage, just curious whether this is intended behavior?

**Comment by bf4** [comment]
Coverage means executed after the coverage module was started. Looking at your gist I can't tell why booting the test suite might run that line before the coverage is started.

See https://grosser.it/2008/04/04/whats-my-coverage-c0-c1-c2-c3-path-coverage/ understanding C0 coverage.

**Comment by jodeci** [comment]
Among further inspection, the root cause of this (and other weird glitches not related to simplecov) was actually caused by bad (or rather lack of) namespaces. I had similar methods overwriting each other and once that was sorted out, all was good.
