### ISSUE TITLE
Is the bootsnap section in README still relevant?

### ISSUE THREAD

**Issue by fidalgo** [colszowka/simplecov#712]
After checking the Readme and the bootsnap issue on https://github.com/Shopify/bootsnap/issues/35 I think this is already addressed, so we can remove that section from the README.

Or am I missing something?

**Comment by PragTob** [comment]
Seems like it, thank you very much!

Will remove it :tada:

**Comment by PragTob** [comment]
Fixed in 96650350f33546eb6a5e2ae86
