### ISSUE TITLE
Possible to only check coverage of a few directories?

### ISSUE THREAD

**Issue by domi91c** [colszowka/simplecov#715]
I'm currently working on an admin tool that's integrated with our Rails app. I'd like to check the coverage of only the admin code, which is  contained in a few directories throughout the Rails app. For example, in `app/controllers/admin` and `app/models/admin`. Is there a way I can isolate the code coverage reporting to those directories?

I searched the documentation and found the `add_filter` method. Is there a method that does the opposite of `add_filter`, or will I need to list all the directories that I don't want coverage for?

**Comment by anhtranEH** [comment]
To make the coverage to run for these 2 directories only, I think you need to create a custom profile for that like:

`custom_profile.rb`
```
SimpleCov.profiles.define 'admin_dir' do
  add_filter do |source_file|
    !source_file.filename.include?("/admin")
  end
  add_group "Admin dir", ["app/controllers/admin", "app/models/admin"] 
end

```
and in the place where you run the simple cov
```
  require "custom_profile"

  SimpleCov.start 'admin_dir'
```

**Comment by PragTob** [comment]
What @anhtranEH wrote should work perfectly. Thank you!

@domi91c I'll close assuming this works for you, feel free to reopen if it doesn't :)
