### ISSUE TITLE
Does simple_cov understand Rails :concerning modules?

### ISSUE THREAD

**Issue by armchairdj** [colszowka/simplecov#723]
I'm running SimpleCov with RSpec on a Rails 5.2.x application. I'm including and starting SimpleCov with the `"rails"` argument at the very beginning of my test suite. Everything works great. Except:

I recently concernified one of my models. There isn't a single line of code in the model that isn't in an ActiveSupport `concerning` block (inline included module). This file shows up in my coverage report as having 0% test coverage despite the fact that every line of it is tested.

In other files that have a mix of `concerning` modules and inline code, the code inside the `concerning` modules get proper coverage metrics just like the inline code.

Any thoughts?

**Comment by armchairdj** [comment]
<img width="1552" alt="Screen Shot 2019-05-21 at 9 22 43 AM" src="https://user-images.githubusercontent.com/293721/58113297-11838700-7baa-11e9-9c66-088294d0f4d6.png">

Here's a screenshot of the SimpleCov output for this file (which most definitely is thoroughly specced).

**Comment by PragTob** [comment]
Hi there,

simplecov should be able to track their execution as ruby tracks execution for us and ruby shouldn't miss its own execution :)

Have you tried the [TroubleShootingSection](https://github.com/colszowka/simplecov#troubleshooting) ? This smells to me like that code is loaded or executed before simplecov even starts.

Failing at that a sample project would be helpful :)

Thank you!

**Comment by armchairdj** [comment]
Turns out this is configurable.

In `rubocop.yml`:

```
Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning
```

**Comment by PragTob** [comment]
@armchairdj hi there, any update on this? :)

**Comment by PragTob** [comment]
Closing due to missing feedback
