### ISSUE TITLE
Coverage reports as 0 for any class referenced in a rails initializer 

### ISSUE THREAD

**Issue by cschiewek** [colszowka/simplecov#725]
I have a constant defined in one of my rails models
```
# app/models/file.rb
class File
  PATH = '/tmp'.freeze
end
```
I then have an initializer that references that contstant
```
# config/initializers/create_path.rb
Dir.mkdir(File::PATH) unless File.exists?(File::PATH)
```
When I run my tests, the coverage for the `File` class is reported at 0.  If I remove that initializer, the coverage is reported correctly.

I'm running simplecov 0.16.1, minitest 5.11.3, and the requires in my test_helper are as such:
```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)
require 'simplecov'
require 'rails/test_help'
require 'mocha/minitest'
require 'webmock/minitest'
```

**Comment by PragTob** [comment]
Hi there @cschiewek,

please require and launch simplecov at the very top of your test_helper before any other requires. It needs to be required/started first so it can track all the other files being required, otherwise it won't work.

That should resolve your problem :dancer:

**Comment by PragTob** [comment]
(I'll already close as I'm fairly certain that's it, feel free to reopen if it isn't)
