### ISSUE TITLE
SimpleCov seems to not be able to accurately check `method_missing`

### ISSUE THREAD

**Issue by Qqwy** [colszowka/simplecov#728]
Ruby version: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`
SimpleCov version: `0.16.1`
Using Rspec (although I do not think it matters for this issue).

I have a class like the following:

```ruby
    # A wrapper class that implements the 'Cloaker' concept
    # which allows us to refer to variables set in 'bindings',
    # while still being able to access things that are only in scope
    # in the creator of '&block'.
    #
    # This allows us to bind the variables specified in `bindings`
    # one way during checking and another way during shrinking.
    class CheckEvaluator
      include RSpec::Matchers if Object.const_defined?('RSpec')

      def initialize(bindings, &block)
        @caller = eval 'self', block.binding, __FILE__, __LINE__
        @block = block
        define_named_instance_methods(bindings)
      end

      def call
        instance_exec(&@block)
      end

      private def define_named_instance_methods(results)
        results.each do |name, result|
          define_singleton_method(name) { result }
        end
      end

      def method_missing(method, *args, &block)
        super || @caller.__send__(method, *args, &block)
      end

      def respond_to_missing?(*args)
        super || @caller.respond_to?(*args)
      end
    end
```

This class is instantiated and called many times during the test run.

 Adding print statements to both `method_missing` and `respond_to_missing?` show that these are also indeed invoked.
However, `SimpleCov`'s HTML output looks like follows, clearly missing these two methods:

![image](https://user-images.githubusercontent.com/5345745/60265687-99198f80-98e6-11e9-8dc4-495ebbbf598a.png)

For a minimal reproducible example, consider something akin to:

```
SimpleCov.start

x = 300
CheckEvaluator.new(y: 33}) do
  p [x, y]
end.call
```

To see this class in the wild, check [this repo](https://github.com/Qqwy/ruby-prop_check/blob/f2f74385c33e96c1d583e3463b8341d068901b5d/lib/prop_check/property/check_evaluator.rb) of the Property Testing library I am building. Cloning it and running `bundle install; rspec` on there (and then opening the `coverage/index.html`) will also indicate the problem.

**Comment by PragTob** [comment]
:wave: 

Answered in https://github.com/Qqwy/ruby-prop_check/pull/1 - basically I could add raises to the methods and tests wouldn't fail for me. So I believe simplecov is right here and I've used it with method_missing before.

Closing for now until we figure out what's wrong, feel free to reopen if I'm wrong or I'll do it myself :)

Tobi

**Comment by Qqwy** [comment]
With thanks to @PragTob , this issue was found out to indeed be a user issue by me, and has been resolved. :clap:
