### ISSUE TITLE
Simplecov fails to exit on rspec suite completion in Ruby 2.6.3

### ISSUE THREAD

**Issue by doublephi** [colszowka/simplecov#740]
So after upgrading the Ruby version used with my app from 2.5.5 to 2.6.3, simplecov 0.17.0 now hangs silently and permanently at the end of my test suite.

I'm running Ruby 2.6.3 and Rails 5.2.3.

As for what else may be relevant, I have capybara 3.26.0 running and I'm using RSpec.

Here's an example of the output I get:

```Finished in 28.28 seconds (files took 2.6 seconds to load)
138 examples, 0 failures, 1 pending

Randomized with seed 29475
```

Then that's where it hangs. One think I tried is adding "use_merging false" to my SimpleCov.start block, as I saw that suggested out and about. No luck for me.

Any help is greatly appreciated!

**Comment by trafium** [comment]
Faced same issue, only thing that helped is rolling back to simplecov 0.16.1

**Comment by PragTob** [comment]
Hi there,

thanks for the report :green_heart: 

Sorry I didn't have much time for OSS the last couple of months/weeks so I missed this :disappointed: 

It got fixed in the mean time in #746 and I released 0.17.1 to match. Please upgrade and let me know if it's really fixed.

**Comment by MisterSpicy** [comment]
Hmm, still broken for me on 0.17.1

**Comment by cnicolaou** [comment]
Hey @PragTob, thanks for the fix but it fails still with Ruby 2.6.5.

I had to revert back to version `0.16.1` as mentioned by @trafium above.

**Comment by PragTob** [comment]
@cnicolaou that is really discomforting - would you happen to have an example repo you could share or something? Are you using parallel tests? For most other people 0.17.1 seems to work so this is kinda scary for me :)

**Comment by cnicolaou** [comment]
@PragTob I take back what I have shared previously.

The error that happened was because i had duplicate configurations for SimpleCov, `.simplecov` and inside `rails_helper`.

PS: I am still using `0.16.1` though

I apologise for this inaccurate bug reporting, please feel free to close the ticket again.

**Comment by PragTob** [comment]
@cnicolaou no worries and thank you :)

**Comment by tieeeeen1994** [comment]
I am also having this issue. However, we are using Ruby 3.3.0. SimpleCov version is at 0.22.0.

I am not sure what's causing this. Any ideas what is causing this?

**Comment by tieeeeen1994** [comment]
An update; it seems that SimpleCov hangs when there's a lot of tests included in one command. I tried adding folders one by one, then when I added `spec/folderA`, it started hanging. However, upon running rspec on `spec/folderA`, all tests pass and SimpleCov was able to generate the report.

I'm not really sure what to do here anymore.
