### ISSUE TITLE
Misleading Text on coverage of Views files

### ISSUE THREAD

**Issue by chase439** [colszowka/simplecov#745]
The README currently states:

> If you're making a Rails application, SimpleCov comes with built-in configurations (see below for information on profiles) that will get you started with groups for your Controllers, **Views**, Models and Helpers.

However, views files are not covered. I would suggest removing the word "Views" from the README.

**Comment by chase439** [comment]
I would also add a caveat that since views files are not ruby files, it's not possible to get their coverage in the report.

**Comment by PragTob** [comment]
Hi there, thanks for the report! :wave: 

That's right, I'm just not 100% certain. If someone made DSL that's pure Ruby view files would be covered to the best of my understanding. There just isn't any coverage for erb/haml/slim and whatever their names are.

**Comment by PragTob** [comment]
Fixed in 6dd17ee4128b9e8c
