### ISSUE TITLE
Parallel_tests wrong timestamp

### ISSUE THREAD

**Issue by silva96** [colszowka/simplecov#751]
Im running simplecov with parallel tests and it keeps showing one report with a totally wrong timestamp from 2018-01-01 00:00:00, see the Rspec4 key

![image](https://user-images.githubusercontent.com/4019924/66784849-f9dad100-eeb1-11e9-8027-52d6803296ae.png)

It always puts that timestamp (never changes) on the rspec4, every time I run the parallel test, even if I delete the coverage folder.

I checked the gem code and all it does is 

```ruby
    # Defines when this result has been created. Defaults to Time.now
    def created_at
      @created_at ||= Time.now
    end
```

I dont see why is this happening. any thoughts?

**Comment by silva96** [comment]
Added some puts in `created_at` `to_hash` and `from_hash` methods, here is the output (notice the 2017 time...)

![image](https://user-images.githubusercontent.com/4019924/66786527-0ada1100-eeb7-11e9-9380-092ac77430c5.png)

**Comment by silva96** [comment]
I found that in a few of my tests I was freezing the time with timecop
```ruby
before do
      Timecop.freeze(Time.zone.local(2018))
    end
```

**Comment by PragTob** [comment]
@silva96 not sure if you found it yourself, but you should either call `Timecop.return` or use an around rspec hook and then do `Timecop.freeze(time) { yield }` to fix the ptorblem.

**Comment by silva96** [comment]
@PragTob yes we have like 40 usages and just one was without return, introduced in the last sprint
