### ISSUE TITLE
Coverage not working properly

### ISSUE THREAD

**Issue by ejelome** [colszowka/simplecov#755]
Hi, new RoR guy here.

I'm using `ruby 2.6.3p62` (latest) and `Rails 6.0.0` (also latest) but this gem (using latest) seems to not show test coverage properly. Below is the setup and the result:

`Gemfile`:
``` ruby
group :test do
  ...
  gem 'simplecov'
  ..
end
```

---

`test/test_helper.rb`:
``` ruby
require 'simplecov'

SimpleCov.start 'rails'

ENV['RAILS_ENV'] ||= 'test'

require_relative '../config/environment'
require 'rails/test_help'
...
```
---

`app/controllers/pages_controller.rb`: (an example controller)

``` ruby
class PagesController < ApplicationController
  def index
    @title = "Hello World!"
  end
end
```

---

`test/controllers/pages_controller_test.rb`:  (an example controller test)

``` ruby
require 'test_helper'

class PagesControllerTest < ActionDispatch::IntegrationTest
  test "should get homepage" do
    get root_path
    assert_select "body", "Hello World!"
  end
end
```
---

`COVERAGE` output:
```
+----------+----------------------------------------------+-------+--------+---------+
| coverage | file                                         | lines | missed | missing |
+----------+----------------------------------------------+-------+--------+---------+
|   0.00%  | app/controllers/pages_controller.rb          | 5     | 5      | 1-5     |
+----------+----------------------------------------------+-------+--------+---------+
```

**Comment by ejelome** [comment]
After some trial and error, it seems that commenting out the parallel testing line (37) still is the solution to fix this problem:

``` ruby
class ActiveSupport::TestCase
  # Run tests in parallel with specified workers
  # parallelize(workers: :number_of_processors);
  ...
end
```

**Comment by ejelome** [comment]
Closing this as there seems to be no at the moment.

**Comment by worace** [comment]
I ran into this as well on Rails 6.0.0 and Simplecov 0.17.1. Fixed for the moment by disabling parallel testing.

The README interestingly claims this is supported:

> As of 0.8.0, SimpleCov should correctly recognize parallel_tests and supplement your test suite names with their corresponding test env numbers. SimpleCov locks the resultset cache while merging, ensuring no race conditions occur when results are merged.

So I wonder if there were some changes in how parallel testing is handled in recent Rails versions that caused a regression here.

**Comment by PragTob** [comment]
@worace rails built their own parallel testing thingy... so far we only integrate with parallel_tests as in the parallel_tests gem. Making it work with rails 6.0 parallel tests is on the roadmap :ok_hand:

**Comment by PragTob** [comment]
Also sorry hadn't seen this issue or rather.. when I looked it was already closed so I thought it was resolved.

**Comment by worace** [comment]
Ah, makes sense. Thanks for the explanation. I have been out of rails for a bit and did not realize they were different things.

**Comment by GURVARINDER** [comment]
@PragTob Any updates on this issue? Has this been resolved in the latest version?

**Comment by PragTob** [comment]
@GURVARINDER no I didn't have time yet to work on tests parallel test execution

**Comment by pdfrod** [comment]
Can I suggest adding to the documentation that Rails parallel tests is not supported at the moment? I just wasted a lot of time trying to figure out why my code coverage was incorrect.

**Comment by dtgay** [comment]
You can get simplecov working with Rails test parallelization with the fix here: https://github.com/simplecov-ruby/simplecov/issues/718#issuecomment-538201587
