### ISSUE TITLE
LAST_READ_LINE is broken

### ISSUE THREAD

**Issue by andrew-aladev** [colszowka/simplecov#758]
Hello. I've found a [simple bug](https://github.com/lemurheavy/coveralls-ruby/issues/155): it is not possible to use `LAST_READ_LINE`.

```ruby
require 'simplecov'

def a
  puts $LAST_READ_LINE
end

$LAST_READ_LINE = "1"
a
```

`$LAST_READ_LINE` is `nil` inside function.

All methods like `print` based on `LAST_READ_LINE` are broken.

> ruby 2.6.5

**Comment by andrew-aladev** [comment]
It is triggered by
```ruby
require "English"
```

It looks like a bug inside ruby itself. I will investigate it later.

**Comment by andrew-aladev** [comment]
```c
VALUE
rb_lastline_get(void)
{
    return vm_svar_get(GET_EC(), VM_SVAR_LASTLINE);
}
void
rb_lastline_set(VALUE val)
{
    vm_svar_set(GET_EC(), VM_SVAR_LASTLINE, val);
}
```

`GET_EC` returns different scopes. It is just my wrong understanding of `LAST_READ_LINE`: it is local to current scope.

![sorry](https://i.imgur.com/0OcCjsf.jpg)

**Comment by PragTob** [comment]
No worries! :)
