### ISSUE TITLE
Plans for including functional/method level coverage ? 

### ISSUE THREAD

**Issue by amitSA** [colszowka/simplecov#762]
In ruby 2.5.* , functional level coverage is implemented by the underlying Coverage library.

But as of SimpleCov v0.17.1 , functional coverage reporting is not supported by SimpleCov. 
Are there plans to support this ?

**Comment by PragTob** [comment]
Hi there @amitSA,

so you mean method level coverage? (not sure what you mean with "functional").

Yes it is planned, I just didn't have the time to do so by now. That said it's not on the top of my list, first it's getting branch coverage in and then some rails integration problems. If I have time after that method level coverage will be implemented, albeit after branch coverage is in it should hopefully be rather easy.

I'll have a lot more time to dedicate to simplecov starting in December so I might be able to do some feature catch up then.

Cheers,
Tobi

**Comment by amitSA** [comment]
Hi @PragTob 
Yes I meant method level coverage! And i appreciate you dedicating your free time on simplecov.  Helps all of us :) 

I'll close the issue now.
