### ISSUE TITLE
simplecov shows 0.0%

### ISSUE THREAD

**Issue by isel** [colszowka/simplecov#77]
We are trying to use simplecov with rspec from within a rake task. we have tried in Windows and ubuntu, but it always shows 0.0%, like this:

```
  root@ip-10-81-10-196:~# rake
  /opt/rvm/rubies/ruby-1.9.2-head/bin/ruby -S rspec test_spec.rb
  .
  Finished in 0.00039 seconds
    1 example, 0 failures
  Coverage report generated for RSpec to /root/coverage. 0 / 0 LOC (0.0%) covered.
```

we are not using bundler, we installed simplecov 0.5.2 and rspec 2.6.0 via "gem install". 

rakefile.rb has:

  require 'simplecov'
  SimpleCov.start

  require 'rake'
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = '*_spec.rb'
  end

  task :default => :spec

and test_spec.rb has:

  require 'rspec'

  class TestClass
    attr_reader :text

```
def initialize(text)
  @text = text
end
```

  end

  describe "a simple test" do
    it "should be covered" do
      test_class = TestClass.new('default text')
      test_class.text.should == 'default text'
    end
  end

How do we make it work?

thank you so much,

Isel

**Comment by sebasjimenez10** [comment]
I'm using Simple Cov without any framework just plain ruby classes. I wanted to see how the coverage was and I had the 0 lines covered issue.

I was able to solve this mixing @isel, @jokeyrhyme an d @ahamid solutions. Here's my example:

```
require 'simplecov'
SimpleCov.start do
  @filters = []
end

require 'minitest/autorun'
```

I needed to set the filters to an empty array and also require simplecov before requiring minitest/autorun.

Hope this helps anyone.

**Comment by Dorian** [comment]
My `Simplecov.start 'rails'` was inside `spec/spec_helper.rb` but `spec/rails_helper.rb` was called before, so I had to move it to `spec/rails_helper.rb` ;)

**Comment by dmolesUC3** [comment]
I was trying to be clever and `require`ing  my library in its own gemspec, in order to get version and description information, so the whole library would be loaded before simplecov started. Fix was to require just the file with the version and description constants.

**Comment by shozayen** [comment]
I have tried possible solutions but none of them worked, I run below command before running RSPEC:  
`set  JRUBY_OPTS="--debug"`
