### ISSUE TITLE
Include not covered files in HTML report

### ISSUE THREAD

**Issue by Pr0p1k** [colszowka/simplecov#788]
If I have some files uncovered at all, I don't see them in the HTML report, it only contains files included into JSON output of simplecov. 
It would be also cool having an opportunity to group files by their directory just like RubyMine does (including not covered files).
I use Ruby 2.6.3 and simplecov 0.17.1.
As you can see on the screenshot: The project contains way more files and I get wrong average coverage percent because the "0%" files are not included.
![image](https://user-images.githubusercontent.com/31842542/70514426-afd63a80-1b44-11ea-995d-558f20423f7b.png)

**Comment by PragTob** [comment]
Hi there @Pr0p1k,

thanks for your issue report.

1. For coverage, just requiring the files (after simplecov was started) whould make them show up in the report. Alternatively you can use [`track_files`](https://rubydoc.info/gems/simplecov/SimpleCov/Configuration#track_files-instance_method) to force their inclusion beyond that.
2. there's a [groups feature](https://github.com/colszowka/simplecov#groups) just for categorizing them which I think should cover your use case. 

Cheers,
Tobi

**Comment by Pr0p1k** [comment]
@PragTob Thanks, track_files helped me! But I still didn't managed to make groups feature group by directory
