### ISSUE TITLE
not working with riot correctly?

### ISSUE THREAD

**Issue by saiko-chriskun** [colszowka/simplecov#80]
simplecov results: http://stuff.saikonet.org/images/misc/2011-09-18-150129_1024x768_scrot.png

my tests:

    context 'New user visits web site' do
        base_uri 'http://localhost:3001'
        get '/'
        asserts_status.equals(200)
    end
    context 'Authentication' do
        context 'User signs up' do
          base_uri 'http://localhost:3001'
          post '/site/authenticate', body: { user: { email: 'saiko_chriskun@shortmail.com', password: 'my_pass' } }
          asserts_status.equals(200)
          asserts('display tasks') { response.body.match(/New Task/) != nil }
        end

        context 'User signs in' do
           base_uri 'http://localhost:3001'
           post '/site/authenticate', body: { user: { email: 'saiko_chriskun@shortmail.com', password: 'my_pass' } }
           asserts_status.equals(200)
           asserts('display tasks') { response.body.match(/New Task/) != nil }
         end
        context 'User tries to signup with existing email' do
           base_uri 'http://localhost:3001'
           post '/site/authenticate', body: { user: { email: 'saiko_chriskun@shortmail.com', password: 'incorrect_pass' } }
           asserts_status.equals(200)
           asserts('display flash message') { response.body.match(/taken!/) != nil }
         end
    end

**Comment by bf4** [comment]
Closing as stale. Please reopen if this is still an issue. (And take a look at https://github.com/colszowka/simplecov/issues/340 )
