### ISSUE TITLE
Ability to include code outside of project root

### ISSUE THREAD

**Issue by bjeanes** [colszowka/simplecov#81]
Use-case: uncovering and removing un-needed dependencies from large applications

I work on a HUGE application with 50+ gems as dependencies. It's become evident that there are a few gems that were included early on in the project's life that may no longer be necessary or that may be rarely used (maybe one method from it is needed, for example). 

The more dependencies there are, the slower the application is when running the tests, starting the app, running rake tasks, starting the console, etc. Finding the least-used gems by using a coverage tool when running the complete suite of specs/cukes would be an ideal way to remedy this problem.

**Comment by bf4** [comment]
Closing as stale. Please reopen if this is still an issue. (And take a look at https://github.com/colszowka/simplecov/issues/340 )
