### ISSUE TITLE
No data is generated

### ISSUE THREAD

**Issue by pupeno** [colszowka/simplecov#82]
Hello,

I'm not sure when simplecov stopped generating data for my project, the html is generated but no file is mentioned. I'm configuring it this way:

``` ruby
# Setup simplecov.
require "simplecov"
SimpleCov.start "rails"
SimpleCov.command_name # Needed to separate test suits, due to issue https://github.com/colszowka/simplecov/issues/45
```

and I have this gems installed:
- actionmailer (3.1.0)
- actionpack (3.1.0)
- activemodel (3.1.0)
- activerecord (3.1.0)
- activeresource (3.1.0)
- activesupport (3.1.0)
- addressable (2.2.6)
- airbrake (3.0.4)
- arel (2.2.1)
- assert_difference (0.3.1)
- bcrypt-ruby (3.0.1)
- builder (3.0.0)
- bundler (1.0.18)
- cancan (1.6.5)
- capybara (1.1.1)
- childprocess (0.2.2)
- coffee-rails (3.1.1)
- coffee-script (2.2.0)
- coffee-script-source (1.1.2)
- daemons (1.1.4)
- delayed_job (2.1.4)
- devise (1.4.6)
- erubis (2.7.0)
- eventmachine (0.12.10)
- execjs (1.2.8)
- factory_girl (2.1.0)
- factory_girl_rails (1.2.0)
- ffi (1.0.9)
- growl_notify (0.0.1)
- guard (0.7.0)
- guard-test (0.3.1)
- haml (3.1.3)
- haml-rails (0.3.4)
- heroku (2.8.0)
- hike (1.2.1)
- i18n (0.6.0)
- jquery-rails (1.0.14)
- json_pure (1.6.1)
- launchy (2.0.5)
- mail (2.3.0)
- mail_safe (0.3.1)
- mime-types (1.16)
- multi_json (1.0.3)
- multitenant (0.4.0)
- newrelic_rpm (3.1.2)
- nokogiri (1.5.0)
- orm_adapter (0.0.5)
- pg (0.11.0)
- polyglot (0.3.2)
- rack (1.3.3)
- rack-cache (1.0.3)
- rack-mount (0.8.3)
- rack-ssl (1.3.2)
- rack-test (0.6.1)
- rails (3.1.0)
- rails-footnotes (3.7.5.rc4)
- rails_admin (0.0.1 8a24737)
- railties (3.1.0)
- rake (0.9.2)
- rb-appscript (0.6.1)
- rb-fsevent (0.4.3.1)
- rdiscount (1.6.8)
- rdoc (3.9.4)
- rest-client (1.6.7)
- rubyzip (0.9.4)
- sass (3.1.7)
- sass-rails (3.1.2)
- selenium-webdriver (2.6.0)
- sequel (3.20.0)
- shoulda (2.11.3)
- simple_form (1.5.1)
- simplecov (0.5.3)
- simplecov-html (0.5.3)
- sinatra (1.0)
- sprockets (2.0.0)
- sqlite3 (1.3.4)
- sqlite3-ruby (1.3.3)
- stringex (1.3.0)
- taps (0.3.23)
- term-ansicolor (1.0.6)
- test-unit (2.3.2)
- thin (1.2.11)
- thor (0.14.6)
- tilt (1.3.3)
- treetop (1.4.10)
- tzinfo (0.3.29)
- uglifier (1.0.3)
- verbose_factory_girl (0.1.0)
- warden (1.0.5)
- xpath (0.1.4)

while running ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.1.0]

**Comment by Tarun17** [comment]
I get this issue as well. I am using SimpleCov with RubyMine IDE.  

![image](https://cloud.githubusercontent.com/assets/4503298/10130310/fec3e10a-658c-11e5-8510-2588503f2153.png)

and this what the coverage report looks like:

![image](https://cloud.githubusercontent.com/assets/4503298/10130315/1e37b502-658d-11e5-875f-d2d8e5362af3.png)

Really need some help

**Comment by harold-s** [comment]
If someone is not finding a solution. My problem in a Rails project was not having a .rspec file with inside
`--color
--require spec_helper
`
Guessed spec_helper was not called right a the beginning and so simplecov registered too late,

**Comment by Dorian** [comment]
I have `--require rails_helper` in my `.rspec` so I had to put simplecov in `rails_helper`
