### ISSUE TITLE
Content Security Policy error and js/css problems when view html report remotely

### ISSUE THREAD

**Issue by nroose** [colszowka/simplecov#849]
Howdy! Thank you for this great gem!

We are now successfully running simplecov on our parallel jenkins rspec runs and merging the results! It's great!

But when we view it remotely as an artifact on a server, rather than downloading the results and viewing them locally, we get an error and some features don't work properly.

We are using 0.18.0, but this was happening on 0.16.1 too.

We are running Rails 6.0.1 and rspec 3.8.0.

The error messages in the browser consoles are:
chrome
```
Blocked script execution in 'https://jenkins.repairpal.com/job/Rails/job/coverage-chore-upgrade-simplecov-2020-01-30-13-56/1/artifact/coverage/index.html#' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
index.html#:16 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution.
```
firefox
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).
```

The resulting behavior is that the spinner is permanent, the columns are not clickable for sorting, and the file views are missing some background color formatting.
![Screen Shot 2020-01-30 at 4 10 22 PM](https://user-images.githubusercontent.com/177314/73501547-1c1e2f00-437b-11ea-98ca-1eace95ae008.png)
![Screen Shot 2020-01-30 at 4 10 34 PM](https://user-images.githubusercontent.com/177314/73501548-1c1e2f00-437b-11ea-9cef-485ff64e3861.png)

**Comment by PragTob** [comment]
Hi @nroose !

Thanks a lot for the bug report :green_heart: 

Theoretically/hopefully this should be an easy fix, not sure when I'll get to it though :)

It might however already be fixed in https://github.com/colszowka/simplecov-html/pull/51 - I haven't taken time yet to dig through all those PRs. Maybe it's time I start doing this.

Cheers,
Tobi

**Comment by nroose** [comment]
Oh! OK. Thanks for the reply. colszowka/simplecov-html#51 seems to have conflicts. I was thinking I would look into it. I will try using that branch koenpunt:csp and see how it goes.

**Comment by nroose** [comment]
Just using that version of simplecov-html doesn't seem to work.

**Comment by nroose** [comment]
I have solved our issue with this solution: https://stackoverflow.com/a/46197356/1899716

**Comment by PragTob** [comment]
Interesting, thanks for the updates!

**Comment by PragTob** [comment]
Fixed version released.
