### ISSUE TITLE
Source files on the second page not opening in coverage report

### ISSUE THREAD

**Issue by dometto** [colszowka/simplecov#867]
Source files on the second page of the overview are not being displayed (at all) when I click them. On the first page, everything is fine. 

This is what it looks like on Firefox:

<img width="898" alt="Screenshot 2020-02-18 at 13 00 45" src="https://user-images.githubusercontent.com/147111/74734389-bd97f280-524e-11ea-8121-1d32c4965f73.png">

On Chrome, I get an error saying: "This content failed to load.".

The source for one of them is:

```html
            <td class="strong t-file__name"><a href="#43d7c8034528c6016dba1551b5b448b35216ed5d" class="src_link" title="lib/langs.rb">lib/langs.rb</a></td>
```

And the relevant div does seem to exist in the HTML:

```html
        <div class="source_table" id="43d7c8034528c6016dba1551b5b448b35216ed5d">
  <div class="header">
    <h3>lib/langs.rb</h3>
```

* RSpec ~> 3.9
* Using a simple `.simplecov`:
```ruby
SimpleCov.start do
    add_filter 'spec'
end
```
* `simplecov v0.18.2` and `simplecov-html v0.12.0`
 * `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`
* The relevant repo is here: https://github.com/repotag/rubydeps/

**Comment by PragTob** [comment]
Yay, I knew all my wild JS dependency updates would eventually show holes in the test coverage and break things :see_no_evil: 

Thanks a bunch for the report! :green_heart: 

I'll have fun fixing these I guess ;) I will hopefully make it this week.

**Comment by PragTob** [comment]
Fixed through https://github.com/colszowka/simplecov-html/pull/96 - no more pagination, no more errors :angel:

**Comment by dometto** [comment]
Thanks @PragTob!
