### ISSUE TITLE
Support for relative paths in `coverage/.resultset.json` 

### ISSUE THREAD

**Issue by etagwerker** [colszowka/simplecov#887]
Howdy! Thanks for maintaining `simplecov`! ❤️ 

I'm wondering if anyone would be interested in having relative paths in `coverage/.resultset.json` -- I would find this quite useful because right now I have a little problem between my development and CI environments

I realize that https://github.com/colszowka/simplecov/issues/229 proposed this many years ago, but then it was closed as it was considered a duplicate of https://github.com/colszowka/simplecov/issues/197. I don't think #197 is quite the same as this issue though, that's why I think it deserves a new issue.

## Problem 

I want to use a `coverage/.resultset.json` file that was generated in Circle CI in my local environment. `SimpleCov` reports that there is 0% coverage for all files in my project. 

I know that the problem is happening because the paths in the file that I download has absolute paths within a Circle CI container.

### Resources

- This file was generated with SimpleCov in Circle CI: https://gist.github.com/etagwerker/0518a1e381b1c6dc4d8814c7602ca108
- After searching and replacing with my local environment's absolute path, this file works as expected: https://gist.github.com/etagwerker/15de7af66f78cc788d4c4696f1bd409f

## Workaround 

If I follow these steps: 

1. Download `coverage/.resultset.json`
2. Find and replace root directory within `coverage/.resultset.json`
3. Run `skunk lib`

Then everything works as expected. Skunk uses SimpleCov and it detects coverage as expected.

## Solution?

I wonder if we could add a configuration option to `SimpleCov` that specifies `relative_paths` (default to false) so that all the file paths written in `coverage/.resultset.json` are relative (instead of absolute)

It could work like this: 

```ruby
SimpleCov.start do
  relative_paths true
end
```

You can also set it like this:

```ruby
SimpleCov.relative_paths true
```

That way you wouldn't get unexpected results when using a `coverage/.resultset.json` from another environment.

Any thoughts about this?

**Comment by PragTob** [comment]
:wave: 

Hi and thanks for opening an issue @etagwerker !

Let's go back a step - why do you want a `resultset.json` from another environment in your local environment?

**Comment by etagwerker** [comment]
@PragTob That's a good question! We do a lot of code audits in my agency and we've found that it's much easier to run SimpleCov in our client's continuous integration service than in our local environments. 

Then we check out their application code and analyze it in our local environment. In order to find hotspots, we use https://github.com/fastruby/skunk which depends on `coverage/.resultset.json` 

Sometimes our client's CI is quite complicated and it takes hours to finish. That means that they're probably using different containers in their CI service. So that means that before calling `skunk` we need to download artifacts from CI (including .resultset.json), merge them, and finally use them in our local environment. (more about merging here: https://www.fastruby.io/blog/rails/simplecov/upgrades/merging-multiple-simpleCov-coverage-results.html)

**Comment by PragTob** [comment]
@etagwerker no one should rely on `.resultset.json`, it's an internal implementation detail and doesn't even have the full reported data. I highlighted some of the inadequacies of using `.resultset.json` over there: https://github.com/codeclimate/test-reporter/issues/413#issue-545404610 - basically it's just the raw ruby coverage data without any or much simplecov coverage processing.

The proper way to go about this imo is to write your own formatter. That's an official extension way, albeit I'll grant that documentation could be better.

**Comment by etagwerker** [comment]
@PragTob Thanks for the quick response! 👍 

> no one should rely on .resultset.json, it's an internal implementation detail and doesn't even have the full reported data.

This is a little bit confusing because it is mentioned a few times in the README. For example: https://github.com/colszowka/simplecov#merging-test-runs-under-different-execution-environments

> The proper way to go about this imo is to write your own formatter. 

I'm not sure if that would be the best way for what I'm trying to do. Skunk depends on RubyCritic, which in turn depends on SimpleCov. You can see how we are reading `covered_percent` over here:  https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/analysers/coverage.rb#L36

The only reason I decided to use `.resultset.json` was because I just needed a machine-readable format to read the coverage per module. In the near future I'd like to find coverage per method and use that information in both RubyCritic and Skunk.

> Due to the introduction of branch coverage the format of this file will change slightly in the next release (beta release just released)

This is something that I'm interested in using in both RubyCritic and Skunk. 

> I highlighted some of the inadequacies of using .resultset.json over there: codeclimate/test-reporter#413 (comment)

Thanks for sharing this! It's very interesting and I learned a lot. 😄 

> On the other hand you can say, it'd be nice to have an official JSON formatter so 🤷‍♂️

You mentioned this in that issue. Is this something that you're planning to work on? I think I would still need raw data in that formatter, which would allow me to create SimpleCov objects in RubyCritic. 

I apologize for talking about way too many different things in this issue. TL; DR: I think it would be very positive to have an official JSON formatter, which included raw data.

**Comment by PragTob** [comment]
@etagwerker 

`.resultset.json` is only ever mentioned when talking about merging test where it goes through another round of simplecov processing either through our parallel tests merging mechanism or `SimpleCov.collate`. All of those were also just introduced rather recently ~ mid January. I was fearing people might mistake this as it's ok to work for the file, even if the format is never discussed or it's never suggested to look at it yourself (iirc). I might add a note about this.

Regarding a formatter - what a formatter allows you to do is access the coverage data/data structures as simplecov itself uses them. You can then use them to gather them in some big ruby object, write out another machine readable format or whatever your heart desires. I acknowledge the interface isn't documented as well as it could be and there might be some deprecations there in the future, if I get the time. It's definitely my recommended way to work with SimpleCov results.
We could explore an easily accessible for SimpleCov that given a `resultset.json` and a configuration you can load the corresponding `SimpleCov` structures to work with them, I have no idea how complicated that'd be right now though (might be super easy, might be harder than expected)

(thanks for your work on rubycritic by the way)

What do you mean by raw data? Raw coverage data? Sure, that's the plan. I'm not planning to work on it right now as there are enough other things to work on. My current deal with CodeClimate is they are the ones to write the JSON formatter (see a bit further below in the very same issue).

**Comment by etagwerker** [comment]
@PragTob yeah, this is exactly what I want: 

> We could explore an easily accessible for SimpleCov that given a resultset.json and a configuration you can load the corresponding SimpleCov structures to work with them

Are you thinking about incorporating https://github.com/vicentllongo/simplecov-json to `simplecov`? 

My concern is that you might end up with two codebases to maintain very similar logic: What would be the main difference between `.resultset.json` and `resultset.json`? I understand that the goal for both those files is different: 

- `.resultset.json` is a cache file that gets used internally by `simplecov` -- this is a private API that `simplecov` users should not rely on
- `resultset.json` is an output formatted in JSON that has very similar information to the HTML report and `.resultset.json` -- this is a public API that `simplecov` users can trust (and might follow semver?)

As you add more features (e.g. coverage data about different branches) I would expect `resultset.json` to have those details.

> My current deal with CodeClimate is they are the ones to write the JSON formatter (see a bit further below in the very same issue).

This is great. I might just wait until they're done with that, to add support to `RubyCritic` and `Skunk`

**Comment by PragTob** [comment]
@etagwerker 

Sorry - interesting times :)

Yes I'm talking about having an official json formatter for SimpleCov. The idea indeed is that one could be relied upon vs. the other and ideally follows semver. The differences go beyond that though - the "formatted"/official json would have lines marked as ignored, loaded files that ruby code coverage didn't load, filtered out files etc. - essentially all the features of simplecov applied to it vs. the current `.resultset.json` which has none of that (It's more or less a dump of what the standard coverage library provides, but merged)

Newer features would be added there yes. But honestly, it's also one of the points why I was resisting adding it as it means more work for me and for new features. So I won't promise it, but it'll remain the goal.

Anyhow, we're at the stage where [code climate will make a PR/proposal of a formatter](https://github.com/codeclimate/test-reporter/issues/413#issuecomment-647188859) - I guess hope we can close this issue then? :)

**Comment by etagwerker** [comment]
@PragTob Sounds good, thanks!
