### ISSUE TITLE
How does Simplecov treat specs marked as pending?

### ISSUE THREAD

**Issue by chrishough** [colszowka/simplecov#888]
I have a short question, I am digging into. I recently stubbed an entire set of classes in a sinatra application and would have expected the specs marked `pending` to reduce the coverage nearly to zero. Instead, it raised the coverage to nearly 90+ percent. 

Is that normal?

**Comment by PragTob** [comment]
No, depending on how you run things ;)

We don't have any special trearment for pending specs. We just start and watch what ruby code is required and executed.

So normally pending --> less code executing --> less coverage.

Now, if the amount of ruby files you `require` is dependent on the specs you run (autoloading for instance) then pending specs might mean less files load --> less code --> higher coverage

**Comment by chrishough** [comment]
Thank you @PragTob I had to confirm that.
