### ISSUE TITLE
Please consider cutting a release

### ISSUE THREAD

**Issue by jar349** [colszowka/simplecov#892]
I was following the documentation for subprocesses and discovered that `SimpleCov.enable_for_subprocesses true` is only available on the master branch.  I would like to use this functionality as I have a spec that I must run in a subprocess (`Process.fork {}`).

I claim that this feature is worthy of a release by itself and instead of me updating my gemspec to pull from master, I wonder if you would consider cutting a new release?

**Comment by PragTob** [comment]
:wave: Hi @jar349 ,

thanks for the feedback. While generally yes, there's nothing wrong with small releases I think there's a couple of more things I'd like to land to call it `0.19.0` (granted I'm not sure how/if I got the time right now). E.g. some of the exit status confusions we're facing right now.

While I understand the sentiment that it's easier/nicer to use a real release please also consider that it's very easy for you to switch :)

Cheers,
Tobi

**Comment by jar349** [comment]
All very reasonable.  I've already built the gem from master because we vendor our gems.  A few things:
1. Thanks for SimpleCov; it's great!
1. `enable_for_subprocesses` on master works for me
