### ISSUE TITLE
Fail if coverage under threshold

### ISSUE THREAD

**Issue by jpatokal** [colszowka/simplecov#96]
In rcov, you can pass in an argument like "--failure-threshold 100" to fail your build if coverage is less than 100%.  Am I missing something obvious, or is there no way to easily do this with SimpleCov?  Writing a custom at_exit handler sounds a bit painful.

**Comment by tcd** [comment]
Did this get some sort of resolution?

**Comment by PragTob** [comment]
@tcd yes as Christoph pointed out it was released more than 7 years ago: https://github.com/colszowka/simplecov#minimum-coverage
