### ISSUE TITLE
Framework detection wrong with MiniTest::Spec

### ISSUE THREAD

**Issue by conradwt** [colszowka/simplecov#97]
When running tests using Minitest::Spec, I'm getting the following message indicating that I'm using RSpec:

Coverage report generated for RSpec to  /path/to/coverage. 11 / 11 LOC (100.0%) covered.

The message should be something similar to the following:

Coverage report generated for Minitest::Spec to /path/to/coverage. 11 / 11 LOC (100.0%) covered.

**Comment by bf4** [comment]
Closing as stale. Please reopen if this is still an issue. (And take a look at https://github.com/colszowka/simplecov/issues/340 )
