### ISSUE TITLE
coverage data provided by Coverage exceeds number of lines

### ISSUE THREAD

**Issue by dnagir** [colszowka/simplecov#98]
``` sh
> jruby -v
jruby 1.6.5 (ruby-1.9.2-p136) (2011-10-25 9dcd388) (Java HotSpot(TM) Client VM 1.6.0_29) [darwin-i386-java]

> bundle exec rspec spec/
Warning: coverage data provided by Coverage [40] exceeds number of lines in /Users/dnagir/proj/neo4j/spec/../lib/neo4j/core_ext/class/inheritable_attributes.rb [37]
```

There is a [resolved issue](https://github.com/colszowka/simplecov/pull/63), but it seems to be a different one.

Is there any way to fix it?

**Comment by rbwendt** [comment]
I can confirm that emptying the contents of your `coverage` folder will fix this problem.

**Comment by joshuapinter** [comment]
Seeing this in 2023 now after enabling `enable_coverage_for_eval` after support for `eval` coverage was introduced in version 0.22.0: 

https://github.com/simplecov-ruby/simplecov/pull/1037

If I remove/disable `enable_coverage_for_eval` then these messages go away. 

I'm adding it here as an easy reference point for others seeing this in the latest release.
